### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by naim-mckay** [sourcegraph/jetbrains#1012]
Plugin version: ```5.3.3914```
IDE version: ```IU-222.3739.54```
Stacktrace:
```text
java.util.concurrent.ExecutionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$0(CodyAgentService.kt:124)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:84)
	... 10 more
Caused by: java.io.IOException: Cannot run program "/Users/naim.mckay/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/Sourcegraph/agent/agent-macos-x64": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.startAgentProcess(CodyAgent.kt:163)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.create(CodyAgent.kt:99)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:71)
	... 10 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 14 more

```

**Comment by taylorsperry** [comment]
closing in favor of https://github.com/sourcegraph/jetbrains/issues/723
