### ISSUE TITLE
bug: Inline Edits - does not handle errors in Fixup Apply

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1121]
### Installation Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210
### Describe the bug

Saw this happen once:

```
2024-03-18 09:06:32,461 [  46834]   WARN - #c.s.c.a.CodyAgent - Error
2024-03-18 09:06:32,461 [  46834]   WARN - #c.s.c.a.CodyAgent -     at FixupTask.set state (/Users/stevey/src/sg/cody/vscode/src/non-stop/FixupTask.ts:80:25)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at FixupController.setTaskState (/Users/stevey/src/sg/cody/vscode/src/non-stop/FixupController.ts:970:14)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at FixupController.error (/Users/stevey/src/sg/cody/vscode/src/non-stop/FixupController.ts:727:14)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at EditProvider.handleError (/Users/stevey/src/sg/cody/vscode/src/edit/provider.ts:193:32)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at EditProvider.handleResponse (/Users/stevey/src/sg/cody/vscode/src/edit/provider.ts:149:18)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at Object.onTurnComplete (/Users/stevey/src/sg/cody/vscode/src/edit/provider.ts:78:31)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at <anonymous> (/Users/stevey/src/sg/cody/lib/shared/src/chat/bot-response-multiplexer.ts:106:81)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at Array.map (<anonymous>)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at _BotResponseMultiplexer.notifyTurnComplete (/Users/stevey/src/sg/cody/lib/shared/src/chat/bot-response-multiplexer.ts:106:52)
2024-03-18 09:06:32,462 [  46835]   WARN - #c.s.c.a.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

The FixupController (actually EditProvider) has encountered an error applying the fixup. It sends an error (as a lens?) to the client, so that we can show the user and clean up the task. 

We do not handle the error yet, and what happens is that the task becomes orphaned -- it remains on "Cody is working... Cancel" until you cancel it.

### Expected behavior

It should report a failure to apply the fixup to the user somehow (popup notification? cody console?)

It should also clean up the task.

### Additional context

Since this is an unusual error, we'll have to simulate it on the Agent side when testing it.

**Comment by steveyegge** [comment]
Here's what I see in the trace log:

`-> {
    "jsonrpc": "2.0",
    "method": "editTask/didUpdate",
    "params": {
        "id": "ltxm",
        "state": 7,
        "error": {
            "message": "Cody did not respond with any text",
            "stack": "Error: Cody did not respond with any text\n    at EditProvider.handleResponse (/Users/stevey/src/sg/cody/vscode/src/edit/provider.ts:149:30)\n    at Object.onTurnComplete (/Users/stevey/src/sg/cody/vscode/src/edit/provider.ts:78:31)\n    at <anonymous> (/Users/stevey/src/sg/cody/lib/shared/src/chat/bot-response-multiplexer.ts:106:81)\n    at Array.map (<anonymous>)\n    at _BotResponseMultiplexer.notifyTurnComplete (/Users/stevey/src/sg/cody/lib/shared/src/chat/bot-response-multiplexer.ts:106:52)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        },
        "selectionRange": {
            "start": {
                "line": 189,
                "character": 0
            },
            "end": {
                "line": 201,
                "character": 5
            }
        }
    }
}`

We are not handling the case where the task state is Error, in `FixupSession.update`.

**Comment by steveyegge** [comment]
cc: @danielmarquespt -- I don't have a good sense of how we want to display errors during Inline Edits.

**Comment by kalanchan** [comment]
All complete as part of `6.0.0`
