### ISSUE TITLE
bug: java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by hosamaly** [sourcegraph/jetbrains#1126]
### Cody Version

5.4.358

### IDE Information

RubyMine 2023.3.5
Build #RM-233.14808.14, built on March 8, 2024
Licensed to Hosam Aly
Subscription is active until October 23, 2024.
Runtime version: 17.0.10+1-b1087.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
  org.jetbrains.plugins.go-template (233.11799.172)
  com.intellij.ideolog (222.3.2.0)
  net.codestats.plugin.atom.intellij (1.0.9)
  com.jetbrains.CyanTheme (1.3)
  com.jetbrains.darkPurpleTheme (1.3)
  com.intellij.kubernetes (233.14475.2)
  com.sourcegraph.jetbrains (5.4.358)

### Describe the bug

I've just upgraded the IDE from v2023.3.3 to v2023.3.5. It's been quite some time since I've used it; maybe a month or more. The error showed up immediately after opening a project, and then again after I've run `bundle install`.

The project is on Ruby 2.6 if this makes any difference.

### Expected behavior

No errors

### Additional context

Stacktrace:
```text
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.getNow(CompletableFuture.java:2134)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.isConnected(CodyAgentService.kt:161)
	at com.sourcegraph.cody.statusbar.CodyStatusService.didStatusChanged(CodyStatusService.kt:64)
	at com.sourcegraph.cody.statusbar.CodyStatusService.onCodyAutocompleteStatusReset$lambda$1(CodyStatusService.kt:43)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 7 more
Caused by: java.io.IOException: Cannot run program "/Users/hosamaly/Library/Application Support/JetBrains/RubyMine2023.3/plugins/Sourcegraph/agent/agent-macos-x64": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.startAgentProcess(CodyAgent.kt:163)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.create(CodyAgent.kt:99)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:61)
	... 10 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 14 more

```

**Comment by taylorsperry** [comment]
Thanks for the report, @hosamaly. I've added this to https://github.com/sourcegraph/jetbrains/issues/723 where we'll be sure to look into it 👍
