### ISSUE TITLE
bug: java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by thewoolleyman** [sourcegraph/jetbrains#1139]
### Cody Version

5.4.358

### IDE Information

RubyMine 2023.3.5
Build #RM-233.14808.14, built on March 8, 2024
Licensed to Chad Woolley
You have a perpetual fallback license for this version.
Subscription is active until July 7, 2025.
Runtime version: 17.0.10+1-b1087.21 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 12000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.tree.horizontal.default.autoscrolling=false
  ide.tooltip.initialDelay=0
  ide.tooltip.showAllSeverities=true
  ide.win.file.chooser.native=true
  vcs.enable.add.ignored.directories.to.exclude=false
  parameter.info.max.visible.rows=10
  actionSystem.fix.alt.gr=false
  show.diff.preview.as.editor.tab.with.single.click=true
  search.everywhere.settings=true
  ide.debug.in.title=true
  search.everywhere.pattern.checking=false
  ide.require.transaction.for.model.changes=false
  performance.watcher.unresponsive.interval.ms=1000
  light.edit.file.open.enabled=false
  ide.experimental.ui=true
  ide.mac.bigsur.window.with.tabs.enabled=false
  ea.enable.developers.list=false
Non-Bundled Plugins:
  some.awesome (1.15)
  de.netnexus.camelcaseplugin (3.0.12)
  awesome.console (0.1337.12)
  com.github.si9ma.codetimejetbrains (0.0.9)
  com.intellij.plugins.watcher (233.13135.65)
  PlantUML integration (7.7.0-IJ2023.2)
  co.anbora.labs.todo.export (1.5.2)
  org.jetbrains.plugins.localization (233.11799.188)
  Key Promoter X (2023.3.0)
  com.bennycode.linessorterplus (1.2.0)
  com.intellij.mermaid (0.0.20+IJ.232)
  dev.feedforward.tldrintellij (0.0.2)
  com.github.copilot (1.5.0.5148)
  izhangzhihao.rainbow.brackets (2024.2.1)
  com.intellij.lang.jsgraphql (233.14808.14)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  com.gitlab.plugin (1.0.1)
  com.majera.intellij.codereview.gitlab (2024.1.3.233)
  mobi.hsz.idea.gitignore (4.5.2)
  com.sourcegraph.jetbrains (5.4.358)
  ru.adelf.idea.dotenv (2024.1)

### Describe the bug

Error message when opening the IDE

### Expected behavior

Don't know, wasn't using Cody, just got the error message.

### Additional context

Stacktrace:
```text
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.getNow(CompletableFuture.java:2134)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$1(CodyAgentService.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	... 7 more
Caused by: java.io.IOException: Cannot run program "/Users/cwoolley/Library/Application Support/JetBrains/RubyMine2023.3/plugins/Sourcegraph/agent/agent-macos-arm64": error=13, Permission denied
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.startAgentProcess(CodyAgent.kt:163)
	at com.sourcegraph.cody.agent.CodyAgent$Companion.create(CodyAgent.kt:99)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:61)
	... 12 more
Caused by: java.io.IOException: error=13, Permission denied
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 16 more

```

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/723
