### ISSUE TITLE
bug: java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Wrong line: 800. Available lines count: 229

### ISSUE THREAD

**Issue by taylorsperry** [sourcegraph/jetbrains#1234]
### Cody Version

5.5.1-nightly

### IDE Information

IntelliJ IDEA 2023.3.3 (Ultimate Edition)
Build #IU-233.14015.106, built on January 24, 2024
Licensed to Sourcegraph / Taylor Sperry
Subscription is active until May 12, 2024.
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.ml.llm (233.14015.147)
  com.sourcegraph.jetbrains (5.5.1-nightly)
Kotlin: 233.14015.106-IJ

### Describe the bug

* I highlighted some code and ran an edit command
* Then I highlighted a different selection of code and ran edit again
* Cody hung on "Cody is working" and I saw this error

### Expected behavior

Cody should apply the edit

### Additional context

Stacktrace:

```text
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: Wrong line: 800. Available lines count: 229
 at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
 at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
 at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
 at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
 at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
 at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$0(CodyAgentClient.java:86)
 at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
 at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
 at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
 at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
 at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
 at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
 at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
 at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
 at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
 at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
 at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
 at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
 at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IndexOutOfBoundsException: Wrong line: 800. Available lines count: 229
 at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:197)
 at com.intellij.openapi.editor.impl.LineSet.getLineStart(LineSet.java:178)
 at com.intellij.openapi.editor.impl.DocumentImpl.getLineStartOffset(DocumentImpl.java:1012)
 at com.sourcegraph.cody.edit.FixupSession.createMarkerForEdit(FixupSession.kt:318)
 at com.sourcegraph.cody.edit.FixupSession.access$createMarkerForEdit(FixupSession.kt:43)
 at com.sourcegraph.cody.edit.FixupSession$performInlineEdits$1.invoke(FixupSession.kt:295)
 at com.sourcegraph.cody.edit.FixupSession$performInlineEdits$1.invoke(FixupSession.kt:289)
 at com.sourcegraph.cody.edit.widget.LensWidgetGroup.withListenersMuted(LensWidgetGroup.kt:92)
 at com.sourcegraph.cody.edit.FixupSession.performInlineEdits(FixupSession.kt:289)
 at com.sourcegraph.cody.edit.FixupSession.performWorkspaceEdit(FixupSession.kt:275)
 at com.sourcegraph.cody.agent.CodyAgentService$1.invoke$lambda$4(CodyAgentService.kt:57)
 at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$0(CodyAgentClient.java:80)
 ... 40 more
 
```

**Comment by taylorsperry** [comment]
Just tried to repro this again today and can't, so might be flaky.

**Comment by odisseus** [comment]
Could it be that the first edit hasn't finished when you requested the second one?

**Comment by odisseus** [comment]
I have just run into a very similar issue:
```
java.lang.IndexOutOfBoundsException: Wrong line: 50. Available lines count: 23
```
It is worth noting that the file has more than 150 lines, and the selected lines were 36-52.

**Comment by kalanchan** [comment]
closing, will reopen if it happens again
