### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by kerbymart** [sourcegraph/jetbrains#1251]
Plugin version: `5.3.3914`
IDE version: `IU-233.15026.9`
Stacktrace:

```text
java.util.concurrent.ExecutionException: java.lang.Exception: Failed to start Cody agent
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgentRestartIfNeeded$lambda$1(CodyAgentService.kt:135)
 at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
 at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Failed to start Cody agent
 at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:84)
 ... 10 more
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Cody agent binary not found at path C:\Users\Kerby\AppData\Roaming\JetBrains\IntelliJIdea2023.3\plugins\Sourcegraph\agent\agent-win-x64.exe
 
```

**Comment by mkondratek** [comment]
Hello @kerbymart 👋 we are sorry you experience this issue. also, thank you for posting your problem here - it's the most effective way to track and solve problems.

Can you try the latest version of the plugin?
Can you provide some specific steps to reproduce the problem?
