### ISSUE TITLE
bug: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed

### ISSUE THREAD

**Issue by pkukielka** [sourcegraph/jetbrains#1276]
### Cody Version

5.5.0

### IDE Information

Most likely all IntelliJ versions (to beverified)

### Describe the bug

Cody agent crashes after some time, each file change then results in such error in the logs:

```
2024-04-02 18:18:53,483 [27134796]   INFO - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint - Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at jdk.proxy9/jdk.proxy9.$Proxy185.textDocumentDidOpen(Unknown Source)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.informAgentAboutEditorChange$lambda$2(CodyEditorFactoryListener.kt:186)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:146)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
	... 17 more
```

It seems to be it started to happen around cody version upgrade around dynamic multiline completions.
But if it is related or not I'm not sure.

### Expected behavior

It should not crash

**Comment by taylorsperry** [comment]
@pkukielka This was also [reported](https://github.com/sourcegraph/jetbrains/issues/1282) by a customer and a [user](https://community.sourcegraph.com/t/unable-to-use-cody-phpstorm-2023-3-6/52) in Discourse. We should take a look.

**Comment by kalanchan** [comment]
@aramaraju could you ask the customer to get an recording/screenshot if this happens again, or ask for reproducible steps

**Comment by aramaraju** [comment]
@kalanchan @pkukielka it doesn't seem like there is one proper way to reproduce this on their end. Their response was "I just keep the editor open. It keep crashing. When I open the cody window and type some like “Hello”, it wakes up again and then after some time crashes. Some thing like crashing on inactivity."

**Comment by pkukielka** [comment]
Looks like the problem is gone when using newest version of Cody, most likely due to some bigger structural changes.
After merging [commit bump](https://github.com/sourcegraph/jetbrains/pull/1295) I'm going to do a QA release with those changes.

**Comment by taylorsperry** [comment]
Reopening because this isn't resolved. Ongoing conversation with @valerybugakov @philipp-spiess and @pkukielka [here](https://sourcegraph.slack.com/archives/C05AGQYD528/p1712644535812079).

**Comment by philipp-spiess** [comment]
https://sourcegraph.slack.com/archives/C05AGQYD528/p1712927530401899?thread_ts=1712644535.812079&cid=C05AGQYD528 big update in Slack

**Comment by kalanchan** [comment]
from triaging:

Bug still not completely fixed, possible solutions
- continue to restart agent on every crash
- disable multi line completions

@pkukielka to follow up

**Comment by taylorsperry** [comment]
@pkukielka has identified the root cause of this issue ([thread](https://sourcegraph.slack.com/archives/C05B7C6FBPX/p1713973077198629)) and expects the fix to land next week.
