### ISSUE TITLE
bug: Slow or no response when doing auto-complete in IntelliJ

### ISSUE THREAD

**Issue by mike-r-mclaughlin** [sourcegraph/jetbrains#1282]
### Cody Version

5.5.0

### IDE Information

IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Licensed to REDACTED / REDACTED
You have a perpetual fallback license for this version.
Subscription is active until REDACTED.
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 8000M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (233.15026.16)
  CheckStyle-IDEA (5.89.1)
  com.jetbrains.packagesearch.intellij-plugin (233.11800.8)
  com.sourcegraph.jetbrains (5.5.0)
Kotlin: 233.15026.9-IJ

### Describe the bug

Very slow responses and in some cases no response at all for code completions.  Details in [this Slack thread](https://sourcegraph.slack.com/archives/C06RSJNG3FX/p1712155654729529).

`idea.log`:
```
2024-04-03 10:50:51,201 [84130023]   INFO - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint - Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at jdk.proxy10/jdk.proxy10.$Proxy177.textDocumentDidOpen(Unknown Source)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.informAgentAboutEditorChange$lambda$2(CodyEditorFactoryListener.kt:186)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:146)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
	... 15 more
```

### Expected behavior

User sees response within a few seconds

### Additional context

Customer is https://github.com/sourcegraph/accounts/issues/8251

**Comment by morgangauth** [comment]
This is also occurring at https://github.com/sourcegraph/accounts/issues/285

**Comment by mike-r-mclaughlin** [comment]
this seems to be a duplicate of #1276
