### ISSUE TITLE
JetBrains: Error occurred "java.lang.NullPointerException: get(...) must not be null"

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1285]
### Cody Version

v5.5.2

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  PythonCore (233.14475.9)
  com.sourcegraph.jetbrains (5.5.2)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ IDEA editor
2. Open/close the editor frequently

### Observed behavior:

Error occurred with a stacktrace below,
Stacktrace:

```text
java.lang.NullPointerException: get(...) must not be null
 at com.sourcegraph.cody.chat.AgentChatSession$Companion.createFromState(AgentChatSession.kt:355)
 at com.sourcegraph.cody.chat.AgentChatSessionService.getOrCreateFromState(AgentChatSessionService.kt:32)
 at com.sourcegraph.cody.CodyToolWindowContent.selectChat(CodyToolWindowContent.kt:137)
 at com.sourcegraph.cody.CodyToolWindowContent.access$selectChat(CodyToolWindowContent.kt:28)
 at com.sourcegraph.cody.CodyToolWindowContent$historyTree$1.invoke(CodyToolWindowContent.kt:35)
 at com.sourcegraph.cody.CodyToolWindowContent$historyTree$1.invoke(CodyToolWindowContent.kt:35)
 at com.sourcegraph.cody.history.HistoryTree.selectLeaf(HistoryTree.kt:180)
 at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.kt:190)
 at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.kt:176)
 at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
 at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:58)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
 at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
 at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
 at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:434)
 at java.desktop/java.awt.Component.processEvent(Component.java:6422)
 at java.desktop/java.awt.Container.processEvent(Container.java:2266)
 at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
 at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
 at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:635)
 at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:580)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:580)
 at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
 at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
 at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
 at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
 at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
 
```

### Expected behavior

Cody should not throw error on opening/closing the editor.

### Additional context

*No responses*

**Comment by mkondratek** [comment]
It looks like we timed out there:
```
return agentChatSession.completeOnTimeout(null, 15, TimeUnit.SECONDS).get()
```

**Comment by pkukielka** [comment]
I think that timeout is not a correct thing to do.
If someone will just start the IDE and open chat from a history immediately, agent might be still not started.
And we know that it sometimes takes even more than 30s to start it, on some machines.
We should define some global timeout value (be it 45s or 60s) and if really needed use it in every such place.
Also, we need some error handling around every place we are using `completeOnTimeout `
