### ISSUE TITLE
Reconnect Automatically

### ISSUE THREAD

**Issue by Satsrag** [sourcegraph/jetbrains#1311]
### Cody Version

5.5.2

### IDE Information

PhpStorm 2023.3.6
Build #PS-233.15026.12, built on March 21, 2024
Licensed to tian lan
Subscription is active until April 26, 2024.
For educational use only.
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (233.15026.16)
  de.espend.idea.php.annotation (10.0.0)
  com.github.copilot (1.5.1.5285)
  com.sourcegraph.jetbrains (5.5.2)

### Describe the bug

I have tried the Cody for a few days. But there is one terrible issue. I connect Cody by a VPN. Cody disconnects normally maybe because of the VPN's unstable and did not reconnect for me after that. I must restart my IDE to reconnect it. The GitHub Copilot does not have this problem. It may not disconnect or may try to reconnect automatically and has a button to reconnect. But I don't like it gives me more wrong code.

### Expected behavior

Hopefully, try to reconnect automatically or improve connecting stability and give a reconnect button.

### Additional context

2024-04-12 10:39:05,937 [ 739282]   INFO - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint - Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at jdk.proxy7/jdk.proxy7.$Proxy163.textDocumentDidOpen(Unknown Source)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.informAgentAboutEditorChange$lambda$2(CodyEditorFactoryListener.kt:189)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:165)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
	... 17 more

**Comment by mkondratek** [comment]
hello @Satsrag 👋 first, we are sorry you are experiencing this issue 🙇 we are doing our best to continuously improve the plugin 🔧 thank you for reporting it as the GitHub issue - it's the most effective way 🚀 

The problem you encountered is a bit complex but the team is on it. Let me close this issue in favor of the original report: https://github.com/sourcegraph/jetbrains/issues/1276. 

As a workaround you can try quickly `Shift Shift` to search everywhere in the IDE and search for action  "Restart Cody Agent":
![image](https://github.com/sourcegraph/jetbrains/assets/19799111/ec6da2cf-4f9e-42ca-af42-434db3372d67)

It can temporarily fix the problem.
