### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.source...

### ISSUE THREAD

**Issue by ubranch** [sourcegraph/jetbrains#1315]
### Cody Version

5.5.5

### IDE Information

GoLand 2024.1
Build #GO-241.14494.238, built on March 28, 2024
Licensed to gurgles tumbles
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12

### Describe the bug

-

### Expected behavior

-

### Additional context

Stacktrace:
```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.cody.history.ChatHistoryPanel$LeafPopupAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by ubranch** [comment]
DUPLICATE

https://github.com/sourcegraph/jetbrains/issues/1299
https://github.com/sourcegraph/jetbrains/issues/1297
https://github.com/sourcegraph/jetbrains/issues/1296
https://github.com/sourcegraph/jetbrains/issues/1290
https://github.com/sourcegraph/jetbrains/issues/1288

**Comment by odisseus** [comment]
This problem is of the same kind as #1327.
