### ISSUE TITLE
bug: Auto suggestions Stop working

### ISSUE THREAD

**Issue by raznar** [sourcegraph/jetbrains#1352]
### Cody Version

5.5.5

### IDE Information

JetBrains Rider 2023.3.4
Build #RD-233.14475.66, built on March 6, 2024
Licensed to
You have a perpetual fallback license for this version.
Subscription is active until March 18, 2025.
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
.NET Core v7.0.10 ARM64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  IdeaVIM (2.10.2)
  PythonCore (233.14475.9)
  com.intellij.ml.llm (233.14475.74)
  com.sourcegraph.jetbrains (5.5.5)

### Describe the bug

A user from [this customer](https://github.com/sourcegraph/accounts/issues/8857) is reporting that cody auto suggestions stop working and they have to restart the IDE to get it to work again

![image](https://uploads.linear.app/15b96a4d-ffc0-481a-ba9c-9d840020f7bc/d3277445-af5d-42c6-a717-d5024174e6a7/55eae17f-fd14-47f2-a0d7-694c045f6022?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzE1Yjk2YTRkLWZmYzAtNDgxYS1iYTljLTlkODQwMDIwZjdiYy9kMzI3NzQ0NS1hZjVkLTQyYzYtYTcxNy1kNTAyNDE3NGU2YTcvNTVlYWUxN2YtZmQxNC00N2YyLWEwZDctNjk0YzA0NWY2MDIyIiwiaWF0IjoxNzE3NDQ4OTQ0LCJleHAiOjMzMjg4MDA4OTQ0fQ.0xIkmSCwtEnV6P5ePpP3CrmRreuuOABT1Vidn94Nvg0)

### Expected behavior

Cody should have helpful error or troubleshooting when it encounters an unexpected error

### Additional context

[Slack thread
](https://sourcegraph.slack.com/archives/C069NN7LTCN/p1713483213549449)

```
2024-04-18 15:45:12,794 [90833760]   INFO - org.eclipse.lsp4j.jsonrpc.RemoteEndpoint - Failed to send notification message.
org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:72)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.notify(RemoteEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(EndpointProxy.java:88)
	at jdk.proxy7/jdk.proxy7.$Proxy158.textDocumentDidOpen(Unknown Source)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.informAgentAboutEditorChange$lambda$2(CodyEditorFactoryListener.kt:189)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:165)
	at com.intellij.codeWithMe.ClientId$Companion.decorateRunnable$lambda$4(ClientId.kt:366)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Stream closed
	at java.base/java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:445)
	at java.base/java.io.OutputStream.write(OutputStream.java:162)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127)
	at java.base/java.io.FilterOutputStream.write(FilterOutputStream.java:108)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:67)
	... 18 more
```

**Comment by taylorsperry** [comment]
Thank you for reporting, @raznar! I believe this is the same issue that's being addressed in https://github.com/sourcegraph/jetbrains/issues/1276. @pkukielka would you please re-open if I'm wrong about that?
