### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Right-hand side of 'instanceof' is...

### ISSUE THREAD

**Issue by alexfazio** [sourcegraph/jetbrains#1359]
### Cody Version

5.5.5

### IDE Information

PyCharm 2023.1.4 (Professional Edition)
Build #PY-231.9225.15, built on July 11, 2023
Licensed to Alex Fazio
You have a perpetual fallback license for this version.
Subscription is active until June 28, 2024.
Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    dev.patrickpichler.darculaPitchBlackTheme (1.0.0)
    net.antelle.intellij-xcode-dark-theme (1.2.4)
    com.samdark.intellij-visual-studio-code-dark-plus (2.8)
    com.github.copilot (1.5.2.5345)
    Dart (231.9161.14)
    com.almightyalpaca.intellij.plugins.discord (1.12.0)
    com.jetbrains.lang.ejs (231.8109.91)
    ru.meanmail.plugin.requirements (2022.4.1)
    net.ashald.envfile (3.4.2)
    ru.adelf.idea.dotenv (2024.1)
    com.sourcegraph.jetbrains (5.5.5)

### Describe the bug

Despite being notified by the IDE about a coding error, Cody continued to work without any interruptions.

### Expected behavior

Despite being notified by the IDE about a coding error, Cody continued to work without any interruptions.

### Additional context

Stacktrace:
```text
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Right-hand side of 'instanceof' is not an object

TypeError: Right-hand side of 'instanceof' is not an object
    at IndexManager.forceRefreshIndex (/snapshot/cody-b7f375c3a9af847dac6a7f58f252d47cc3deb8f3/agent/dist/index.js:174106:23)
    at async Object.callback (/snapshot/cody-b7f375c3a9af847dac6a7f58f252d47cc3deb8f3/agent/dist/index.js:174142:13)
    at async /snapshot/cody-b7f375c3a9af847dac6a7f58f252d47cc3deb8f3/agent/dist/index.js:199732:11
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.context.ui.ReindexButton$actionPerformed$1$1.run(ReindexButton.kt:33)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Right-hand side of 'instanceof' is not an object

TypeError: Right-hand side of 'instanceof' is not an object
    at IndexManager.forceRefreshIndex (/snapshot/cody-b7f375c3a9af847dac6a7f58f252d47cc3deb8f3/agent/dist/index.js:174106:23)
    at async Object.callback (/snapshot/cody-b7f375c3a9af847dac6a7f58f252d47cc3deb8f3/agent/dist/index.js:174142:13)
    at async /snapshot/cody-b7f375c3a9af847dac6a7f58f252d47cc3deb8f3/agent/dist/index.js:199732:11
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

```

**Comment by mkondratek** [comment]
hello 👋 thanks for the report - we are sorry you experience that

closing in favor of https://github.com/sourcegraph/jetbrains/issues/650
