### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.source...

### ISSUE THREAD

**Issue by marc-gist** [sourcegraph/jetbrains#1375]
### Cody Version

latest

### IDE Information

PyCharm 2024.1 (Professional Edition)
Build #PY-241.14494.241, built on March 28, 2024
Licensed to Marc Reid
Subscription is active until February 4, 2025.
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (241.14494.150)
  com.intellij.ml.llm (241.14494.320)
  com.sourcegraph.jetbrains (5.5.5)

### Describe the bug

code completion suggestions flash quickly on the screen, no time to read or execute them.

### Expected behavior

code suggestions to stay long enough to read them!

### Additional context

Stacktrace:

```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.website.SearchSelectionAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
 at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
 at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
 at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
 at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
 at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
 
```

**Comment by taylorsperry** [comment]
closing in favor of https://github.com/sourcegraph/jetbrains/issues/1404
