### ISSUE TITLE
bug: java.lang.AssertionError

### ISSUE THREAD

**Issue by Nopik** [sourcegraph/jetbrains#1389]
### Cody Version

5.5.5

### IDE Information

goland

### Describe the bug

I tried to see historical chat, double clicked on some entry in historical chat list, then goland got frozen for about 1 minute or so - nothing was working, not responsive to mouse clicks nor keyboard, no editor etc. After a long while whole IDE unfreezed.

### Expected behavior

no crash

### Additional context

Stacktrace:
```text
java.lang.AssertionError
	at com.intellij.util.ui.tree.TreeUtil.repaintPath(TreeUtil.java:157)
	at com.intellij.ui.tree.ui.DefaultTreeUI.repaintPath(DefaultTreeUI.java:239)
	at com.intellij.ui.tree.ui.DefaultTreeUI$5.propertyChange(DefaultTreeUI.java:838)
	at java.desktop/java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:343)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:335)
	at java.desktop/java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:268)
	at java.desktop/java.awt.Component.firePropertyChange(Component.java:8759)
	at com.intellij.ui.treeStructure.Tree.firePropertyChange(Tree.java:575)
	at java.desktop/javax.swing.JTree.setLeadSelectionPath(JTree.java:1742)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setLeadSelectionPath(BasicTreeUI.java:2813)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.setLeadSelectionPath(BasicTreeUI.java:2804)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.valueChanged(BasicTreeUI.java:4251)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:650)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:783)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1120)
	at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:306)
	at java.desktop/javax.swing.JTree.setSelectionPaths(JTree.java:1723)
	at java.desktop/javax.swing.JTree.setSelectionRows(JTree.java:1806)
	at java.desktop/javax.swing.JTree.setSelectionRow(JTree.java:1781)
	at com.intellij.ui.CheckboxTreeBase.<init>(CheckboxTreeBase.java:40)
	at com.intellij.ui.CheckboxTree.<init>(CheckboxTree.java:30)
	at com.sourcegraph.cody.context.ui.EnhancedContextPanel.<init>(EnhancedContextPanel.kt:64)
	at com.sourcegraph.cody.chat.ui.ChatPanel.<init>(ChatPanel.kt:43)
	at com.sourcegraph.cody.chat.AgentChatSession.<init>(AgentChatSession.kt:55)
	at com.sourcegraph.cody.chat.AgentChatSession.<init>(AgentChatSession.kt)
	at com.sourcegraph.cody.chat.AgentChatSession$Companion$createFromState$1.invoke(AgentChatSession.kt:351)
	at com.sourcegraph.cody.chat.AgentChatSession$Companion$createFromState$1.invoke(AgentChatSession.kt:348)
	at com.sourcegraph.cody.chat.AgentChatSession$Companion.createNewPanel$lambda$6(AgentChatSession.kt:367)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:165)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by dominiccooney** [comment]
Not sure about the exact assertion without a Goland version, but this is probably invoking Swing on a background thread instead of EDT.

This should be fixed by @pkukielka in #1351
