### ISSUE TITLE
bug: java.lang.NullPointerException: get(...) must not be null

### ISSUE THREAD

**Issue by Nopik** [sourcegraph/jetbrains#1390]
### Cody Version

5.5.5

### IDE Information

goland

### Describe the bug

crash

### Expected behavior

no crash

### Additional context

Stacktrace:

```text
java.lang.NullPointerException: get(...) must not be null
 at com.sourcegraph.cody.chat.AgentChatSession$Companion.createFromState(AgentChatSession.kt:358)
 at com.sourcegraph.cody.chat.AgentChatSessionService.getOrCreateFromState(AgentChatSessionService.kt:32)
 at com.sourcegraph.cody.CodyToolWindowContent.selectChat(CodyToolWindowContent.kt:138)
 at com.sourcegraph.cody.CodyToolWindowContent.access$selectChat(CodyToolWindowContent.kt:28)
 at com.sourcegraph.cody.CodyToolWindowContent$chatHistoryPanel$1.invoke(CodyToolWindowContent.kt:36)
 at com.sourcegraph.cody.CodyToolWindowContent$chatHistoryPanel$1.invoke(CodyToolWindowContent.kt:36)
 at com.sourcegraph.cody.history.ChatHistoryPanel.selectLeaf(ChatHistoryPanel.kt:182)
 at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.kt:190)
 at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.kt:176)
 at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:16)
 at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:62)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
 at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
 at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
 at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:442)
 at java.desktop/java.awt.Component.processEvent(Component.java:6422)
 at java.desktop/java.awt.Container.processEvent(Container.java:2266)
 at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
 at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:698)
 at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:637)
 at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$10(IdeEventQueue.kt:584)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
 at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
 at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1021)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
 at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1021)
 at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
 at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
 at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
 
```

**Comment by taylorsperry** [comment]
closing in favor of https://github.com/sourcegraph/jetbrains/issues/1285
