### ISSUE TITLE
bug: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAg (...)

### ISSUE THREAD

**Issue by JLSkyzer** [sourcegraph/jetbrains#1405]
Plugin version: `5.3.27`
IDE version: `IC-223.8214.52`
Stacktrace:

```text
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=Erinium Launcher, containerState=DISPOSE_COMPLETED, componentStore=C:\Users\killi\Desktop\Dev\Launcher Minecraft\Erinium Launcher) (disposed))
 at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
 at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:749)
 at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:721)
 at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:685)
 at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.getInstance(CodyAgentService.kt:149)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$0(CodyAgentService.kt:122)
 at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
 at java.base/java.lang.Thread.run(Thread.java:833)
 
```

**Comment by kalanchan** [comment]
hey there! this should be fixed in the latest JB release, please upgrade and see if it works for you. <br><br>Feel free to reopen if its still broken
