### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.source...

### ISSUE THREAD

**Issue by efren-corillo** [sourcegraph/jetbrains#1418]
### Cody Version

5.5.5

### IDE Information

Phpstorm 2024.1

### Describe the bug

is deprecated and going to be removed soon. 'com.source is all I got from the error message. i accidentally cleared it.

### Expected behavior

Not sure where it came from. it just showed up.

### Additional context

Stacktrace:

```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.website.OpenRevisionAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
 at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
 at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
 at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
 at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
 at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
 
```

**Comment by kalanchan** [comment]
this should be fixed in the latest JetBrains update! please upgrade and let us know if it works :)
