### ISSUE TITLE
bug: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1493]
### Cody Version

6e3cd8577afa7cac754ed354a5c2b77ea2ae3ed8

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

1. Open a project
2. Open a text file outside of the project
3. Write "An interpreter for S-expressions which can do arithmetic.", select it, and Cody, Generate Unit Test (new version)

The CodyAgentService line 80 is getting a URI, `untitled:eb57dd3f-85c0-433e-86a4-05bfe28fe85c.txt`

### Expected behavior

Don't throw.

### Additional context

Stacktrace:

```text
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
 at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:67)
 at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
 at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
 at org.eclipse.lsp4j.jsonrpc.TracingMessageConsumer.consume(TracingMessageConsumer.java:114)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
 at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
 at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
 ... 12 more
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
 at java.base/java.net.URI$Parser.fail(URI.java:2913)
 at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
 at java.base/java.net.URI$Parser.parse(URI.java:3119)
 at java.base/java.net.URI.(URI.java:685)
 at com.intellij.util.UriUtilKt.withScheme(UriUtil.kt:16)
 at com.sourcegraph.cody.agent.CodyAgentService$1.invoke$lambda$9(CodyAgentService.kt:80)
 at com.sourcegraph.cody.agent.CodyAgentClient.openUntitledDocument(CodyAgentClient.java:104)
 ... 17 more
 
```

**Comment by mkondratek** [comment]
IMHO it's a `P1`. We probably should disable `Generate Unit Test` for files outside the project.

**Comment by pkukielka** [comment]
@mkondratek After your recent changes regarding untitled documents  it just works.

**Comment by mkondratek** [comment]
after a re-review:
1. the problem **is not** related to the non-project files
2. the problem **is** related to some specific extensions - in particular it fails for `txt` and `md`

---

After [my recent changes](https://github.com/sourcegraph/cody/pull/4142) uuid-named files should not appear on the client side 🤔 we need to debug what is going on on the agent side and how such a file is sent to the client.

On the other hand - maybe we should disable `Generate Unit Tests` for some file types (or enable it only for some)? It clearly does not make sense to generate a test for a txt or md file.

**Comment by mkondratek** [comment]
The agent calls it from there:
https://sourcegraph.com/-/editor?remote_url=github.com%2Fsourcegraph%2Fcody&branch=main&file=vscode%2Fsrc%2Fedit%2Fprovider.ts&start_row=279&start_col=0&end_row=281&end_col=14&editor=JetBrains&version=v5.5.10-nightly
