### ISSUE TITLE
bug: java.lang.RuntimeException: Side effect not allowed: INVOKE_LATER

### ISSUE THREAD

**Issue by niazmr** [sourcegraph/jetbrains#1512]
### Cody Version

N/A

### IDE Information

IntelliJ

### Describe the bug

don't know

### Expected behavior

Step by step to show the debug process.

### Additional context

Stacktrace:

```text
java.lang.RuntimeException: Side effect not allowed: INVOKE_LATER
 at com.intellij.model.SideEffectGuard$Companion.checkSideEffectAllowed(SideEffectGuard.kt:21)
 at com.intellij.model.SideEffectGuard.checkSideEffectAllowed(SideEffectGuard.kt)
 at com.intellij.openapi.application.impl.LaterInvocator.invokeLater(LaterInvocator.java:79)
 at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:290)
 at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:274)
 at com.sourcegraph.cody.listeners.CodyDocumentListener.documentChangedNonBulk(CodyDocumentListener.kt:80)
 at com.intellij.openapi.editor.event.BulkAwareDocumentListener.documentChanged(BulkAwareDocumentListener.java:21)
 at jdk.internal.reflect.GeneratedMethodAccessor229.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:568)
 at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:119)
 at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:84)
 at jdk.proxy2/jdk.proxy2.$Proxy70.documentChanged(Unknown Source)
 at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$1(DocumentImpl.java:917)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:269)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:684)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
 at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:53)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:268)
 at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:914)
 at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:818)
 at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:658)
 at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:595)
 at com.intellij.psi.impl.PsiToDocumentSynchronizer.doCommitTransaction(PsiToDocumentSynchronizer.java:212)
 at com.intellij.psi.impl.PsiToDocumentSynchronizer.lambda$commitTransaction$1(PsiToDocumentSynchronizer.java:188)
 at com.intellij.psi.impl.PsiToDocumentSynchronizer.lambda$doSync$0(PsiToDocumentSynchronizer.java:106)
 at com.intellij.psi.impl.PsiToDocumentSynchronizer.performAtomically(PsiToDocumentSynchronizer.java:124)
 at com.intellij.psi.impl.PsiToDocumentSynchronizer.doSync(PsiToDocumentSynchronizer.java:106)
 at com.intellij.psi.impl.PsiToDocumentSynchronizer.commitTransaction(PsiToDocumentSynchronizer.java:188)
 at com.intellij.pom.core.impl.PomModelImpl.commitTransaction(PomModelImpl.java:195)
 at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$1(PomModelImpl.java:151)
 at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:535)
 at com.intellij.pom.core.impl.PomModelImpl.lambda$runTransaction$2(PomModelImpl.java:103)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:269)
 at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
 at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:57)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:268)
 at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:92)
 at com.intellij.psi.impl.source.tree.ChangeUtil.prepareAndRunChangeAction(ChangeUtil.java:141)
 at com.intellij.psi.impl.source.tree.CompositeElement.replaceChild(CompositeElement.java:632)
 at com.intellij.psi.impl.source.codeStyle.CodeEditUtil.replaceChild(CodeEditUtil.java:162)
 at com.intellij.psi.impl.source.tree.CompositeElement.replaceChildInternal(CompositeElement.java:463)
 at com.intellij.psi.impl.java.stubs.LambdaExpressionElementType$1.replaceChildInternal(LambdaExpressionElementType.java:40)
 at com.intellij.psi.impl.source.tree.SharedImplUtil.doReplace(SharedImplUtil.java:194)
 at com.intellij.psi.impl.source.JavaStubPsiElement.replace(JavaStubPsiElement.java:108)
 at com.intellij.psi.LambdaUtil.specifyLambdaParameterTypes(LambdaUtil.java:1276)
 at com.intellij.psi.LambdaUtil.specifyLambdaParameterTypes(LambdaUtil.java:1266)
 at com.siyeh.ig.style.LambdaParameterTypeCanBeSpecifiedInspection$InferLambdaParameterTypeFix.applyFix(LambdaParameterTypeCanBeSpecifiedInspection.java:97)
 at com.intellij.modcommand.PsiUpdateModCommandQuickFix.lambda$perform$0(PsiUpdateModCommandQuickFix.java:14)
 at com.intellij.modcommand.ModCommand.lambda$psiUpdate$2(ModCommand.java:234)
 at com.intellij.lang.impl.modcommand.PsiUpdateImpl$1.run(PsiUpdateImpl.java:55)
 at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.lambda$postponeFormattingInside$2(PostprocessReformattingAspectImpl.java:139)
 at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:148)
 at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:138)
 at com.intellij.lang.impl.modcommand.PsiUpdateImpl.psiUpdate(PsiUpdateImpl.java:65)
 at com.intellij.lang.impl.modcommand.ModCommandServiceImpl.psiUpdate(ModCommandServiceImpl.java:47)
 at com.intellij.modcommand.ModCommand.psiUpdate(ModCommand.java:212)
 at com.intellij.modcommand.ModCommand.psiUpdate(ModCommand.java:234)
 at com.intellij.modcommand.PsiUpdateModCommandQuickFix.perform(PsiUpdateModCommandQuickFix.java:14)
 at com.intellij.modcommand.ModCommandQuickFix.generatePreview(ModCommandQuickFix.java:55)
 at com.intellij.codeInspection.e...
```

**Comment by kalanchan** [comment]
@mkondratek Should also review similar issues like this with the latest intelliJ versions

**Comment by mkondratek** [comment]
hello @niazmr 👋  thank you for your report - I just tried to play with the plugin but I couldn't reproduce your issue. 

Let me close this one. I hope you will not see it again. But if you encounter it please provide more specific steps to reproduce 🙏 

--- 

btw: I run the plugin with the latest IntelliJ snapshot.

**Comment by adam0white** [comment]
I've received a similar error:
Stacktrace:
```text
CompositeException (3 nested):
------------------------------
[1]: com.intellij.model.SideEffectGuard$SideEffectNotAllowedException: Side effect not allowed: INVOKE_LATER
	at com.intellij.model.SideEffectGuard$Companion.checkSideEffectAllowed(SideEffectGuard.kt:21)
	at com.intellij.model.SideEffectGuard.checkSideEffectAllowed(SideEffectGuard.kt)
	at com.intellij.openapi.application.impl.LaterInvocator.invokeLater(LaterInvocator.java:79)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:290)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeLater(ApplicationImpl.java:274)
	at com.sourcegraph.cody.listeners.CodyDocumentListener.documentChangedNonBulk(CodyDocumentListener.kt:80)
	at com.intellij.openapi.editor.event.BulkAwareDocumentListener.documentChanged(BulkAwareDocumentListener.java:21)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:119)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:84)
	at jdk.proxy2/jdk.proxy2.$Proxy84.documentChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$1(DocumentImpl.java:923)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:269)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:268)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:920)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:824)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:664)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:598)
	at com.intellij.spellchecker.quickfixes.ChangeTo$ChangeToVariantAction.applyFix(ChangeTo.kt:68)
	at com.intellij.codeInspection.IntentionAndQuickFixAction.invoke(IntentionAndQuickFixAction.java:48)
	at com.intellij.codeInsight.intention.IntentionAction.generatePreview(IntentionAction.java:116)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.generatePreview(IntentionActionWithTextCaching.java:267)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable$invokePreview$1$1$1.invoke(IntentionPreviewComputable.kt:132)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable$invokePreview$1$1$1.invoke(IntentionPreviewComputable.kt:131)
	at com.intellij.model.SideEffectGuard$Companion.computeWithAllowedSideEffectsBlocking(SideEffectGuard.kt:42)
	at com.intellij.model.SideEffectGuard$Companion.computeWithoutSideEffects(SideEffectGuard.kt:27)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda$2$lambda$1(IntentionPreviewComputable.kt:131)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.lambda$postponeFormattingInside$2(PostprocessReformattingAspectImpl.java:139)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:148)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:138)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda$2(IntentionPreviewComputable.kt:130)
	at com.intellij.codeInsight.intention.preview.IntentionPreviewUtils.previewSession(IntentionPreviewUtils.java:123)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview(IntentionPreviewComputable.kt:129)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.generatePreview(IntentionPreviewComputable.kt:90)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.tryCreateDiffContent(IntentionPreviewComputable.kt:66)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:44)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.call(IntentionPreviewComputable.kt:38)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:840)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:872)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:604)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$4(NonBlockingReadActionImpl.java:567)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:958)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:93)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:155)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:138)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderPr...
```

**Comment by mkondratek** [comment]
@abdulisik - thanks for the update 

can you share more details? what os are you on? what version of the plugin are you using? any specific steps to repro? 🙏
