### ISSUE TITLE
bug: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by lwasyl** [sourcegraph/jetbrains#1533]
### Cody Version

5.5.10

### IDE Information

IntelliJ IDEA 2024.2 EAP (Ultimate Edition)
Build #IU-242.10180.25, built on May 15, 2024
Runtime version: 21.0.3+13-b446.1 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.8.0-76060800daily20240311-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  debugger.new.tool.window.layout=true
  vcs.non.modal.post.commit.checks=false
  keymap.windows.as.meta=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.macoskeymap (241.13688.16)
  org.nik.presentation-assistant (1.0.10)
  de.ehmkah.projects.imgdiff (1.11.0)
  String Manipulation (9.13.0)
  com.github.camork.fileExpander (2.5)
  com.jetbrains.performancePlugin.yourkit (242.10180.28)
  com.intellij.ml.llm (242.10180.28)
  com.intellij.lang.jsgraphql (242.10180.28)
  com.suusan2go.kotlin-fill-class (1.0.23)
  LivePlugin (0.8.8 beta)
  org.jetbrains.android (242.10180.25)
  com.android.tools.design (242.10180.25)
  com.developerphil.adbidea (1.6.4)
  com.sourcegraph.jetbrains (5.5.10)
Kotlin: 242.10180.25-IJ
Current Desktop: pop:GNOME

### Describe the bug

I opened the IDE, after an update if relevant. The error popped out while initial indexing

### Expected behavior

No bug reported by the IDE

### Additional context

Stacktrace:

```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
 at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
 at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:120)
 at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.set(PasswordSafeImpl.kt:106)
 at com.sourcegraph.cody.auth.AccountManagerBase.updateAccount(AccountManagerBase.kt:86)
 at com.sourcegraph.cody.config.CodyAuthenticationManager.updateAccountToken$Sourcegraph(CodyAuthenticationManager.kt:124)
 at com.sourcegraph.cody.config.SettingsMigration$refreshAccountsIds$1$1.invoke(SettingsMigration.kt:84)
 at com.sourcegraph.cody.config.SettingsMigration$refreshAccountsIds$1$1.invoke(SettingsMigration.kt:78)
 at com.sourcegraph.cody.config.SettingsMigration$loadUserDetails$2.invoke(SettingsMigration.kt:257)
 at com.sourcegraph.cody.config.SettingsMigration$loadUserDetails$2.invoke(SettingsMigration.kt:256)
 at com.intellij.collaboration.async.CompletableFutureUtil$successOnEdt$1.invoke(CompletableFutureUtil.kt:126)
 at com.intellij.collaboration.async.CompletableFutureUtil$successOnEdt$1.invoke(CompletableFutureUtil.kt:124)
 at com.intellij.collaboration.async.CompletableFutureUtil.handleOnEdt$lambda$8(CompletableFutureUtil.kt:114)
 at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
 at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
 at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
 at com.intellij.collaboration.async.CompletableFutureUtil$getEDTExecutor$1$1.invoke(CompletableFutureUtil.kt:198)
 at com.intellij.collaboration.async.CompletableFutureUtil$getEDTExecutor$1$1.invoke(CompletableFutureUtil.kt:198)
 at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:66)
 at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
 at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
 at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
 at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
 at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1152)
 at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
 at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
 at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:697)
 at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$13(IdeEventQueue.kt:591)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:591)
 at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:358)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:357)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:357)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:352)
 at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
 at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
 at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:352)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
 at java.desktop/java.awt.EventDispatchThread.run(Event...
```

**Comment by odisseus** [comment]
This seems to be a duplicate of #1549.

**Comment by lwasyl** [comment]
Admittedly I haven't searched for related issues, this was part of bulk report done by the IDE automatically — some reports go straight to Jetbrains, some just open a Github page with most details filled. It does look like a duplicate :+1:
