### ISSUE TITLE
bug: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by ceearrashee** [sourcegraph/jetbrains#1549]
### Cody Version

5.5.10

### IDE Information

GoLand 2024.2 EAP
Build #GO-242.10180.32, built on May 16, 2024
Licensed to GoLand EAP user: Yevhen Androsov
Expiration date: June 15, 2024
Runtime version: 21.0.3+13-b446.1 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 20
Registry:
  debugger.new.tool.window.layout=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
  ide.experimental.ui=true
  go.run.processes.with.pty=false
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.10180.28)
  com.intellij.datagen (242.10180.28)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.2.0)
  MultiHighlight (3.1.0)
  com.jetbrains.space (242.10180.28)
  Rider UI Theme Pack (0.14.11)
  org.intellij.plugins.postcss (242.10180.32)
  org.turbanov.run.configuration.as.action (3.0)
  org.OverEngineer.InlineProblems (0.5.3)
  org.jetbrains.plugins.sass (242.10180.32)
  com.intellij.properties (242.10180.28)
  String Manipulation (9.13.0)
  com.intellij.plugins.github.colorscheme (242.10180.25)
  hunspell (242.10180.32)
  xyz.danizz.commit-message-wrapper-fixer (1.2)
  com.github.camork.fileExpander (2.5)
  com.wakatime.intellij.plugin (14.3.14)
  XPathView (242.10180.28)
  com.intellij.tasks (242.10180.32)
  com.intellij.tasks.timeTracking (242.10180.32)
  com.intellij.plugin.adernov.powershell (2.6.1)
  com.intellij.aqua (242.10180.32)
  com.intellij.mermaid (0.0.22+IJ.232)
  com.intellij.kubernetes (242.10180.28)
  com.intellij.laf.macos (242.10180.28)
  [com.intellij.grazie.pro](http://com.intellij.grazie.pro) (0.3.306)
  com.intellij.ml.llm (242.10180.28)
  Dart (242.10180.28)
  io.wisetime.plugins.window.branch (2.0.0)
  com.intellij.queryComplexity (242.10180.28)
  app.codepreview.plugin (1.2.1)
  com.dmarcotte.handlebars (242.10180.28)
  tslint (242.10180.25)
  com.intellij.tide (242.10180.31)
  com.sourcegraph.jetbrains (5.5.10)
  com.mallowigi (96.0.0)
  mobi.hsz.idea.gitignore (4.5.3)
  com.github.linwancen.drawgraph (1.14.2024.05.08_23.05)
  com.github.dinbtechit.vscodetheme (1.10.10)
  com.ypwang.plugin.go-linter (1.6.6)
  cn.yiiguxing.plugin.translate (3.5.8)
  AngularJS (242.10180.25)
  dev.nx.console (1.24.0)

### Describe the bug

Startup Goland

### Expected behavior

No error

### Additional context

Stacktrace:

```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
 at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
 at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:120)
 at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.set(PasswordSafeImpl.kt:106)
 at com.sourcegraph.cody.auth.AccountManagerBase.updateAccount(AccountManagerBase.kt:86)
 at com.sourcegraph.cody.config.CodyAuthenticationManager.updateAccountToken$Sourcegraph(CodyAuthenticationManager.kt:124)
 at com.sourcegraph.cody.config.SettingsMigration$refreshAccountsIds$1$1.invoke(SettingsMigration.kt:84)
 at com.sourcegraph.cody.config.SettingsMigration$refreshAccountsIds$1$1.invoke(SettingsMigration.kt:78)
 at com.sourcegraph.cody.config.SettingsMigration$loadUserDetails$2.invoke(SettingsMigration.kt:257)
 at com.sourcegraph.cody.config.SettingsMigration$loadUserDetails$2.invoke(SettingsMigration.kt:256)
 at com.intellij.collaboration.async.CompletableFutureUtil$successOnEdt$1.invoke(CompletableFutureUtil.kt:126)
 at com.intellij.collaboration.async.CompletableFutureUtil$successOnEdt$1.invoke(CompletableFutureUtil.kt:124)
 at com.intellij.collaboration.async.CompletableFutureUtil.handleOnEdt$lambda$8(CompletableFutureUtil.kt:114)
 at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
 at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
 at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
 at com.intellij.collaboration.async.CompletableFutureUtil$getEDTExecutor$1$1.invoke(CompletableFutureUtil.kt:198)
 at com.intellij.collaboration.async.CompletableFutureUtil$getEDTExecutor$1$1.invoke(CompletableFutureUtil.kt:198)
 at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:66)
 at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
 at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
 at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
 at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
 at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1152)
 at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
 at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
 at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:697)
 at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$13(IdeEventQueue.kt:591)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:591)
 at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:358)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:357)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:357)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:352)
 at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
 at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
 at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:352)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
 at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.ja...
```

**Comment by odisseus** [comment]
This might be related to #247.
