### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'co (...)

### ISSUE THREAD

**Issue by beevester** [sourcegraph/jetbrains#1550]
Plugin version: `5.3.1544`
IDE version: `IU-241.14494.240`
Stacktrace:

```text
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.sourcegraph.cody.CodyActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.sourcegraph.jetbrains]
 at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
 at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
 at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
 at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
 at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
 
```

**Comment by dominiccooney** [comment]
This has been fixed and released, see [https://github.com/sourcegraph/jetbrains/issues/610](https://github.com/sourcegraph/jetbrains/issues/610)
