### ISSUE TITLE
Error when formatting a generated unit tests file

### ISSUE THREAD

**Issue by odisseus** [sourcegraph/jetbrains#1580]
### Cody Version

1af55f3858e67d30b24f54e00b2c4cd0be2754fd

### IDE Information

Idea CE 2022.1

### Describe the bug

Spotted while trying to reproduce [https://github.com/sourcegraph/jetbrains/issues/1521](https://github.com/sourcegraph/jetbrains/issues/1521) and [https://github.com/sourcegraph/jetbrains/issues/1543](https://github.com/sourcegraph/jetbrains/issues/1543).

### Expected behavior

No errors

### Additional context

```
java.lang.IndexOutOfBoundsException: chars sequence.length:19, start:784, end:1174
	at com.intellij.util.text.CharSequenceSubSequence.<init>(CharSequenceSubSequence.java:20)
	at com.intellij.util.text.ImmutableText.subSequence(ImmutableText.java:199)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$getText$1(DocumentImpl.java:950)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.openapi.editor.impl.DocumentImpl.getText(DocumentImpl.java:950)
	at com.sourcegraph.cody.edit.sessions.FixupSession$performInlineEdits$1.invoke$lambda$3(FixupSession.kt:370)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:362)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:362)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:350)
	at com.sourcegraph.cody.edit.sessions.FixupSession$performInlineEdits$1.invoke(FixupSession.kt:338)
	at com.sourcegraph.cody.edit.sessions.FixupSession$performInlineEdits$1.invoke(FixupSession.kt:333)
	at com.sourcegraph.cody.edit.widget.LensWidgetGroup.withListenersMuted(LensWidgetGroup.kt:126)
	at com.sourcegraph.cody.edit.sessions.FixupSession.performInlineEdits(FixupSession.kt:333)
	at com.sourcegraph.cody.edit.sessions.FixupSession.performWorkspaceEdit(FixupSession.kt:300)
```

**Comment by odisseus** [comment]
Since we have disabled the internal formatting of inline edits in #1632, this issue is irrelevant now.
