### ISSUE TITLE
bug: com.intellij.platform.instanceContainer.internal.ContainerDisposedException: Container 'ProjectImpl@1765230210 services' was ...

### ISSUE THREAD

**Issue by kalanchan** [sourcegraph/jetbrains#1593]
### Cody Version

6.0-localbuild

### IDE Information

WebStorm 2023.3.3
Build #WS-233.14015.89, built on January 23, 2024
Licensed to Sourcegraph / Kalan Chan
You have a perpetual fallback license for this version.
Subscription is active until February 11, 2025.
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.sourcegraph.jetbrains (6.0-localbuild)

### Describe the bug

could be precursor to document being disabled

### Expected behavior

document should work

### Additional context

Stacktrace:

```text
com.intellij.platform.instanceContainer.internal.ContainerDisposedException: Container 'ProjectImpl@1765230210 services' was disposed
 at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.state(InstanceContainerImpl.kt:59)
 at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.state(InstanceContainerImpl.kt:38)
 at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.getInstanceHolder(InstanceContainerImpl.kt:264)
 at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:1024)
 at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:988)
 at com.sourcegraph.cody.history.HistoryService$Companion.getInstance(HistoryService.kt:157)
 at com.sourcegraph.cody.chat.ui.LlmDropdown.setSelectedItem(LlmDropdown.kt:94)
 at com.sourcegraph.cody.chat.ui.LlmDropdown$updateModelsInUI$3.invoke$lambda$3(LlmDropdown.kt:69)
 at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
 at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
 at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
 at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
 at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
 at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
 at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
 at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
 at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
 at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
 at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
 at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
 at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
 at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
 at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
 at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
 at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
 at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.intellij.platform.instanceContainer.internal.DisposalTrace
 at com.intellij.platform.instanceContainer.internal.InstanceContainerImpl.dispose(InstanceContainerImpl.kt:253)
 at com.intellij.serviceContainer.ComponentManagerImpl.dispose(ComponentManagerImpl.kt:1696)
 at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.kt:316)
 at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
 at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
 at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
 at com.intellij.openapi.util.Disposer.dispose(Disposer.java:238)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject$lambda$15(ProjectManagerImpl.kt:406)
 at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:975)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.kt:388)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject$default(ProjectManagerImpl.kt:318)
 at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.kt:418)
 at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.closeProjectAndShowWelcomeFrameIfNoProjectOpened(CloseProjectWindowHelper.kt:57)
 at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing(CloseProjectWindowHelper.kt:44)
 at com.intellij.openapi.wm.impl.ProjectFrameHelper.windowClosing(ProjectFrameHelper.kt:434)
 at com.intellij.openapi.wm.impl.WindowCloseListener.windowClosing(ProjectFrameHelper.kt:454)
 at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
 at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
 at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
 at java.desktop/java.awt.AWTEventMulticaster.windowClosing(...
```

**Comment by mkondratek** [comment]
I am afraid the error is not about the disabled document. It's a project already disposed problem (probably the project has been closed while cody initialises) - fix to the error: https://github.com/sourcegraph/jetbrains/pull/1594

**Comment by kalanchan** [comment]
logs: [idea.log](https://github.com/sourcegraph/jetbrains/files/15405603/idea.log)

**Comment by kalanchan** [comment]
@mkondratek is this issue related to https://github.com/sourcegraph/cody-issues/issues/314? When we testing it live, the project disposed problem seems to disable commands

**Comment by mkondratek** [comment]
> @mkondratek is this issue related to [sourcegraph/cody-issues#314](https://github.com/sourcegraph/cody-issues/issues/314)? When we testing it live, the project disposed problem seems to disable commands

IMHO the project-disposed problems are unrelated to the issues with disabled command.

Please note that the project disposed error APPEAR to the users after reopening the project BUT they OCCUR on closing it (IntelliJ "remembers" the error that happened in previous session).
