### ISSUE TITLE
JetBrains: Crash occurred while running "Document Code" command for excluded repo.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1600]
### Cody Version

v5.5.12-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  de.sgalinski.typoscript.enterprise.plugin.id (2.8.0)
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (5.5.12-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user
3. Apply following policy from Site Admin > Configuration
```
"cody.contextFilters": {
    "exclude": [
        {
            "repoNamePattern": "^github\\.com\\/sourcegraph\\/cody"
        }
    ],
    "include": [
        {
            "repoNamePattern": "^github\\.com\\/sourcegraph\\/.+"
        }
    ]
}
```

4. Relaunch the IDE and navigate to [http://github.com/sourcegraph/cody](https://github.com/sourcegraph/cody) repo
5. Verify that "Explain Code" button is still showing disabled
6. Open any source code file and right click to open context menu
7. Choose "Cody > Document Code"

### Observed behavior:
Crash occurred with following stacktrace,
Stacktrace:
```text
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[pool-4-thread-1,5,main] 828847023 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1508296963
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.throwThreadAccessException(ThreadingAssertions.java:143)
	at com.intellij.util.concurrency.ThreadingAssertions.assertEventDispatchThread(ThreadingAssertions.java:65)
	at com.intellij.openapi.editor.impl.EditorImpl.assertIsDispatchThread(EditorImpl.java:3488)
	at com.intellij.openapi.editor.impl.InlayImpl.dispose(InlayImpl.java:90)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:238)
	at com.sourcegraph.cody.edit.sessions.FixupSession.showLensGroup(FixupSession.kt:191)
	at com.sourcegraph.cody.edit.sessions.FixupSession.showErrorGroup(FixupSession.kt:231)
	at com.sourcegraph.cody.edit.sessions.FixupSession.access$showErrorGroup(FixupSession.kt:53)
	at com.sourcegraph.cody.edit.sessions.FixupSession$triggerFixupAsync$1$1.invoke(FixupSession.kt:126)
	at com.sourcegraph.cody.edit.sessions.FixupSession$triggerFixupAsync$1$1.invoke(FixupSession.kt:124)
	at com.sourcegraph.cody.edit.sessions.FixupSession$sam$java_util_function_BiFunction$0.apply(FixupSession.kt)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Expected behavior

Crash should not occur.

### Additional context

**Video link:**

https://drive.google.com/file/d/1_GqM4Rjz0DDJ-y_5HhIariQoh7AbW_YA/view?usp=drive_link

**Comment by dominiccooney** [comment]
I can't reproduce the exception, but I *can* reproduce a bug: You can activate the document command without getting feedback that the command is disabled; you can start an edit (which will spin endlessly.)

**Comment by dominiccooney** [comment]
I can not reproduce this issue, or the problem I was seeing, with tip of trunk 12167331689275ba0ef0ad0074ac8ea7fa6e7552

When I race startup and do context menu commands before the extension has started, I get the "Cody is starting" banner. When I race startup and use the sidebar buttons to do it, chat does not respond but it does not get wedged, either and you can continue chatting.
