### ISSUE TITLE
JetBrains: Crash occurred while running "Document Code" command second time after undo action.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1620]
### Cody Version

v5.5.13-nightly

### IDE Information

IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.jetbrains.plugins.hocon (2023.1.0)
  PythonCore (233.14475.9)
  com.soywiz.korge.korge-intellij-plugin (4.0.4)
  com.sourcegraph.jetbrains (5.5.13-nightly)
Kotlin: 233.14475.28-IJ

### Describe the bug

Platform: Windows

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Enterprise user(S2 - mimics enterprise instance and Cody Ignore disabled)
3. Open any source code and select code snippet
4. Go to commands and run "Document Code" command
5. Click on "Undo" button from lenses
6. Verify that crash occurred and clear it
7. Remove the documentation added from above action
8. Go to commands and run "Document Code" command

### Observed behavior:
Crash occurred with following stacktrace,
Stacktrace:
```text
java.lang.Throwable: Can't remove document listener (FixupSessionDocumentListener@62d9817f). Registered listeners: [com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1@13fb5d4c, 346, 38, Multicaster, 187, 52, 45, 3, 66, 50, 38, 113, 359, 0, 25, 0, 0, [], com.intellij.openapi.editor.impl.view.LogicalPositionCache@1515a055, com.intellij.openapi.editor.impl.view.TextLayoutCache@7335ec6c, com.intellij.openapi.editor.ex.util.LexerEditorHighlighter(com.intellij.lexer.JavaHighlightingLexer): 'public class hello {
    public class BubbleSort {
        public static void bubbleSort(int[] arr) {
            int n = arr.length;
            boolean swapped;

            for (int i = 0; i < n - 1; i++) {
                swapped = false;


/**
 * This is a placeholder for documentation of the selected code.
 * The selected code is empty, so there is nothing to document.
 */
                for (int j = 0; j < n - 1 - i; j++) {
                    if (arr[j] > arr[j + 1]) {
                        // Swap arr[j] and arr[j + 1]
                        int temp = arr[j];
                        arr[j] = arr[j + 1];
                        arr[j + 1] = temp;
                        swapped = true;
                    }
                }

                // If no two elements were swapped by inner loop, then break
                if (!swapped) break;
            }
        }

        public static void main(String[] args) {
            int[] arr = {64, 34, 25, 12, 22, 11, 90};
            System.out.println("Unsorted array:");
        }
    }
}', 
use soft wraps: false, tab width: 4, additional columns: false, update in progress: false, bulk update in progress: false, dirty: true, deferred regions: []
appliance manager state: recalculation in progress: false; event being processed: null, available width: 662, visible width: 0, dirty: true
soft wraps mapping info: Soft wraps affected by current update: []
soft wraps: [], com.intellij.openapi.editor.impl.view.EditorSizeManager@65b2933a, com.intellij.openapi.editor.impl.CaretModelImpl@8553935, com.intellij.openapi.editor.impl.InlayModelImpl@7df2ed8b, com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter@5c1f0d35, Multicaster, com.intellij.openapi.editor.impl.event.EditorEventMulticasterImpl$1@2096ef22, com.intellij.openapi.editor.impl.ScrollingModelImpl$1@eea5036, EditorMarkupModel for EditorImpl[file://C:/Users/Jay Gohil/IdeaProjects/jaysVSDemo/hello.java], com.intellij.codeInsight.inline.completion.listeners.InlineCompletionDocumentListener@47327d9a, com.intellij.ae.database.counters.community.CodingTimeUserActivityEditorFactoryListener$editorCreated$1@6360b6ec, com.intellij.openapi.fileEditor.impl.text.TextEditorComponent$MyDocumentListener@7498ba5d, com.intellij.openapi.actionSystem.impl.FloatingToolbar$DocumentChangeListener@28af2f18, com.intellij.codeInsight.codeVision.CodeVisionHost$subscribeForFrontendEditor$3@7c25493a, com.intellij.openapi.vcs.ex.DocumentTracker$MyDocumentListener@1a145784, com.intellij.openapi.vcs.ex.ChangelistsLocalLineStatusTracker$MyUndoDocumentListener@2b6f4cc9]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.openapi.editor.impl.DocumentImpl.removeDocumentListener(DocumentImpl.java:995)
	at com.sourcegraph.cody.edit.sessions.FixupSession.dispose(FixupSession.kt:402)
	at com.sourcegraph.cody.edit.sessions.FixupSession.update(FixupSession.kt:175)
	at com.sourcegraph.cody.agent.CodyAgentService$2.invoke$lambda$2(CodyAgentService.kt:72)
	at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$1(CodyAgentClient.java:143)
	at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$0(CodyAgentClient.java:126)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.j...
```

### Expected behavior

Crash should not occur.

### Additional context

**Video link:**

https://drive.google.com/file/d/12Ct5aeTcUaZb8YX6AH1PSsjGnu2FVVmL/view?usp=drive_link

**Comment by mkondratek** [comment]
To be fixed by https://github.com/sourcegraph/jetbrains/pull/1621
