### ISSUE TITLE
bug: java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/ActionUpdateThread

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/jetbrains#1681]
### Cody Version

trunk 12167331689275ba0ef0ad0074ac8ea7fa6e7552

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 12, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 12
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

Start IDE and click on Cody status bar icon "early"

### Expected behavior

Don't throw exceptions

### Additional context

Stacktrace:

```text
java.lang.NoClassDefFoundError: com/intellij/openapi/actionSystem/ActionUpdateThread
 at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
 at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
 at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
 at java.base/java.lang.Class.getMethod0(Class.java:3293)
 at java.base/java.lang.Class.getMethod(Class.java:2106)
 at com.intellij.util.ReflectionUtil.getMethod(ReflectionUtil.java:250)
 at com.intellij.util.ReflectionUtil.getMethodDeclaringClass(ReflectionUtil.java:313)
 at com.intellij.openapi.actionSystem.ActionGroup.isDumbAware(ActionGroup.java:214)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:121)
 at com.intellij.openapi.actionSystem.impl.ActionUpdater.doUpdate(ActionUpdater.java:639)
 at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$updateActionReal$4(ActionUpdater.java:125)
 at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$6(ActionUpdater.java:209)
 at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
 at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
 at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
 at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
 at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
 at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
 at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
 at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
 at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$computeOnEdt$7(ActionUpdater.java:207)
 at com.intellij.openapi.actionSystem.impl.ActionUpdateEdtExecutor.lambda$computeOnEdt$0(ActionUpdateEdtExecutor.java:45)
 at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroupFastTrack$5(Utils.java:272)
 at com.intellij.openapi.actionSystem.impl.Utils.runLoopAndWaitForFuture(Utils.java:603)
 at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupFastTrack(Utils.java:270)
 at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.java:182)
 at com.intellij.openapi.actionSystem.impl.Utils.lambda$expandActionGroup$0(Utils.java:157)
 at com.intellij.openapi.actionSystem.impl.Utils.computeWithRetries(Utils.java:641)
 at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:156)
 at com.intellij.ui.popup.ActionStepBuilder.appendActionsFromGroup(ActionStepBuilder.java:102)
 at com.intellij.ui.popup.ActionStepBuilder.buildGroup(ActionStepBuilder.java:75)
 at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:125)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:259)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.(PopupFactoryImpl.java:215)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.(PopupFactoryImpl.java:182)
 at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:336)
 at com.jetbrains.rdserver.ui.popup.BackendBePopupFactory.createActionGroupPopup(BackendBePopupFactory.kt:87)
 at com.intellij.openapi.ui.popup.JBPopupFactory.createActionGroupPopup(JBPopupFactory.java:264)
 at com.jetbrains.rdserver.ui.popup.BackendBePopupFactory.createActionGroupPopup(BackendBePopupFactory.kt:134)
 at com.sourcegraph.cody.statusbar.CodyStatusBarWidget.createPopup(CodyStatusBarWidget.kt:33)
 at com.intellij.openapi.wm.impl.status.EditorBasedStatusBarPopup.showPopup(EditorBasedStatusBarPopup.java:186)
 at com.intellij.openapi.wm.impl.status.EditorBasedStatusBarPopup$1.onClick(EditorBasedStatusBarPopup.java:73)
 at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
 at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
 at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
 at java.desktop/java.awt.Component.processEvent(Component.java:6419)
 at java.desktop/java.awt.Container.processEvent(Container.java:2263)
 at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
 at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
 at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
 at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
 at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
 at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
 at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
 at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
 at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
 at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
 at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
 at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
 at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEv...
```

**Comment by dominiccooney** [comment]
This looks like an IntelliJ issue given the depth of IDEA code on the stack after our popup creation. And Cody no longer supports this version of IntelliJ, so WontFixing this one.
