### ISSUE TITLE
bug: exception while running tests

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#1690]
### Cody Version

5.5.12-nightly but it's actually the latest pre-GA / main

### IDE Information

IntelliJ IDEA 2022.1 (Community Edition)
Build #IC-221.5080.210, built on April 11, 2022
Runtime version: 11.0.14.1+1-b2043.25 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 752M
Cores: 10
Non-Bundled Plugins:
    com.sourcegraph.jetbrains (6.0-localbuild)

Kotlin: 221-1.6.20-release-285-IJ5080.210

### Describe the bug

`> Task :test
ERROR: Already disposed: MessageBus(owner=Project(name= formatting into fewer lines, containerState=disposed temporarily, componentStore=/private/var/folders/6k/hrbcgs512_z_6v5cgln5sx1h0000gq/T/unitTest_notifies_observer_2h9KCs8Vymc64DnrMfAqMdYFGKH/light_temp_2h9KCrQnjwOKHQNfIt3j38aflqm.ipr) (disposed), disposeState= 0)
java.lang.Throwable: Already disposed: MessageBus(owner=Project(name= formatting into fewer lines, containerState=disposed temporarily, componentStore=/private/var/folders/6k/hrbcgs512_z_6v5cgln5sx1h0000gq/T/unitTest_notifies_observer_2h9KCs8Vymc64DnrMfAqMdYFGKH/light_temp_2h9KCrQnjwOKHQNfIt3j38aflqm.ipr) (disposed), disposeState= 0)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.intellij.util.messages.impl.MessageBusImpl.checkNotDisposed(MessageBusImpl.java:334)
	at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:34)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:164)
	at com.sun.proxy.$Proxy62.afterAction(Unknown Source)
	at com.sourcegraph.cody.config.CodyAuthenticationManager.setActiveAccount$lambda$8(CodyAuthenticationManager.kt:142)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invokeSuspend(CodyAgentService.kt:259)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.coWithAgent(CodyAgentService.kt:316)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.access$coWithAgent(CodyAgentService.kt:226)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1.invokeSuspend(CodyAgentService.kt:265)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:256)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)`

### Expected behavior

CodyAuthenticationManager should detect errors here and recover more gracefully.

### Additional context

Did not reproduce -- but we need more error handling at that exact spot in `CodyAuthenticationManager`.

**Comment by steveyegge** [comment]
I think it probably happened during testing; that's the only place the message "formatting into fewer lines" appears. Somehow IntelliJ decided to run the tests before launching the IDE that time, and they happened to fail. Closing.
