### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with messa...

### ISSUE THREAD

**Issue by alderhan** [sourcegraph/jetbrains#1699]
### Cody Version

5.5.10

### IDE Information

PhpStorm 2024.1.2
Build #PS-241.17011.119, built on May 28, 2024
Licensed to auzuret Clément
You have a perpetual fallback license for this version.
Subscription is active until April 30, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2024M
Cores: 8
Registry:
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.toml.lang (241.17011.8)
  com.jetbrains.space (241.17011.48)
  com.intellij.ideolog (222.3.2.0)
  color.scheme.Visual Studio Dark (1.0.0)
  com.samdark.intellij-visual-studio-code-dark-plus (2.8)
  ru.adelf.idea.dotenv (2024.1)
  NEON support (0.5.4)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (10.0.0)
  com.sourcegraph.jetbrains (5.5.10)

### Describe the bug

I can't select chat model
![image](https://github.com/sourcegraph/jetbrains/assets/130375094/e975c6d8-52d0-42b4-a1e7-b33764f1c4e0)

and i have an error on phpstorm when start a discuss

````
Cody encountered an error when processing your message: 
⚠ org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config
If the problem persists, please create a support ticket.
````

### Expected behavior

I can discuss with AI

### Additional context

Stacktrace:
```text
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.chat.AgentChatSession.submitMessageToAgent$lambda$1(AgentChatSession.kt:109)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invokeSuspend(CodyAgentService.kt:185)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1$task$1.invoke(CodyAgentService.kt)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.coWithAgent(CodyAgentService.kt:241)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$withAgent$2$1.invokeSuspend(CodyAgentService.kt:190)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:182)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

```
Additional info: ```org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request chat/new failed with message: No chat model found in server-provided config```

**Comment by alderhan** [comment]
Resolve by use case https://github.com/sourcegraph/jetbrains/issues/1498#issuecomment-2115717931

**Comment by odisseus** [comment]
Duplicate of #1498.
