### ISSUE TITLE
Autocomplete not working and the agent fails to start.

### ISSUE THREAD

**Issue by ericbsd** [sourcegraph/jetbrains#1769]
### IDE Information

PyCharm 2024.1.1 (Community Edition)
Build #PC-241.15989.155, built on April 29, 2024
Runtime version: 17.0.11+9-1 amd64
VM: OpenJDK 64-Bit Server VM by OpenJDK BSD Porting Team
FreeBSD 14.0-stable
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  eu.osimowicz.plugins.intellij.CodeBlocksSorter (0.1.2)
  com.jetbrains.space (241.15989.9)
  com.sourcegraph.jetbrains (6.0.3)
  name.kropp.intellij.makefile (241.14494.150)
Current Desktop: MATE

### Bug Description

Due to that issue, I have been unable to use Cody for over two months. It is a duplicate of what I reported before.

### Additional context

Stacktrace:

```text
java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
 at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
 at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
 at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4(CodyAgentService.kt:181)
 at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
 at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
 
```

**Comment by mkondratek** [comment]
Hello @ericbsd 👋 we are sorry you experience this problem and it lasts so long 🙇 

Could you please share more details? What do you usually do to get this error?

**Comment by ericbsd** [comment]
I get this error when I open PyCharm.

**Comment by mkondratek** [comment]
@ericbsd, I tested the plugin on Windows and macOs and it works. I am trying to setup the project and play with it on my Ubuntu machine. Research in progress 🕵️ 

In the meantime, I kindly ask you to do the following tests:

### Share the logs from the crash
1. Close IDE
2. Open IDE and a project
3. Ensure that the error appears
4. Go to `Help > Show Log in Files` (`Show Log in <smth>`, idk what the precise name in FreeBSD)
5. Copy the file and paste it here

### Increase your memory settings 
In your setup it is 2048. 
1. Go to `Help > Change Memory Settings`
2. Set it to `4096`.
3. Restart IDE.
4. Verify if the problem persists.

can you please try them? 🙏

**Comment by ericbsd** [comment]
Here is the idea log.
[idea.log](https://github.com/user-attachments/files/15803277/idea.log)

**Comment by ericbsd** [comment]
The error persist after changing the memory from 2048 to 4096 and restarting Pycharm.

**Comment by ericbsd** [comment]
I just noticed that the IDE Internal Errors are only sent on a log.

Log 1
```
java.lang.Throwable: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4$lambda$1(CodyAgentService.kt:178)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1008)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2364)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4(CodyAgentService.kt:176)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
Log 2
```
Failed to start Cody agent

java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4(CodyAgentService.kt:181)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
```
Log 3
```
java.lang.Throwable: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4$lambda$1(CodyAgentService.kt:178)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1008)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2364)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4(CodyAgentService.kt:176)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```
Log 4
```
Failed to start Cody agent

java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4(CodyAgentService.kt:181)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
```

**Comment by vroudge** [comment]
I would add that I am also unable to use Cody at all with the same issue as the poster above, although I'm running WSL2.

**Comment by mkondratek** [comment]
hey @ericbsd, a new version is out. Can you please check **6.0.12**? Can you still see the problem?

**Comment by ericbsd** [comment]
Yes

**Comment by ericbsd** [comment]
The last version that autocompletes stopped working for me was `5.5.5-nightly`, but Pycharm did not report an error after that, and autocomplete has not worked since. The error above started to show in `5.5.9-nightly`.

On a new install of GhostBSD and PyCharm, autocomplete was not working on `5.5.4-nightly`. I don't know why, but on my main system, it is working.

On `5.5.5-nightly`, the chat was working, and it stopped working on `5.5.9-nightly`.

I took time to dig in when it stopped working, and I hope it helps.

**Comment by ericbsd** [comment]
I tried `6.0.14-nightly`, and Cody failed to start like all the other versions after 5.5.9-nightly.

**Comment by mkondratek** [comment]
Hi @ericbsd 👋 feel free to try the new plugin version: [6.0.25](https://plugins.jetbrains.com/plugin/9682-cody-ai-coding-assistant-with-autocomplete--chat/versions/stable/584093?noRedirect=true). I hope it resolves your problems 🤞

**Comment by ericbsd** [comment]
I will have a try.

**Comment by ericbsd** [comment]
Looks like the same issue is still happening.
```
java.lang.Throwable: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$6$lambda$1(CodyAgentService.kt:168)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1008)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2364)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$6(CodyAgentService.kt:166)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

```
Failed to start Cody

java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$6(CodyAgentService.kt:172)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
```

```
java.lang.Throwable: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$6$lambda$1(CodyAgentService.kt:168)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1008)
	at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2364)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$6(CodyAgentService.kt:166)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

```
Failed to start Cody

java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$6(CodyAgentService.kt:172)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.JsonRpcException: java.io.IOException: Stream closed
```

**Comment by ericbsd** [comment]
I just installed the latest 7.0.8-nightly, and everything is working. I have not tried stable, but I will stay one night to report any problem faster. Also, I noticed all the lovely changes. It is way better than 5.5.4, which I have used since the issue.

I am closing this since it is fixed.

**Comment by mkondratek** [comment]
I'm so glad I read this 🚀 It was quite a journey 😌
