### ISSUE TITLE
An error when trying to use the context selector in IDE

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#181]
```
java.lang.NoClassDefFoundError: org/commonmark/ext/gfm/tables/TablesExtension
    at com.sourcegraph.cody.chat.MessagePanel.<clinit>(MessagePanel.kt:83)
    at com.sourcegraph.cody.CodyToolWindowContent.addMessageToChat$lambda$11(CodyToolWindowContent.kt:279)
    at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
    at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
    at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
    at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
    at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
    at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:667)
    at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:571)
    at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1444)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:571)
    at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
    at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
    at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
    at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
    at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
    at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
    at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
    at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: org.commonmark.ext.gfm.tables.TablesExtension PluginClassLoader(plugin=PluginDescriptor(name=Sourcegraph Cody + Code Search, id=com.sourcegraph.jetbrains, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IdeaIC2023.1/plugins/instrumented-Sourcegraph-5.2.9816.jar, version=5.2.9816, package=null, isBundled=false), packagePrefix=null, instanceId=53, state=active)
    at [com.intellij.ide.plugins.cl](http://com.intellij.ide.plugins.cl/).PluginClassLoader.loadClass(PluginClassLoader.kt:150)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 39 more
```

> I have a customer who is getting the below error(shared in thread) when trying to use the context selector in their IDE.

Reported by @superhsu.

**Comment by mkondratek** [comment]
> path=~/Library/Application Support/JetBrains/IdeaIC2023.1/plugins/instrumented-Sourcegraph-5.2.9816.jar

Based no that line above, they are running 5.2.9816 (latest version). I just downloaded the jar and was able to find the TablesExtension.create() method that's causing the problem

```
❯ javap -cp /Users/olafurpg/Downloads/Sourcegraph-11/lib/commonmark-ext-gfm-tables-0.21.0.jar org.commonmark.ext.gfm.tables.TablesExtension
Compiled from "TablesExtension.java"
public class org.commonmark.ext.gfm.tables.TablesExtension implements org.commonmark.parser.Parser$ParserExtension,org.commonmark.renderer.html.HtmlRenderer$HtmlRendererExtension,org.commonmark.renderer.text.TextContentRenderer$TextContentRendererExtension {
  public static org.commonmark.Extension create();
...
```

~ @olafurpg
