### ISSUE TITLE
bug: making request: AWS Bedrock: unexpected status code 400: {"message":"Malformed input request: #: required key [prompt] not fo...

### ISSUE THREAD

**Issue by lauramoorealc** [sourcegraph/jetbrains#1825]
### IDE Information

IntelliJ

### Bug Description

Stopped accepting XML input for summarizing.   This had worked previously but then stopped working when I tried to clear the chat / start a new chat because Cody could not process large amounts of data.

024-06-26 16:43:20,130 [102288578]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:43:43,603 [102312051]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:44:20,141 [102348589]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:44:21,838 [102350286]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:45:06,638 [102395086]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2024-06-26 16:45:20,141 [102408589]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:45:21,850 [102410298]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:46:20,173 [102468621]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:46:21,869 [102470317]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:47:20,190 [102528638]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:47:21,887 [102530335]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:47:26,638 [102535086]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ UpstreamHealth: Ping took 80ms  
2024-06-26 16:48:01,643 [102570091]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:48:20,209 [102588657]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:48:38,143 [102606591]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.characters/flush 
2024-06-26 16:48:51,907 [102620355]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:49:03,466 [102631914]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ UpstreamHealth: Ping took 85ms  
2024-06-26 16:49:13,251 [102641699]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:49:50,230 [102678678]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:49:51,932 [102680380]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:50:50,259 [102738707]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:50:51,959 [102740407]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:51:46,286 [102794734]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2024-06-26 16:51:50,265 [102798713]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:51:51,980 [102800428]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:52:34,571 [102843019]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:52:50,280 [102858728]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:53:21,982 [102890430]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:53:50,309 [102918757]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}
2024-06-26 16:54:16,899 [102945347]   WARN - #com.sourcegraph.cody.agent.CodyAgent - {"stack":"Error: Timeout\n    at Timeout._onTimeout (C:\\Users\\c14103\\AppData\\Roaming\\JetBrains\\IntelliJIdea2023.3\\plugins\\Sourcegraph\\agent\\index.js:271505:20)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)","message":"Timeout","name":"Error"}

### Additional context

Stacktrace: ```making request: AWS Bedrock: unexpected status code 400: {"message":"Malformed input request: #: required key [prompt] not found#: required key [max_tokens_to_sample] not found#: extraneous key [system] is not permitted#: extraneous key [max_tokens] is not permitted, please reformat your input and try again."}```

**Comment by kalanchan** [comment]
should be fixed on version 7 and above, feel free to reopen if it is not
