### ISSUE TITLE
bug: java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.model.SideEffectGuard$SideEffectNotAllowedExceptio...

### ISSUE THREAD

**Issue by theanseur** [sourcegraph/jetbrains#1835]
### IDE Information

👍

### Bug Description

fix

### Additional context

Stacktrace:
```text
java.lang.Throwable: Control-flow exceptions (e.g. this class com.intellij.model.SideEffectGuard$SideEffectNotAllowedException) should never be logged. Instead, these should have been rethrown if caught.
	at com.intellij.openapi.diagnostic.Logger.ensureNotControlFlow(Logger.java:493)
	at com.intellij.idea.IdeaLogger.doLogError(IdeaLogger.java:154)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:145)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.intellij.openapi.editor.impl.DocumentImpl$DelayedExceptions.register(DocumentImpl.java:844)
	at com.intellij.openapi.editor.impl.DocumentImpl.lambda$changedUpdate$1(DocumentImpl.java:926)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:269)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:277)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:268)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:920)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:824)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:664)
	at com.intellij.openapi.editor.impl.DocumentImpl.replaceString(DocumentImpl.java:598)
	at com.intellij.psi.formatter.DocumentBasedFormattingModel.replaceWhiteSpace(DocumentBasedFormattingModel.java:146)
	at com.intellij.formatting.engine.FormatProcessorUtils.replaceWhiteSpace(FormatProcessorUtils.java:31)
	at com.intellij.formatting.engine.ApplyChangesState.doIteration(ApplyChangesState.java:162)
	at com.intellij.formatting.engine.State.iteration(State.java:28)
	at com.intellij.formatting.engine.StateProcessor.iteration(StateProcessor.java:29)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:94)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:682)
	at com.intellij.formatting.FormatterImpl.execute(FormatterImpl.java:261)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:229)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processText(CodeFormatterFacade.java:203)
	at com.intellij.formatting.service.CoreFormattingService.formatRanges(CoreFormattingService.java:72)
	at com.intellij.formatting.service.FormattingServiceUtil.formatRanges(FormattingServiceUtil.java:122)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:164)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:123)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformatText(CodeStyleManagerImpl.java:116)
	at com.intellij.codeInsight.template.impl.TemplateState.reformat(TemplateState.java:1231)
	at com.intellij.codeInsight.template.impl.TemplateState.lambda$doReformat$2(TemplateState.java:415)
	at com.intellij.codeInsight.template.impl.TemplateState.performWrite(TemplateState.java:426)
	at com.intellij.codeInsight.template.impl.TemplateState.doReformat(TemplateState.java:419)
	at com.intellij.codeInsight.template.impl.TemplateState.lambda$processAllExpressions$1(TemplateState.java:366)
	at com.intellij.codeInsight.template.impl.TemplateState.performWrite(TemplateState.java:426)
	at com.intellij.codeInsight.template.impl.TemplateState.processAllExpressions(TemplateState.java:399)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:339)
	at com.intellij.codeInsight.template.impl.TemplateState.start(TemplateState.java:301)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.lambda$startTemplate$1(TemplateManagerImpl.java:163)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:169)
	at com.intellij.codeInsight.template.impl.TemplateManagerImpl.startTemplate(TemplateManagerImpl.java:184)
	at com.goide.refactor.template.GoTemplate.lambda$startTemplate$25(GoTemplate.java:592)
	at com.goide.refactor.template.GoTemplate.startTemplate(GoTemplate.java:595)
	at com.goide.refactor.template.GoTemplate.startTemplate(GoTemplate.java:553)
	at com.goide.intentions.expressions.structLiteral.GoFillStructHandler.fill(GoFillStructHandler.java:56)
	at com.goide.intentions.expressions.structLiteral.GoFillFieldsIntentionBase.invoke(GoFillFieldsIntentionBase.java:80)
	at com.intellij.codeInsight.intention.BaseElementAtCaretIntentionAction.invoke(BaseElementAtCaretIntentionAction.java:58)
	at com.intellij.codeInsight.intention.IntentionAction.generatePreview(IntentionAction.java:116)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.generatePreview(IntentionActionWrapper.java:87)
	at com.intellij.codeInsight.intention.impl.IntentionActionWithTextCaching$MyIntentionAction.generatePreview(IntentionActionWithTextCaching.java:262)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable$invokePreview$1$1$1.invoke(IntentionPreviewComputable.kt:132)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable$invokePreview$1$1$1.invoke(IntentionPreviewComputable.kt:131)
	at com.intellij.model.SideEffectGuard$Companion.computeWithAllowedSideEffectsBlocking(SideEffectGuard.kt:42)
	at com.intellij.model.SideEffectGuard$Companion.computeWithoutSideEffects(SideEffectGuard.kt:27)
	at com.intellij.codeInsight.intention.impl.preview.IntentionPreviewComputable.invokePreview$lambda$2$lambda$1(IntentionPreviewComputable.kt:131)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.lambda$postponeFormattingInside$2(PostprocessReformattingAspectImpl.java:137)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectImpl.java:146)
	at com.intellij.psi.impl.source.PostprocessReformattingAspectImpl.postponeFormattingInside(PostprocessReformattingAspectI...
```

**Comment by theanseur** [comment]
bug

**Comment by theanseur** [comment]
👍
