### ISSUE TITLE
bug: java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.ecli...

### ISSUE THREAD

**Issue by phamnhathieudn** [sourcegraph/jetbrains#1880]
### IDE Information

WebStorm 2024.1.5
Build #WS-241.18034.50, built on June 19, 2024
Licensed to Nguyen Van Vuong
Subscription is active until April 25, 2025.
For educational use only.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 14096M
Cores: 12
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.codeium.intellij (1.8.76)
  com.github.copilot (1.5.13.5971)
  com.sourcegraph.jetbrains (6.0.12)

### Bug Description

Can not use cody extension with wsl code

### Additional context

Stacktrace:
```text
java.util.concurrent.ExecutionException: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at f2 (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35123:21)
    at e4.t4 (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35138:88)
    at new e4 (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35180:40)
    at t4.parse (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35152:25)
    at _Uri.parse (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:90310:48)
    at C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:119047:49
    at C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:118763:50
    at handleRequest (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96879:33)
    at handleMessage (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96746:11)
    at processMessageQueue (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96765:13)
    at Immediate.<anonymous> (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96741:11)
    at process.processImmediate (node:internal/timers:478:21)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$4(CodyAgentService.kt:192)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: com.sourcegraph.cody.agent.CodyAgentException: Creating agent unsuccessful: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at f2 (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35123:21)
    at e4.t4 (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35138:88)
    at new e4 (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35180:40)
    at t4.parse (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:35152:25)
    at _Uri.parse (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:90310:48)
    at C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:119047:49
    at C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:118763:50
    at handleRequest (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96879:33)
    at handleMessage (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96746:11)
    at processMessageQueue (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96765:13)
    at Immediate.<anonymous> (C:\Users\vuong.nguyen\AppData\Roaming\JetBrains\WebStorm2024.1\plugins\Sourcegraph\agent\index.js:96741:11)
    at process.processImmediate (node:internal/timers:478:21)

```

**Comment by mkondratek** [comment]
Hi @phamnhathieudn 👋 can you please update the plugin to [6.0.25](https://plugins.jetbrains.com/plugin/9682-cody-ai-coding-assistant-with-autocomplete--chat/versions/stable/584093?noRedirect=true)? 🙏 the issue with WSL should be resolved now 😌

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
