### ISSUE TITLE
JetBrains: Crash occurred while deleting a file which is being written by "Generate Unit Tests" command

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1900]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.14-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Open any source code file and right click to open context menu
4. Choose "Cody > Generate Unit Tests" and verify a test file is being written
5. Immediately delete the file

### Observed behavior:
Crash occurred with following stacktrace,
Stacktrace:
```text
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:44)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:1025)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.checkDisposed(LogicalPositionCache.java:191)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.getLineInfo(LogicalPositionCache.java:176)
	at com.intellij.openapi.editor.impl.view.LogicalPositionCache.logicalPositionToOffset(LogicalPositionCache.java:111)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.logicalPositionToOffset(EditorCoordinateMapper.java:95)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.logicalToVisualPosition(EditorCoordinateMapper.java:106)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.offsetToVisualPosition(EditorCoordinateMapper.java:234)
	at com.intellij.openapi.editor.impl.view.EditorView.offsetToVisualPosition(EditorView.java:200)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$offsetToVisualPosition$33(EditorImpl.java:1475)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.editor.impl.EditorImpl.offsetToVisualPosition(EditorImpl.java:1475)
	at com.intellij.openapi.editor.impl.EditorImpl.offsetToVisualPosition(EditorImpl.java:1470)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:92)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.lambda$create$0(VisualLineFragmentsIterator.java:31)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.xyToVisualPosition(EditorCoordinateMapper.java:333)
	at com.intellij.openapi.editor.impl.view.EditorView.xyToVisualPosition(EditorView.java:228)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$xyToVisualPosition$29(EditorImpl.java:1447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.editor.impl.EditorImpl.xyToVisualPosition(EditorImpl.java:1447)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$xyToLogicalPosition$37(EditorImpl.java:1519)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:909)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:65)
	at com.intellij.openapi.editor.impl.EditorImpl.xyToLogicalPosition(EditorImpl.java:1517)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.getVisibleRange(ProtocolTextDocument.kt:71)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.fromVirtualFile(ProtocolTextDocument.kt:181)
	at com.sourcegraph.cody.edit.sessions.FixupSession.updateEditorIfNeeded$Sourcegraph(FixupSession.kt:380)
	at com.sourcegraph.cody.agent.CodyAgentService$2.invoke$lambda$8(CodyAgentService.kt:102)
	at com.sourcegraph.cody.agent.CodyAgentClient.lambda$acceptOnEventThread$0(CodyAgentClient.java:128)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsFo...
```

### Expected behavior:
Crash should not occur.

### Additional context

**Video link:**

https://drive.google.com/file/d/1u7MBfsDF4WOwiaHv2pjpz6LSQREKmwgN/view?usp=drive_link

**Comment by kalanchan** [comment]
going to close this, if this is still an issue feel free to re-open
