### ISSUE TITLE
JetBrains: Crash occurred while deleting suggestion generated by autocomplete

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#1988]
### IDE Information

IntelliJ IDEA 2023.3.3 (Community Edition)
Build #IC-233.14015.106, built on January 25, 2024
Runtime version: 17.0.9+7-b1087.11 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  idea.plugin.protoeditor (233.13135.65)
  DevKit (233.14015.152)
  gherkin (233.11799.165)
  cucumber-java (233.11799.196)
  PythonCore (233.14015.106)
  com.sourcegraph.jetbrains (6.0.22-nightly)
Kotlin: 233.14015.106-IJ

### Bug Description

Platform: macOS

**Steps to reproduce:**

1. Have Cody plugin installed in your JB IntelliJ editor
2. Login to Cody with Free/Pro user
3. Type something in a source code file and trigger Autocompletion
4. Clear the auto completed code

### Expected behavior:
Crash should not occur.

### Observed behavior:
Crash occurred with following stacktrace.

Stacktrace:
```text
java.lang.IndexOutOfBoundsException: Wrong offset: 194. Should be in range: [0, 189]
	at com.intellij.openapi.editor.impl.LineSet.findLineIndex(LineSet.java:164)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineNumber(DocumentImpl.java:1001)
	at com.sourcegraph.cody.agent.intellij_extensions.DocumentKt.codyRange(Document.kt:16)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:53)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:406)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:76)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:34)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:401)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1075)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:184)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:187)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

### Additional context

**Video link:**

https://drive.google.com/file/d/1ftGcKAaJy-3HtnxFiEcISlDpI8KHruDj/view?usp=drive_link

**Comment by mkondratek** [comment]
closes https://github.com/sourcegraph/jetbrains/issues/2031, https://github.com/sourcegraph/jetbrains/issues/2032, https://github.com/sourcegraph/jetbrains/issues/2164, https://github.com/sourcegraph/jetbrains/issues/2163, https://github.com/sourcegraph/jetbrains/issues/2153, https://github.com/sourcegraph/jetbrains/issues/2130, https://github.com/sourcegraph/jetbrains/issues/2129, https://github.com/sourcegraph/jetbrains/issues/2112, https://github.com/sourcegraph/jetbrains/issues/2094, https://github.com/sourcegraph/jetbrains/issues/2093, https://github.com/sourcegraph/jetbrains/issues/2079, https://github.com/sourcegraph/jetbrains/issues/2062, https://github.com/sourcegraph/jetbrains/issues/2051, https://github.com/sourcegraph/jetbrains/issues/2248, https://github.com/sourcegraph/jetbrains/issues/2234, https://github.com/sourcegraph/jetbrains/issues/2232, https://github.com/sourcegraph/jetbrains/issues/2230, https://github.com/sourcegraph/jetbrains/issues/2229, https://github.com/sourcegraph/jetbrains/issues/2221, https://github.com/sourcegraph/jetbrains/issues/2220, https://github.com/sourcegraph/jetbrains/issues/2218, https://github.com/sourcegraph/jetbrains/issues/2217, https://github.com/sourcegraph/jetbrains/issues/2215, https://github.com/sourcegraph/jetbrains/issues/2211, https://github.com/sourcegraph/jetbrains/issues/2205, https://github.com/sourcegraph/jetbrains/issues/2184, https://github.com/sourcegraph/jetbrains/issues/2182, https://github.com/sourcegraph/jetbrains/issues/2181, https://github.com/sourcegraph/jetbrains/issues/2180, https://github.com/sourcegraph/jetbrains/issues/2179, https://github.com/sourcegraph/jetbrains/issues/2177, https://github.com/sourcegraph/jetbrains/issues/2168, https://github.com/sourcegraph/jetbrains/issues/2167, https://github.com/sourcegraph/jetbrains/issues/2166, https://github.com/sourcegraph/jetbrains/issues/2165
