### ISSUE TITLE
bug: java.lang.Throwable: ID 'cody.command.Explain' is already taken by action 'Explain Code (null)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction) . Action 'Explain Code (null)' (class com.sourcegraph.cody.commands.ui.CommandsContextMenu$Companion$addCommandsToCodyContextMenu$action$1) cannot use the same ID null

### ISSUE THREAD

**Issue by tamanna18** [sourcegraph/jetbrains#2070]
Plugin version: ```5.2.21709```
IDE version: ```PC-231.8109.197```
Exception: ```java.lang.Throwable: ID 'cody.command.Explain' is already taken by action 'Explain Code (null)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction) . Action 'Explain Code (null)' (class com.sourcegraph.cody.commands.ui.CommandsContextMenu$Companion$addCommandsToCodyContextMenu$action$1) cannot use the same ID null```
Stacktrace:
```text
java.lang.Throwable: ID 'cody.command.Explain' is already taken by action 'Explain Code (null)' (class com.intellij.openapi.actionSystem.impl.ChameleonAction) . Action 'Explain Code (null)' (class com.sourcegraph.cody.commands.ui.CommandsContextMenu$Companion$addCommandsToCodyContextMenu$action$1) cannot use the same ID null
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.reportActionIdCollision(ActionManagerImpl.java:1336)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1273)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.registerAction(ActionManagerImpl.java:1345)
	at com.sourcegraph.cody.commands.ui.CommandsContextMenu$Companion.addCommandsToCodyContextMenu(CommandsContextMenu.kt:50)
	at com.sourcegraph.cody.initialization.PostStartupActivity.runActivity(PostStartupActivity.kt:35)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:328)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$1.invoke(StartupManagerImpl.kt:269)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$4$2$1.invoke(StartupManagerImpl.kt:268)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda$0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:193)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:268)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:69)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by tamanna18** [comment]
.
