### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by attid** [sourcegraph/jetbrains#2071]
### IDE Information

PyCharm 2024.2 (Community Edition)
Build #PC-242.20224.347, built on August 9, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.5.0-44-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (223.240814.221)
  com.github.blarc.ai-commits-intellij-plugin (2.2.0)
  com.sourcegraph.jetbrains (6.0.26)
  ru.adelf.idea.dotenv (2024.2.1)
Current Desktop: MATE

### Bug Description

just on start

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///home/itolstov/Project/eurmtl.me/routers/remote.py

Error: codeActions/provide: document not found for file:///home/itolstov/Project/eurmtl.me/routers/remote.py
    at /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:138490:19
    at /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:139426:18
    at async /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:137987:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:133)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:179)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///home/itolstov/Project/eurmtl.me/routers/remote.py

Error: codeActions/provide: document not found for file:///home/itolstov/Project/eurmtl.me/routers/remote.py
    at /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:138490:19
    at /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:139426:18
    at async /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:137987:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:370)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///home/itolstov/Project/eurmtl.me/routers/remote.py

Error: codeActions/provide: document not found for file:///home/itolstov/Project/eurmtl.me/routers/remote.py
    at /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:138490:19
    at /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:139426:18
    at async /home/itolstov/.local/share/JetBrains/PyCharmCE2024.2/Sourcegraph/agent/index.js:137987:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation$lambda$5(CodyFixHighlightPass.kt:122)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:266)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.i...
```

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
