### ISSUE TITLE
NPE errors when opening .class files

### ISSUE THREAD

**Issue by felixfrost** [sourcegraph/jetbrains#2158]
### IDE Information

IntelliJ IDEA 2022.1.2 (Community Edition)
Build #IC-221.5787.30, built on May 31, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    com.tabnine.TabNine (1.120.0)
    com.intellij.ideolog (203.0.30.0)
    com.hiberbee.intellij.hiberbee-theme (2023.11.10.2029)
    com.github.kropp.intellij.theme.ubuntu (0.1)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    SQL Query Plugin (2.2)
    com.sourcegraph.jetbrains (6.0.25)
    CheckStyle-IDEA (5.76.0)
    com.haulmont.jpab (2022.4.7-221)
    com.weirddev.testme (5.1.0)

Kotlin: 221-1.6.21-release-337-IJ5787.30

### Bug Description

 When opening a .class file, multiple errors are triggered, each throwing a NullPointerException (NPE). This issue occurs consistently, causing several error dialogs to pop up simultaneously. The errors make it frustrating and disruptive to work with .class files, as the user has to close each error dialog manually if notification settings are set to show them.

### Steps to Reproduce

1. Open the application.
2. Navigate to and select any `.class` file.
3. Observe the multiple error dialogs that appear, each indicating a `NullPointerException` (NPE).

**Expected Behavior:**
- The `.class` file should open without any errors or exceptions.

**Actual Behavior:**
- Multiple NPE error dialogs are triggered, requiring manual dismissal.

### Additional context

Stacktrace:
```text
java.lang.NullPointerException
	at com.sourcegraph.cody.inspections.CodyFixHighlightPassFactory.factory$lambda$0(CodyFixHighlightPass.kt:156)
	at com.intellij.codeInsight.daemon.impl.TextEditorHighlightingPassRegistrarImpl.instantiatePasses(TextEditorHighlightingPassRegistrarImpl.java:171)
	at com.intellij.codeInsight.daemon.impl.TextEditorBackgroundHighlighter.getPasses(TextEditorBackgroundHighlighter.java:75)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$14(DaemonCodeAnalyzerImpl.java:963)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:68)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$15(DaemonCodeAnalyzerImpl.java:954)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.lambda$queuePassesCreation$16(DaemonCodeAnalyzerImpl.java:946)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:184)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

```
Additional info: ```Opening .class files triggers this error.```

**Comment by pkukielka** [comment]
Fixed by https://github.com/sourcegraph/cody/pull/7156
