### ISSUE TITLE
bug: Freeze IDE

### ISSUE THREAD

**Issue by ceearrashee** [sourcegraph/jetbrains#2292]
### IDE Information

GoLand 2024.2.1.1
Build #GO-242.21829.220, built on September 8, 2024
Licensed to Yevhen Androsov
Subscription is active until October 4, 2024.
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4196M
Cores: 20
Registry:
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=TRUE
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.21829.162)
  dev.turingcomplete.intellijdevelopertoolsplugins (5.0.0)
  MultiHighlight (3.2.0)
  org.toml.lang (242.20224.155)
  org.intellij.plugins.postcss (242.20224.204)
  org.jetbrains.plugins.sass (242.20224.204)
  com.intellij.properties (242.20224.155)
  String Manipulation (9.14.1)
  hunspell (242.21829.220)
  XPathView (242.20224.155)
  com.intellij.tasks (242.20224.204)
  com.intellij.tasks.timeTracking (242.20224.204)
  com.intellij.mermaid (0.0.22+IJ.232)
  com.intellij.ml.llm (242.21829.196)
  com.intellij.grazie.pro (0.3.329)
  com.dsoftware.ghtoolbar (2024.2.8)
  com.intellij.queryComplexity (242.20224.159)
  NodeJS (242.21829.142)
  com.dmarcotte.handlebars (242.21829.3)
  me.mbolotov.cypress (1.6.2)
  tslint (242.20224.159)
  intellij.prettierJS (242.20224.159)
  com.github.copilot (1.5.21.6667)
  com.intellij.jira (4.9.0)
  com.mallowigi (97.0.0)
  mobi.hsz.idea.gitignore (4.5.3)
  com.github.linwancen.drawgraph (1.17.2024.09.11_03.00)
  com.ypwang.plugin.go-linter (1.6.6)
  cn.yiiguxing.plugin.translate (3.6.4)
  AngularJS (242.21829.3)

### Bug Description

I’m experiencing a recurring issue where GoLand IDE freezes, and I am unable to interact with it at all. 

Once the IDE freezes, I cannot close it through normal means, and the only solution is to terminate the task via Task Manager forcefully.

### Additional context

Log which was by the JetBrains team
```
2024-09-12 08:30:32,176 [76376457] SEVERE - #c.i.c.d.i.PassExecutorService - java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql

Error: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128783:19
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:129743:18
    at async C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128267:44
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql

Error: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128783:19
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:129743:18
    at async C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128267:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:133)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql

Error: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128783:19
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:129743:18
    at async C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128267:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:370)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql

Error: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128783:19
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:129743:18
    at async C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128267:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation$lambda$5(CodyFixHighlightPass.kt:122)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:182)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport$executeOnPooledThread$1.run(AnyThreadWriteThreadingSupport.kt:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql

Error: codeActions/provide: document not found for file:///C:/Users/eandr/Projects/Existlive/mouse-golang/db/migrations/20190912122949_org_account.up.sql
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128783:19
    at C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:129743:18
    at async C:\Users\eandr\AppData\Roaming\JetBrains\GoLand2024.2\plugins\Sourcegraph\agent\index.js:128267:44
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:204)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
2024-09-12 08:30:32,178 [76376459] SEVERE - #c.i.c.d.i.PassExecutorService - GoLand 2024.2.1.1  Build #GO-242.21829.220
2024-09-12 08:30:32,178 [76376459] SEVERE - #c.i.c.d.i.PassExecutorService - JDK: 21.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-09-12 08:30:32,178 [76376459] SEVERE - #c.i.c.d.i.PassExecutorService - OS: Windows 11
2024-09-12 08:30:32,178 [76376459] SEVERE - #c.i.c.d.i.PassExecutorService - Plugin to blame: Cody: AI Coding Assistant with Autocomplete & Chat version: 7.0.1
2024-09-12 08:30:32,178 [76376459] SEVERE - #c.i.c.d.i.PassExecutorService - Last Action: FindInPath
```

**Comment by chain710** [comment]
same here, freeze every 20~30 min

completely unusable

**Comment by luckycreationsindia** [comment]
I can confirm same issue here. For me every 2 mins.

**Comment by cyformatician** [comment]
Same issue with Phpstorm. Unrecoverable freeze leading to loss of coding done since IDE was started with plugin enabled! Please fix this.

Thanks

**Comment by flippyhead** [comment]
I'm on the latest webstorm, same for me. Was working well before the latest update. Now freezes after a few minutes. I disabled ALL other plugins except for Cody to confirm the problem.

**Comment by cyformatician** [comment]
> I'm on the latest webstorm, same for me. Was working well before the latest update. Now freezes after a few minutes. I disabled ALL other plugins except for Cody to confirm the problem.

Download and install latest nightly v7.0.4 .. stable build is expected to be released tomorrow.

https://plugins.jetbrains.com/plugin/9682-cody-ai-coding-assistant-with-autocomplete--chat/versions/nightly

**Comment by flippyhead** [comment]
I did that, disabled all other plugins and the problem is still happening. Can I provide anything to help?

**Comment by flippyhead** [comment]
Prior to locking up, I often get "running out of memory" notices in WebStorm.

**Comment by cyformatician** [comment]
@flippyhead Double check that you have version v7.0.4 installed and try clearing out your IDE caches and reindex your project/s. As for running out of memory, you might want to tweak your vm option properties of your IDE, specifically Xms and Xmx, ie:
`-Xms1024m`
`-Xmx4096m`

**Comment by ceearrashee** [comment]
Fix solves the bug. Tested to 2-3 days

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏 

Feel free to try nightly channel in the meantime 🌃

**Comment by mkondratek** [comment]
Also, if you see some other problems than `Error: codeActions/provide: document not found` feel free to issue a new bug report. Thank you for your assistance!
