### ISSUE TITLE
bug: kotlin.NotImplementedError: An operation is not implemented: NYI, focus the chat thru TypeScript

### ISSUE THREAD

**Issue by est7** [sourcegraph/jetbrains#2296]
### IDE Information

Android Studio Ladybug | 2024.2.1 Beta 2
Build #AI-242.21829.142.2421.12332550, built on September 7, 2024
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 8
Metal Rendering is ON
Registry:
  action.toolbar.position.bottom.on.mac=true
  debugger.new.tool.window.layout=true
  vcs.log.index.enable=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.monokai.colorscheme (242.20224.159)
  com.intellij.ideolog (242.21829.162)
  com.intellij.marketplace (242.21829.220)
  org.jetbrains.jumpToLine (0.1.16)
  io.github.anvell.dune-theme (2.0.5)
  com.codigrate.autumn.theme (1.0.17)
  com.github.lppedd.idea-conventional-commit (0.23.1)
  com.nvlad.tinypng-optimizer (1.0.8)
  com.markskelton.one-dark-theme (5.11.0)
  tv.codely.codelytv-theme (3.0.0)
  com.levinzonr.arch.jetpackcompose.plugin (1.4.1)
  io.github.mani-sh-reddy.mariana-light (0.0.8)
  wu.seal.tool.jsontokotlin (3.7.5)
  AceJump (3.8.19)
  com.github.camork.fileExpander (2.5)
  com.jetbrains.embeddedProjectJdk (2.5)
  idea.plugin.protoeditor (242.21829.3)
  awesome.console (0.1337.12)
  Docker (242.21829.162)
  monokai-pro (1.10)
  IdeaVIM (2.17.0-eap.1)
  com.github.dankinsoid.multicursor (1.2.2)
  IdeaVimExtension (1.7.4)
  org.jetbrains.IdeaVim-EasyMotion (1.15)
  com.joshestein.ideavim-quickscope (1.0.12)
  ru.adelf.idea.dotenv (2024.2.1)
  izhangzhihao.rainbow.brackets.lite (1.2.0)
  com.github.catppuccin.jetbrains_icons (1.8.0)
  com.developerphil.adbidea (1.6.18)
  com.sourcegraph.jetbrains (7.0.4-nightly)
  zielu.gittoolbox (500.2.15+242)
  ru.serafimarts.roboticket (1.1.3)
  cn.yiiguxing.plugin.translate (3.6.4)

### Bug Description

When I open the cody chat panel, this error is shown

### Additional context

Stacktrace:
```text
kotlin.NotImplementedError: An operation is not implemented: NYI, focus the chat thru TypeScript
	at com.sourcegraph.cody.chat.OpenChatAction.actionPerformed(OpenChatAction.kt:15)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:345)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:32)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$actionProcessor$1.performAction(IdeKeyEventDispatcher.kt:496)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$4$lambda$3(IdeKeyEventDispatcher.kt:845)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner$lambda$4(IdeKeyEventDispatcher.kt:845)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1177)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:362)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.doPerformActionInner(IdeKeyEventDispatcher.kt:843)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcherKt.access$doPerformActionInner(IdeKeyEventDispatcher.kt:1)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction$intellij_platform_ide_impl(IdeKeyEventDispatcher.kt:572)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.kt:509)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.kt:448)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.kt:441)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.kt:303)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:620)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$15(IdeEventQueue.kt:582)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:582)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by PriNova** [comment]
Thank you for reporting the issue.

**Comment by alpafm** [comment]
Hi, any plans to fix it? I am constantly running into it.

**Comment by PriNova** [comment]
@alpafm When exactly does this happen? From the log I assume you try to open Cody chat via keymap shortcut?
Please try to re-assign another shortcut for opening the Cody chat window. This might solve the issue of conflicting keymappings.

**Comment by PriNova** [comment]
Hey @est7 

The team fixed the issue by https://github.com/sourcegraph/cody/pull/7273
Please update the Cody extension and try again.

Thank you
