### ISSUE TITLE
`Error: Cannot add a bot message after a bot message` on an error from chat 

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#233]
The error appears in the `runIde` logs:

```
2023-12-28 13:24:28,476 [  62751]   WARN - #c.s.c.a.CodyAgent - /Users/mkondratek/IdeaProjects/cody/vscode/src/chat/chat-view/SimpleChatModel.ts:68
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent -             throw new Error('Cannot add a bot message after a bot message')
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent -                   ^
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent - 
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent - 
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent - Error: Cannot add a bot message after a bot message
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent -     at SimpleChatModel.addBotMessage (/Users/mkondratek/IdeaProjects/cody/vscode/src/chat/chat-view/SimpleChatModel.ts:68:19)
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent -     at <anonymous> (/Users/mkondratek/IdeaProjects/cody/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts:851:32)
2023-12-28 13:24:28,477 [  62752]   WARN - #c.s.c.a.CodyAgent -     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

## Steps to reproduce

1. Having the most recent changes related to the new UI:
- https://github.com/sourcegraph/cody/pull/2457
- https://github.com/sourcegraph/jetbrains/pull/220
2. Switch to an account with the rate limit exceeded 
3. Write a message to the chat 

## Actual 
- no rate limit error notification in the chat 
- the error from the snippet ☝️ in the logs

## Expected 
- rate limit error notification in the chat
- no error in the logs

**Comment by mkondratek** [comment]
## My investigation results 

the method: [addBotMessageWithGuardrails](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L848%3A13-848%3A40)

is called from ([sg link](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L683:24&popover=pinned)):
```
close: content => {
    this.addBotMessageWithGuardrails(requestID, content)
}
```
and that is called from [typewriter.close()](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatPanelProvider.ts?L741%3A22-741%3A39).

**Comment by mkondratek** [comment]
this is fixed now - see the linked PR
