### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by youssofOkiel** [sourcegraph/jetbrains#2350]
### IDE Information

PhpStorm 2024.2.1
Build #PS-242.21829.154, built on August 29, 2024
Licensed to ahmed medhat
Subscription is active until May 23, 2025.
For educational use only.
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2304M
Cores: 11
Metal Rendering is ON
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  ru.adelf.idea.dotenv (2024.2.1)
  nl.deschepers.laraveltinker (2.7.3)
  com.laravel_idea.plugin (8.2.5.242)
  com.sourcegraph.jetbrains (7.0.2)

### Bug Description

ide crashed when i delete line or rollback something in git

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/youssofokiel/Work/Sites/petroapp-new/resources/views/invoices/zoho_pdf/vehicle_operation_tool_replacement_invoice_pdf.blade.php

Error: codeActions/provide: document not found for file:///Users/youssofokiel/Work/Sites/petroapp-new/resources/views/invoices/zoho_pdf/vehicle_operation_tool_replacement_invoice_pdf.blade.php
    at /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:128784:19
    at /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:129744:18
    at async /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:128268:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:128)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/youssofokiel/Work/Sites/petroapp-new/resources/views/invoices/zoho_pdf/vehicle_operation_tool_replacement_invoice_pdf.blade.php

Error: codeActions/provide: document not found for file:///Users/youssofokiel/Work/Sites/petroapp-new/resources/views/invoices/zoho_pdf/vehicle_operation_tool_replacement_invoice_pdf.blade.php
    at /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:128784:19
    at /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:129744:18
    at async /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:128268:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:370)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/youssofokiel/Work/Sites/petroapp-new/resources/views/invoices/zoho_pdf/vehicle_operation_tool_replacement_invoice_pdf.blade.php

Error: codeActions/provide: document not found for file:///Users/youssofokiel/Work/Sites/petroapp-new/resources/views/invoices/zoho_pdf/vehicle_operation_tool_replacement_invoice_pdf.blade.php
    at /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:128784:19
    at /Users/youssofokiel/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:129744:18
    at async /U...
```

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
