### ISSUE TITLE
bug: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize

### ISSUE THREAD

**Issue by ericbsd** [sourcegraph/jetbrains#2362]
### IDE Information

PyCharm 2024.2.1 (Community Edition)
Build #PC-242.21829.153, built on August 29, 2024
Runtime version: 17.0.12+7-1 amd64
VM: OpenJDK 64-Bit Server VM by OpenJDK BSD Porting Team
Toolkit: sun.awt.X11.XToolkit
FreeBSD 14.1-stable
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  String Manipulation (9.14.1)
  org.jetbrains.plugins.gitlab (242.21829.162)
  com.sourcegraph.jetbrains (7.0.8-nightly)
Current Desktop: MATE

### Bug Description

I just noticed that the chat window is empty, so I generated a report. I mostly use autocompletion, which works well, and missing the chat is not a big deal.

![image](https://github.com/user-attachments/assets/69047cf3-7704-4d7d-ae79-decf51e88bea)

### Additional context

Stacktrace:
```text
java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:210)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:172)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:36)
	at com.intellij.ui.jcef.JBCefBrowser.create(JBCefBrowser.java:116)
	at com.intellij.ui.jcef.JBCefBrowserBuilder.build(JBCefBrowserBuilder.java:136)
	at com.sourcegraph.cody.ui.web.WebUIProxy$Companion.create(WebUIProxy.kt:116)
	at com.sourcegraph.cody.ui.web.WebUIService.createWebviewView$Sourcegraph(WebUIService.kt:115)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.provideView(WebviewView.kt:109)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.provideHost$lambda$5(WebviewView.kt:100)
	at com.intellij.openapi.application.ActionsKt.runInEdt(actions.kt:56)
	at com.intellij.openapi.application.ActionsKt.runInEdt$default(actions.kt:53)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.provideHost(WebviewView.kt:100)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.provideCodyToolWindowContent(WebviewView.kt:104)
	at com.sourcegraph.cody.CodyToolWindowContent.<init>(CodyToolWindowContent.kt:45)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:49)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt$instantiate$2.invoke(instantiate.kt:42)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:313)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:42)
	at com.intellij.serviceContainer.LightServiceInstanceSupport$LightServiceInstanceInitializer.createInstance(LightServiceInstanceSupport.kt:47)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:162)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:160)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:145)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:13)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:135)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:95)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:87)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.serviceContainer.ComponentManagerImplKt$doGetOrCreateInstanceBlocking$1.invokeSuspend(ComponentManagerImpl.kt:1568)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:111)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:1686)
	at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:1677)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:85)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:1677)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doGetOrCreateInstanceBlocking(ComponentManagerImpl.kt:1567)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1562)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.sourcegraph.cody.CodyToolWindowContent$Companion.executeOnInstanceIfNotDisposed$lambda$0(CodyToolWindowContent.kt:111)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:1985)
	at com.sourcegraph.cody.CodyToolWindowContent$Companion.executeOnInstanceIfNotDisposed(CodyToolWindowContent.kt:109)
	at com.sourcegraph.cody.CodyToolWindowFactory.createToolWindowContent(CodyToolWindowFactory.java:22)
	at com.intellij.openap...
```

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the troubles 🙇 

We are aware of the issue and it has been fixed already by https://github.com/sourcegraph/jetbrains/pull/2451.

I am happy to announce that the fix is available in the latest available release 🚀  Please keep the plugin up to date 🙏
