### ISSUE TITLE
Comparing Local Class with Server Class using Illuminated Cloud

### ISSUE THREAD

**Issue by kwukdev** [sourcegraph/jetbrains#2378]
### IDE Information

WebStorm 2024.2.3
Build #WS-242.23339.15, built on September 25, 2024
Licensed to Trial User
Subscription is active until October 15, 2024.
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 24
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.markskelton.one-dark-theme (5.12.0)
  com.illuminatedcloud2.intellij (2.3.3.0)
  com.sourcegraph.jetbrains (7.0.6)

### Bug Description

Using Illuminated Cloud, ran a compare of local class against server class.  Failed without showing comparison.

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/capew/AppData/Local/JetBrains/WebStorm2024.2/tmp/Prep-Prep-retrieve8/diff/force-app/main/default/classes/CloneSTLayout2Batch.cls

Error: codeActions/provide: document not found for file:///C:/Users/capew/AppData/Local/JetBrains/WebStorm2024.2/tmp/Prep-Prep-retrieve8/diff/force-app/main/default/classes/CloneSTLayout2Batch.cls
    at C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:128784:19
    at C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:129744:18
    at async C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:128268:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:104)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:416)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:392)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:392)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:390)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:259)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/capew/AppData/Local/JetBrains/WebStorm2024.2/tmp/Prep-Prep-retrieve8/diff/force-app/main/default/classes/CloneSTLayout2Batch.cls

Error: codeActions/provide: document not found for file:///C:/Users/capew/AppData/Local/JetBrains/WebStorm2024.2/tmp/Prep-Prep-retrieve8/diff/force-app/main/default/classes/CloneSTLayout2Batch.cls
    at C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:128784:19
    at C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:129744:18
    at async C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:128268:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:370)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/capew/AppData/Local/JetBrains/WebStorm2024.2/tmp/Prep-Prep-retrieve8/diff/force-app/main/default/classes/CloneSTLayout2Batch.cls

Error: codeActions/provide: document not found for file:///C:/Users/capew/AppData/Local/JetBrains/WebStorm2024.2/tmp/Prep-Prep-retrieve8/diff/force-app/main/default/classes/CloneSTLayout2Batch.cls
    at C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:128784:19
    at C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\agent\index.js:129744:18
    at async C:\Users\capew\AppData\Roaming\JetBrains\WebStorm2024.2\plugins\Sourcegraph\age...
```

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
