### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by hungpd9** [sourcegraph/jetbrains#2381]
### IDE Information

PhpStorm 2024.2.3
Build #PS-242.23339.16, built on September 25, 2024
Licensed to Vũ Phạm Anh
Subscription is active until November 23, 2024.
For educational use only.
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4056M
Cores: 12
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  cn.yiiguxing.plugin.translate (3.6.5)
  ru.adelf.idea.dotenv (2024.2.1)
  com.laravel_idea.plugin (8.3.3.242)
  com.sourcegraph.jetbrains (7.0.6)

### Bug Description

after open program on window 10, error has showing

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///D:/laragon/www/carrental/app/Helpers/helper.php

Error: codeActions/provide: document not found for file:///D:/laragon/www/carrental/app/Helpers/helper.php
    at C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:128784:19
    at C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:129744:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:128268:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:104)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:416)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:392)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:392)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:390)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:259)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///D:/laragon/www/carrental/app/Helpers/helper.php

Error: codeActions/provide: document not found for file:///D:/laragon/www/carrental/app/Helpers/helper.php
    at C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:128784:19
    at C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:129744:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:128268:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:370)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///D:/laragon/www/carrental/app/Helpers/helper.php

Error: codeActions/provide: document not found for file:///D:/laragon/www/carrental/app/Helpers/helper.php
    at C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:128784:19
    at C:\Users\hungp\AppData\Roaming\JetBrains\PhpStorm2024.2\plugins\Sourcegraph\agent\index.js:129744:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at pro...
```

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
