### ISSUE TITLE
bug: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by istvan-ujjmeszaros** [sourcegraph/jetbrains#2445]
### IDE Information

PhpStorm 2024.3 EAP
Build #PS-243.19420.27, built on October 9, 2024
Licensed to PhpStorm EAP user: Istvan Meszaros
Expiration date: November 8, 2024
Runtime version: 21.0.4+8-b620.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.jetbrains.gerryPurpleTheme (2024.1.1010)
  com.jetbrains.space (243.19420.21)
  Statistic (4.3.1)
  com.intellij.remoteControl (243.19420.21)
  PlantUML integration (7.11.2-IJ2023.2)
  com.jetbrains.lang.ejs (243.19420.21)
  org.vepanimas.uml.javascript (0.3.0)
  com.sourcegraph.jetbrains (7.0.13-nightly)
  com.intellij.plugins.html.instantEditing (243.19420.21)
  ru.adelf.idea.dotenv (2024.3)
  org.endpointdeps.EndpointDependencies (1.3)
  de.espend.idea.php.phpunit (7.1)

### Bug Description

I just left the IDE to do something outside of it, and then it closed itself.

### Additional context

Stacktrace:
```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:126)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:95)
	at com.sourcegraph.cody.auth.AccountManagerBase.findCredentials(AccountManagerBase.kt:109)
	at com.sourcegraph.cody.config.CodyAuthenticationManager.getTokenForAccount$Sourcegraph(CodyAuthenticationManager.kt:211)
	at com.sourcegraph.cody.config.CodyAuthenticationManager.getAuthenticationState(CodyAuthenticationManager.kt:133)
	at com.sourcegraph.cody.config.CodyAuthenticationManager.getIsTokenInvalid(CodyAuthenticationManager.kt:206)
	at com.sourcegraph.cody.config.CodyAuthenticationManager.showInvalidAccessTokenError(CodyAuthenticationManager.kt:274)
	at com.sourcegraph.cody.CodyToolWindowContent.refreshPanelsVisibility(CodyToolWindowContent.kt:55)
	at com.sourcegraph.cody.CodyToolWindowContent.<init>(CodyToolWindowContent.kt:48)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate$lambda$0(instantiate.kt:50)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate$lambda$8$lambda$7(instantiate.kt:310)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.withStoredTemporaryContext(instantiate.kt:328)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:309)
	at com.intellij.platform.instanceContainer.instantiation.InstantiateKt.instantiate(instantiate.kt:43)
	at com.intellij.serviceContainer.LightServiceInstanceSupport$LightServiceInstanceInitializer.createInstance(LightServiceInstanceSupport.kt:47)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invokeSuspend(LazyInstanceHolder.kt:163)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invokeSuspend(LazyInstanceHolder.kt:161)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder$initialize$1.invoke(LazyInstanceHolder.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.initialize(LazyInstanceHolder.kt:146)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.access$initialize(LazyInstanceHolder.kt:14)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.tryInitialize(LazyInstanceHolder.kt:136)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstance(LazyInstanceHolder.kt:96)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext$suspendImpl(LazyInstanceHolder.kt:88)
	at com.intellij.platform.instanceContainer.internal.LazyInstanceHolder.getInstanceInCallerContext(LazyInstanceHolder.kt)
	at com.intellij.serviceContainer.ComponentManagerImplKt$doGetOrCreateInstanceBlocking$1.invokeSuspend(ComponentManagerImpl.kt:1566)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:111)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$BuildersKt__BuildersKt(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:52)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization$lambda$10(ComponentManagerImpl.kt:1684)
	at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:85)
	at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:1675)
	at com.intellij.serviceContainer.ComponentManagerImplKt.doGetOrCreateInstanceBlocking(ComponentManagerImpl.kt:1565)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1560)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:751)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:695)
	at com.sourcegraph.cody.CodyToolWindowContent$Companion.executeOnInstanceIfNotDisposed$lambda$0(CodyToolWindowContent.kt:115)
	at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:32)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:1988)
	at com.sourcegraph.cody.CodyToolWindowContent$Companion.executeOnInstanceIfNotDisposed(CodyToolWindowContent.kt:113)
	at com.sourcegraph.cody.CodyToolWindowFactory.createToolWindowContent(CodyToolWindowFactory.java:22)
	at com.intellij.openapi.wm.impl.ToolWindowIm...

**Comment by PriNova** [comment]
Thank you for reporting the issue.
