### ISSUE TITLE
bug: java.nio.file.InvalidPathException: Illegal char <<> at index 0: <808463de-3381-4a54-a04b-af011d71c15b>/wp-config.php

### ISSUE THREAD

**Issue by sergio-its-goodboy** [sourcegraph/jetbrains#2489]
### IDE Information

IntelliJ IDEA 2024.2.3 (Ultimate Edition)
Build #IU-242.23339.11, built on September 25, 2024
Licensed to Sergio Estefan Fiallo Cabrera
Subscription is active until September 22, 2025.
For educational use only.
Runtime version: 21.0.4+13-b509.17 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.intellij.laf.enable.animation=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.sublimetextkeymap (241.13688.16)
  PythonCore (242.23339.11)
  awesome.console (0.1337.12)
  IdeaVIM (2.16.0)
  io.acari.DDLCTheme (88.5-1.14.1)
  io.unthrottled.doki.icons (88.5-1.4.0)
  com.daynight.plugin (2.0.0)
  com.intellij.lang.liquid (242.20224.159)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.bluewaitor.tsReact (1.4.0)
  Key Promoter X (2024.2.0)
  com.intellij.plugin.adernov.powershell (2.7.0)
  Pythonid (242.23339.11)
  com.intellij.python.django (242.23339.11)
  Dart (242.22855.32)
  com.nasller.CodeGlancePro (1.9.2)
  org.jetbrains.android (242.23339.11)
  com.haulmont.rcb (242.20224.155)
  io.flutter (82.0.3)
  com.crzsc.FlutterAssetsGenerator (2.4.2)
  com.virtuslab.git-machete (5.1.1)
  com.sourcegraph.jetbrains (7.0.15-nightly)
  com.jetbrains.php (242.23339.16)
  com.jetbrains.twig (242.23339.18)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (11.1.0)
  com.jetbrains.php.blade (242.23339.16)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  zielu.gittoolbox (600.0.2+242)
  com.jsdelivr.pluginintellij.JsDelivrPackageSearch (1.0.9)
Kotlin: 242.23339.11-IJ

### Bug Description

After downloading a file from sftp and then trying to write or use the arrow keys i can't use the arrow keys or enter or select any text and this error pop ups. and can't do anything with the file.

### Additional context

Stacktrace:
```text
java.nio.file.InvalidPathException: Illegal char <<> at index 0: <808463de-3381-4a54-a04b-af011d71c15b>/wp-config.php
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:199)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.uriFor(ProtocolTextDocument.kt:197)
	at com.sourcegraph.cody.agent.protocol.ProtocolTextDocument$Companion.fromEditorWithOffsetSelection(ProtocolTextDocument.kt:92)
	at com.sourcegraph.cody.listeners.CodyCaretListener.caretPositionChanged(CodyCaretListener.kt:27)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:119)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:84)
	at jdk.proxy2/jdk.proxy2.$Proxy171.caretPositionChanged(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:119)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:84)
	at jdk.proxy2/jdk.proxy2.$Proxy171.caretPositionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.CaretModelImpl.fireCaretPositionChanged(CaretModelImpl.java:536)
	at com.intellij.openapi.editor.impl.CaretImpl.doMoveToVisualPosition(CaretImpl.java:593)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$moveToVisualPosition$4(CaretImpl.java:531)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:412)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:531)
	at com.intellij.openapi.editor.impl.CaretImpl.moveToVisualPosition(CaretImpl.java:527)
	at com.intellij.openapi.editor.CaretModel.moveToVisualPosition(CaretModel.java:68)
	at com.intellij.openapi.editor.impl.EditorImpl.processMouseDragged(EditorImpl.java:2731)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$new$0(EditorImpl.java:276)
	at com.intellij.ide.ui.laf.MouseDragSelectionEventHandler.mouseDragged(MouseDragSelectionEventHandler.kt:14)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$runMouseDraggedCommand$62(EditorImpl.java:2617)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.impl.EditorImpl.runMouseDraggedCommand(EditorImpl.java:2617)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.lambda$mouseDragged$0(EditorImpl.java:4816)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseDragged(EditorImpl.java:4816)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6713)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3412)
	at java.desktop/java.awt.Component.processEvent(Component.java:6434)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5035)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4594)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at ja...

**Comment by PriNova** [comment]
Duplicate of #2199
