### ISSUE TITLE
bug: java.lang.AssertionError: Assertion failed

### ISSUE THREAD

**Issue by muhammedashraf9244** [sourcegraph/jetbrains#2514]
### IDE Information

PyCharm 2024.2.4 (Community Edition)
Build #PC-242.23726.102, built on October 22, 2024
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 5.15.0-124-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3964M
Cores: 12
Registry:
  ide.balloon.shadow.size=0
  ide.intellij.laf.enable.animation=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  me.x150.intellij-code-screenshots (1.4.8)
  com.andrey4623.rainbowcsv (2.0.2)
  one.util.ideaplugin.screenshoter (1.8.1)
  com.godwin.json.parser (1.7.1)
  org.xiaogang.unit.test (0.0.4.8)
  dev.turingcomplete.intellijdevelopertoolsplugins (5.1.0)
  com.karateca.jstoolbox (1.10)
  org.jetbrains.intellij.scripting-javascript (1.3)
  ris58h.webcalm (0.11.1)
  indent-rainbow.indent-rainbow (2.2.0)
  com.pinkfloyded.idea-file-path-autocomplete.idea-file-path-autocomplete (0.4.1)
  com.jetbrains.space (242.23726.16)
  Docker (242.23726.107)
  com.intellij.ml.llm (242.23726.20)
  com.intellij.grazie.pro (0.3.343)
  izhangzhihao.rainbow.brackets (2024.2.6-241)
  net.firebits.odoo (1.2.1)
  com.nnthink.aixcoder (5.2.1-2024)
  at.wtioit.intellij.plugins.odoo (0.6.11)
  com.vermouthx.idea (1.16.0)
  net.seesharpsoft.intellij.plugins.csv (4.0.0)
  com.sourcegraph.jetbrains (7.0.13)
  zielu.gittoolbox (600.0.5+242)
  mobi.hsz.idea.gitignore (4.5.4)
  com.obroom.plugin.toolset (2024.8.1)
Current Desktop: ubuntu:GNOME

### Bug Description

bug: java.lang.AssertionError: Assertion failed

### Additional context

Stacktrace:
```text
java.lang.AssertionError: Assertion failed
	at com.sourcegraph.cody.ui.web.CodyToolWindowContentWebviewHost.adopt$lambda$0(WebviewView.kt:39)
	at com.intellij.openapi.application.ActionsKt.runInEdt(actions.kt:56)
	at com.intellij.openapi.application.ActionsKt.runInEdt$default(actions.kt:53)
	at com.sourcegraph.cody.ui.web.CodyToolWindowContentWebviewHost.adopt(WebviewView.kt:38)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.provideView$lambda$6(WebviewView.kt:110)
	at com.sourcegraph.cody.ui.web.WebUIService.createWebviewView$Sourcegraph(WebUIService.kt:116)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.provideView(WebviewView.kt:109)
	at com.sourcegraph.cody.ui.web.WebviewViewManager.registerProvider$lambda$3(WebviewView.kt:89)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:66)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:229)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$1(AnyThreadWriteThreadingSupport.kt:184)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:183)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:836)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:424)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithImplicitRead(AnyThreadWriteThreadingSupport.kt:122)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1162)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:78)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:119)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:696)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:590)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWithoutImplicitRead(AnyThreadWriteThreadingSupport.kt:117)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:590)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:73)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:357)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1$1.compute(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.invoke(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke$lambda$0(IdeEventQueue.kt:1035)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:84)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:910)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt$performActivity$runnableWithWIL$1.invoke(IdeEventQueue.kt:1035)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1036)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1036)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$10(IdeEventQueue.kt:351)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:397)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchTh...

**Comment by PriNova** [comment]
Thank you for reporting the issue. This is a duplicate of #2302
