### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by bendx77** [sourcegraph/jetbrains#2529]
### IDE Information

PhpStorm 2023.1.5
Build #PS-231.9414.10, built on February 14, 2024
Licensed to Benjamin Dixon
You have a perpetual fallback license for this version.
Subscription expired on July 28, 2024.
Runtime version: 17.0.10+10-b829.26 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 32
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.intellij.grazie.pro (0.3.271)
    com.sourcegraph.jetbrains (6.0.34)

### Bug Description

SEEMS LIKE FOR NO REASON JUST POPPED UP

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/bendo/PhpstormProjects/picklefriend.net/public_html/Mixer-Dev/includes/player_functions.php

Error: codeActions/provide: document not found for file:///C:/Users/bendo/PhpstormProjects/picklefriend.net/public_html/Mixer-Dev/includes/player_functions.php
    at C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:138490:19
    at C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:139426:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:137987:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:132)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:347)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:133)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1100)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/bendo/PhpstormProjects/picklefriend.net/public_html/Mixer-Dev/includes/player_functions.php

Error: codeActions/provide: document not found for file:///C:/Users/bendo/PhpstormProjects/picklefriend.net/public_html/Mixer-Dev/includes/player_functions.php
    at C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:138490:19
    at C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:139426:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:137987:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:332)
	... 21 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///C:/Users/bendo/PhpstormProjects/picklefriend.net/public_html/Mixer-Dev/includes/player_functions.php

Error: codeActions/provide: document not found for file:///C:/Users/bendo/PhpstormProjects/picklefriend.net/public_html/Mixer-Dev/includes/player_functions.php
    at C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:138490:19
    at C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:139426:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async C:\Users\bendo\AppData\Roaming\JetBrains\PhpStorm2023.1\plugins\Sourcegraph\agent\index.js:137987:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableF...
```

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
