### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by vrybas** [sourcegraph/jetbrains#2537]
### IDE Information

GoLand 2024.2.3
Build #GO-242.23339.24, built on September 26, 2024
Licensed to Vladimir Rybas
Subscription is active until October 29, 2024.
Evaluation purpose only.
Runtime version: 21.0.4+13-b509.17 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=TRUE
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.twig (242.23339.18)
  net.sjrx.intellij.plugins.systemdunitfiles (223.241023.292)
  com.tabnine.TabNine (1.153.0)
  MultiHighlight (3.2.0)
  AceJump (3.8.20)
  indent-rainbow.indent-rainbow (2.2.0)
  com.intellij.ml.llm (242.23339.40)
  IdeaVIM (2.16.0)
  net.seesharpsoft.intellij.plugins.csv (4.0.0)
  com.sourcegraph.jetbrains (7.0.18)
  com.github.copilot (1.5.27.7265)
  ru.adelf.idea.dotenv (2024.2.1)
  net.ashald.envfile (3.4.2)

### Bug Description

Error occurred when IDE was showing Database plugin with one of he DB consoles open

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/vladimir.rybas/Library/Application%20Support/JetBrains/GoLand2024.2/consoles/db/e39796ba-7770-480a-a143-27f13fb8ee75/console.sql

Error: codeActions/provide: document not found for file:///Users/vladimir.rybas/Library/Application%20Support/JetBrains/GoLand2024.2/consoles/db/e39796ba-7770-480a-a143-27f13fb8ee75/console.sql
    at /Users/vladimir.rybas/Library/Application Support/JetBrains/GoLand2024.2/plugins/Sourcegraph/agent/index.js:134957:19
    at /Users/vladimir.rybas/Library/Application Support/JetBrains/GoLand2024.2/plugins/Sourcegraph/agent/index.js:135868:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at async /Users/vladimir.rybas/Library/Application Support/JetBrains/GoLand2024.2/plugins/Sourcegraph/agent/index.js:134418:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:104)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:416)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:392)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:392)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:390)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:259)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/vladimir.rybas/Library/Application%20Support/JetBrains/GoLand2024.2/consoles/db/e39796ba-7770-480a-a143-27f13fb8ee75/console.sql

Error: codeActions/provide: document not found for file:///Users/vladimir.rybas/Library/Application%20Support/JetBrains/GoLand2024.2/consoles/db/e39796ba-7770-480a-a143-27f13fb8ee75/console.sql
    at /Users/vladimir.rybas/Library/Application Support/JetBrains/GoLand2024.2/plugins/Sourcegraph/agent/index.js:134957:19
    at /Users/vladimir.rybas/Library/Application Support/JetBrains/GoLand2024.2/plugins/Sourcegraph/agent/index.js:135868:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at async /Users/vladimir.rybas/Library/Application Support/JetBrains/GoLand2024.2/plugins/Sourcegraph/agent/index.js:134418:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:370)
	... 27 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/vladimir.rybas/Library/Application%20Support/JetBrains/GoLand2024.2/consoles/db/e39796ba-7770-480a-a143-27f13fb8ee75/console.sql

Error: codeActions/provide: docume...

**Comment by mkondratek** [comment]
Hi 👋 thanks for reporting. please note that the issue has been fixed. 

It should work since 7.0.19. Please be patient and wait for the the next release 🙏
