### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by Flaxoos** [sourcegraph/jetbrains#2565]
### IDE Information

RustRover 2024.2
Build #RR-242.21829.198, built on September 5, 2024
Licensed to Ido Flasch
Subscription is active until May 27, 2025.
For non-commercial use only.
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 28672M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.attach.dialog.enabled=true
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui.show.promotion=false
  org.toml.json.schema=false
  llm.ai.assistant.toolwindow.activation.on.start=false
  transferSettings.vscode.onlyCargoToml=true
Non-Bundled Plugins:
  com.github.lppedd.idea-conventional-commit (0.23.1)
  com.codeium.intellij (1.22.4)
  varme.pw.oceanic-dark-theme (1.1.9)
  String Manipulation (9.14.1)
  com.noctumsempra.themes.espresso.lightgram (1.0.3.1)
  org.jetbrains.plugins.hocon (2024.2.0)
  foundation (1.4)
  white-sand-ui (0.2.6)
  org.jetbrains.idea.grammar (2022.3.2)
  com.jetbrains.CyanTheme (1.3)
  com.github.voml.neo_theme (0.4.2)
  rasarts.espresso.light.theme (1.2.0)
  com.jetbrains.edu (2024.9-2024.2-1051)
  com.intellij.ml.llm (242.21829.196)
  com.intellij.laf.macos (242.20224.155)
  com.github.yunabraska.githubworkflowplugin (2024.2.0)
  com.sourcegraph.jetbrains (7.0.18)
  com.jetbrains.hackathon.indices.viewer (1.28)
  light.flat.theme (0.14)
  com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.17.0)

### Bug Description

Just showed up

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/ido/IdeaProjects/Forks%20and%20refs/frost-dalek-fork/benches/dalek_benchmarks.rs

Error: codeActions/provide: document not found for file:///Users/ido/IdeaProjects/Forks%20and%20refs/frost-dalek-fork/benches/dalek_benchmarks.rs
    at /Users/ido/Library/Application Support/JetBrains/RustRover2024.2/plugins/Sourcegraph/agent/index.js:134957:19
    at /Users/ido/Library/Application Support/JetBrains/RustRover2024.2/plugins/Sourcegraph/agent/index.js:135868:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async /Users/ido/Library/Application Support/JetBrains/RustRover2024.2/plugins/Sourcegraph/agent/index.js:134418:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:104)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:418)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:413)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:404)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:403)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:379)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:377)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:190)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/ido/IdeaProjects/Forks%20and%20refs/frost-dalek-fork/benches/dalek_benchmarks.rs

Error: codeActions/provide: document not found for file:///Users/ido/IdeaProjects/Forks%20and%20refs/frost-dalek-fork/benches/dalek_benchmarks.rs
    at /Users/ido/Library/Application Support/JetBrains/RustRover2024.2/plugins/Sourcegraph/agent/index.js:134957:19
    at /Users/ido/Library/Application Support/JetBrains/RustRover2024.2/plugins/Sourcegraph/agent/index.js:135868:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async /Users/ido/Library/Application Support/JetBrains/RustRover2024.2/plugins/Sourcegraph/agent/index.js:134418:44
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture....

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
