### ISSUE TITLE
bug: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp...

### ISSUE THREAD

**Issue by bdteo** [sourcegraph/jetbrains#2569]
### IDE Information

PhpStorm 2024.2.4
Build #PS-242.23726.107, built on October 23, 2024
Licensed to Boris Teoharov
Subscription is active until November 18, 2024.
Runtime version: 21.0.4+13-b509.26 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 12240M
Cores: 10
Metal Rendering is ON
Registry:
  actionSystem.playback.typecommand.delay=500
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  net.sjrx.intellij.plugins.systemdunitfiles (223.241023.292)
  com.intellij.plugin.applescript (0.121)
  com.jetbrains.space (242.23726.16)
  com.godwin.json.parser (1.7.2)
  com.crunch42.openapi (1.93-242)
  com.intellij.properties (242.20224.155)
  com.wix.sasslint (1.1.3)
  String Manipulation (9.14.1)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  Key Promoter X (2024.2.0)
  com.intellij.aqua (242.23726.125)
  com.intellij.mermaid (0.0.22+IJ.232)
  com.intellij.kubernetes (242.23726.19)
  com.intellij.ml.llm (242.23726.20)
  pro.bashsupport (4.3.2.242)
  com.atlassian.bitbucket.references (2023.1.304)
  com.github.aleksandrsl.intellijbrowserslist (1.0.2)
  me.rerere.unocss-intellij (1.7.4)
  com.dmarcotte.handlebars (242.21829.3)
  com.jetbrains.lang.ejs (242.20224.155)
  me.serce.solidity (2.4.5)
  deno (242.21829.3)
  lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
  ru.adelf.idea.dotenv (2024.2.1)
  com.axeldev.php1Up (0.1.2)
  net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
  de.espend.idea.php.toolbox (6.2.0)
  de.espend.idea.php.annotation (11.1.0)
  fr.adrienbrault.idea.symfony2plugin (2024.1.276)
  com.laravel_idea.plugin (8.4.0.242)
  com.aurimasniekis.phppsr4namespacedetector (1.0.1)
  com.sourcegraph.jetbrains (7.0.18)
  de.shyim.shopware6 (0.0.45)
  zielu.gittoolbox (600.0.5+242)
  mobi.hsz.idea.gitignore (4.5.4)
  dev.nx.console (1.32.4)

### Bug Description

I am a bit new to SourceGraph, and I like it generally, and it works. Maybe there is something that is breaking but I am not aware of what is breaking. However these error notifications are messy and distracting.
Please, investigate what happens.
All the best!

### Additional context

Stacktrace:
```text
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/boris/DevEnvs/ProBidder/probidder/fls/www/karadjata/date-check.php

Error: codeActions/provide: document not found for file:///Users/boris/DevEnvs/ProBidder/probidder/fls/www/karadjata/date-check.php
    at /Users/boris/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:134957:19
    at /Users/boris/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:135868:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    at process.topLevelDomainCallback (node:domain:160:15)
    at process.callbackTrampoline (node:internal/async_hooks:128:24)
    at async /Users/boris/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:134418:44
	at com.intellij.util.ExceptionUtil.rethrow(ExceptionUtil.java:136)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.awaitWithCheckCanceled(ProgressIndicatorUtils.java:399)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doCollectInformation(CodyFixHighlightPass.kt:104)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:431)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.runWithSpanIgnoreThrows(trace.kt:118)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceUtil.runWithSpanThrows(TraceUtil.java:36)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$3(PassExecutorService.java:426)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:291)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:965)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$4(PassExecutorService.java:417)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:416)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:392)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.cacheFileTypesInside(FileTypeManagerImpl.java:802)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$1(PassExecutorService.java:392)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.executeByImpatientReader(AnyThreadWriteThreadingSupport.kt:486)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:390)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:259)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: codeActions/provide: document not found for file:///Users/boris/DevEnvs/ProBidder/probidder/fls/www/karadjata/date-check.php

Error: codeActions/provide: document not found for file:///Users/boris/DevEnvs/ProBidder/probidder/fls/www/karadjata/date-check.php
    at /Users/boris/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:134957:19
    at /Users/boris/Library/Application Support/JetBrains/PhpStorm2024.2/plugins/Sourcegraph/agent/index.js:135868:18
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:449:9)
    ...

**Comment by mkondratek** [comment]
Hi there 👋 sorry for the inconvenience 🙇 we know about that problem and we fixed it already!

The original issue: https://github.com/sourcegraph/jetbrains/issues/2512
The fix: https://github.com/sourcegraph/jetbrains/pull/2539

The fix will be included in the next release. The next release should be available next week. 
I kindly ask you for some more patience 🙏
