### ISSUE TITLE
bug: java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, o...

### ISSUE THREAD

**Issue by luokuning** [sourcegraph/jetbrains#2614]
### IDE Information

WebStorm 2024.3 RC
Build #WS-243.21565.120, built on November 7, 2024
Licensed to K L
Subscription is active until October 11, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
  eslint.additional.file.extensions=svelte
Non-Bundled Plugins:
  com.fwdekker.randomness (3.3.3)
  club.nutsoft.Github3Theme (1.2.2)
  com.hiberbee.intellij.hiberbee-theme (2024.2.28.2100)
  com.vermouthx.idea (1.16.0)
  org.toml.lang (243.21565.122)
  com.intellij.ideolog (243.21565.133)
  String Manipulation (9.14.1)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.yemreak.DarkCode-Theme (1.1)
  com.intellij.kubernetes (243.21565.136)
  ru.adelf.idea.dotenv (2024.3)
  org.jetbrains.plugins.gitlab (243.21565.122)
  org.jetbrains.plugins.github (243.21565.122-ultimate)
  com.github.aleksandrsl.intellijbrowserslist (1.0.2)
  com.intellij.lang.jsgraphql (243.21565.122)
  dev.blachut.svelte.lang (243.21565.120)
  mdx.js (243.21565.120)
  deno (243.21565.120)
  com.sourcegraph.jetbrains (7.0.18)
  mobi.hsz.idea.gitignore (4.5.4)
  com.blai30.lotus.theme (1.12)
  izhangzhihao.rainbow.brackets (2024.2.6-241)

### Bug Description

I was using code completion the first time, and this error popped up.

### Additional context

Stacktrace:
```text
java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking. 
	at com.intellij.openapi.progress.CoroutinesKt.assertBackgroundThreadOrWriteAction(coroutines.kt:473)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:139)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingMaybeCancellable(coroutines.kt:176)
	at com.intellij.lang.javascript.service.JSLanguageServiceUtilKt.lockCancellable(JSLanguageServiceUtil.kt:38)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.lockCacheCancellable$lambda$19(JSLanguageServiceQueueImpl.kt:338)
	at com.intellij.lang.javascript.service.JSLanguageServiceTracerUtilKt.withTraceSpan(JSLanguageServiceTracerUtil.kt:15)
	at com.intellij.lang.javascript.service.JSLanguageServiceTracerUtilKt.withTraceSpan$default(JSLanguageServiceTracerUtil.kt:13)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.lockCacheCancellable(JSLanguageServiceQueueImpl.kt:337)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.executeBlocking(JSLanguageServiceQueueImpl.kt:169)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.execute(JSLanguageServiceQueueImpl.kt:64)
	at com.intellij.lang.javascript.service.JSLanguageServiceBase.sendCommand(JSLanguageServiceBase.kt:28)
	at com.intellij.lang.javascript.service.JSLanguageServiceFileCommandCache.calculateWithCache(JSLanguageServiceFileCommandCache.kt:51)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFixSet.calcAndUpdateState(TypeScriptLanguageServiceFixSet.java:107)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFixSet.refresh(TypeScriptLanguageServiceFixSet.java:94)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFixSet.lambda$new$1(TypeScriptLanguageServiceFixSet.java:67)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFix.getText(TypeScriptLanguageServiceFix.java:112)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFix.getFamilyName(TypeScriptLanguageServiceFix.java:123)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doApplyInformationToEditor$lambda$4(CodyFixHighlightPass.kt:110)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doApplyInformationToEditor$lambda$5(CodyFixHighlightPass.kt:110)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.lambda$unregisterQuickFix$2(HighlightInfo.java:1012)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1031)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1006)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.unregisterQuickFix(HighlightInfo.java:1012)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doApplyInformationToEditor(CodyFixHighlightPass.kt:110)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:116)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$2(PassExecutorService.java:512)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16...

**Comment by dominiccooney** [comment]
Merging this into BUGS-729 / #2614
