### ISSUE TITLE
bug: com.intellij.util.IncorrectOperationException: Sorry but parent: Problems View (class com.intellij.openapi.util.Disposer$2) h...

### ISSUE THREAD

**Issue by snacsnoc** [sourcegraph/jetbrains#2679]
### IDE Information

PyCharm 2024.3 (Professional Edition)
Build #PY-243.21565.199, built on November 13, 2024
Licensed to Easton E
Subscription is active until December 2, 2024.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.7.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  documentation.show.toolbar=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.vermouthx.xcode-theme (1.7.0)
  com.jetbrains.space (243.21565.122)
  com.hiberbee.intellij.hiberbee-theme (2024.2.28.2100)
  com.markskelton.one-dark-theme (5.12.0)
  intellij-micropython (2.0.0.pre-alpha10-2024.3)
  name.kropp.intellij.makefile (243.21565.122)
  net.antelle.intellij-xcode-dark-theme (1.2.4)
  com.intellij.mermaid (0.0.24+IJ.243)
  com.github.gitofleonardo.simplesqlitebrowser (1.0.7)
  nl.jusx.pycharm.lineprofiler (1.8.0)
  com.dropbox.plugins.mypy_plugin (0.3.2)
  net.ashald.envfile (3.4.2)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  com.intellij.lang.jsgraphql (243.21565.122)
  com.sourcegraph.jetbrains (7.1.0)

### Bug Description

Opening PyCharm

### Additional context

Stacktrace:
```text
com.intellij.util.IncorrectOperationException: Sorry but parent: Problems View (class com.intellij.openapi.util.Disposer$2) has already been disposed (see the cause for stacktrace) so the child: com.intellij.openapi.wm.impl.content.ToolWindowContentUi$2@1a3e70d4 (class com.intellij.openapi.wm.impl.content.ToolWindowContentUi$2) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:156)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.<init>(ToolWindowContentUi.java:203)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentManager$lambda$4(ToolWindowImpl.kt:190)
	at com.intellij.ui.content.impl.ContentManagerImpl.<init>(ContentManagerImpl.java:80)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentManager(ToolWindowImpl.kt:188)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.contentManager$lambda$2(ToolWindowImpl.kt:134)
	at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
	at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
	at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.ensureContentManagerInitialized(ToolWindowImpl.kt:663)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:687)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:550)
	at com.sourcegraph.cody.error.CodyConsole._init_$lambda$3(CodyConsole.kt:42)
	at com.intellij.openapi.application.ActionsKt.invokeLater$lambda$5(actions.kt:60)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(...

**Comment by PriNova** [comment]
Thank you for reporting the issue.

**Comment by mkondratek** [comment]
The issue has been identified and fix but the fix has not been yet publicly released. Hopefully it will be **7.76.0**. It should be available soon. 

I kindly ask you for some more patience 🙏
