### ISSUE TITLE
bug: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentServi...

### ISSUE THREAD

**Issue by bilalsagheer13** [sourcegraph/jetbrains#2684]
### IDE Information

PhpStorm 2023.2
Build #PS-232.8660.205, built on July 28, 2023
Licensed to menorah parapet
You have a perpetual fallback license for this version.
Subscription is active until September 14, 2026.
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Cores: 8
Registry:
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.ssh.tool (2023.1.9)
    com.xiaobaicai.ChatGPTCoding (2024.7.9)
    LJYXP.ColorBrackets (2024.6.1.4)
    com.intellij.ideolog (222.3.2.0)
    ru.adelf.idea.dotenv (2024.2.1)
    com.laravel_idea.tailwind (1.4.2)
    izhangzhihao.rainbow.brackets (2023.3.7)
    com.laravel_idea.plugin (8.4.0.232)
    com.zhengfei.aicoding (2023.5.16)
    com.sourcegraph.jetbrains (7.0.18)

### Bug Description

this message shows me again and again i don't know why!!

### Additional context

Stacktrace:
```text
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=sales-and-pos, containerState=DISPOSE_COMPLETED, componentStore=C:\xampp\htdocs\Jaldi\sales-and-pos) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:752)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:732)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getInstance(CodyAgentService.kt:227)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.withAgent$lambda$2(CodyAgentService.kt:191)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by PriNova** [comment]
Duplicate of #2613
