### ISSUE TITLE
bug: java.lang.AssertionError: Illegal char <<> at index 0: <2458a31f-8020-42ee-aa75-2d1d23e6fedc>/public/.htaccess

### ISSUE THREAD

**Issue by xblabs** [sourcegraph/jetbrains#2696]
### IDE Information

PhpStorm 2024.3.1 Preview
Build #PS-243.22562.9, built on November 19, 2024
Licensed to 
Subscription is active until September 12, 2025.
Runtime version: 21.0.5+8-b631.19 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 17008M
Cores: 4
Registry:
  debugger.watches.in.variables=false
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  i18n.locale=
  typescript.service.completion.enabled=[true|conservative*|false]
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  com.jetbrains.gerryPurpleTheme (2024.1.1030)
  com.markskelton.one-dark-theme (5.12.0)
  com.intellij.properties (243.22562.9)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.intellij.ml.llm (243.22562.23)
  dev.blachut.svelte.lang (243.22562.13)
  com.niclas-van-eyk.laravel-make-integration (2.3.5)
  com.kalessil.phpStorm.phpInspectionsEA (5.1.0)
  lv.midiana.misc.phpstorm-plugins.deep-keys (2022.08.03.001)
  ru.adelf.idea.dotenv (2024.3)
  net.king2500.plugins.PhpAdvancedAutoComplete (1.1.0)
  com.laravel_idea.plugin (9.0.0.243)
  dev.ekvedaras.laravelquery (4.0.4)
  com.github.copilot (1.5.29.7524)
  com.sourcegraph.jetbrains (7.3.2)
  mobi.hsz.idea.gitignore (4.5.4)
  de.espend.idea.php.phpunit (7.1)

### Bug Description

Can not edit remote files. Can not place cursor or type anything in the file, After multiple keypresses random keystrokes are placed in the file ( 1 char out of 20 strokes is placed, but never where intended, but around the cursor ) . Space, Backspace does not work at all

### Additional context

Stacktrace:
```text
java.lang.AssertionError: Illegal char <<> at index 0: <2458a31f-8020-42ee-aa75-2d1d23e6fedc>/public/.htaccess
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:82)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:436)
	at com.intellij.util.EventDispatcher.throwExceptions(EventDispatcher.java:170)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:128)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy155.selectionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.broadcastSelectionEvent(SelectionModelImpl.java:81)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.fireSelectionChanged(SelectionModelImpl.java:75)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1176)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:413)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1086)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1076)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1068)
	at com.intellij.openapi.editor.SelectionModel.setSelection(SelectionModel.java:180)
	at com.intellij.openapi.editor.impl.EditorImpl.setSelectionAndBlockActions(EditorImpl.java:2988)
	at com.intellij.openapi.editor.impl.EditorImpl.processMouseDragged(EditorImpl.java:2818)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$new$0(EditorImpl.java:276)
	at com.intellij.ide.ui.laf.MouseDragSelectionEventHandler.mouseDragged(MouseDragSelectionEventHandler.kt:14)
	at com.intellij.openapi.editor.impl.EditorImpl.lambda$runMouseDraggedCommand$64(EditorImpl.java:2645)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.impl.EditorImpl.runMouseDraggedCommand(EditorImpl.java:2645)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.lambda$mouseDragged$0(EditorImpl.java:4913)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:98)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseMotionListener.mouseDragged(EditorImpl.java:4913)
	at java.desktop/java.awt.Component.processMouseMotionEvent(Component.java:6710)
	at java.desktop/javax.swing.JComponent.processMouseMotionEvent(JComponent.java:3412)
	at java.desktop/java.awt.Component.processEvent(Component.java:6431)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4594)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteInte...

**Comment by PriNova** [comment]
Sorry for the late reply. The team will have a look at it. Thank you
