### ISSUE TITLE
bug: java.lang.IllegalArgumentException: Invalid range specified: (10106, 10053); 

### ISSUE THREAD

**Issue by lzrf0cuz** [sourcegraph/jetbrains#2719]
### IDE Information

GoLand 2024.3
Build #GO-243.21565.208, built on November 14, 2024
Licensed to XXXXX
You have a perpetual fallback license for this version.
Subscription is active until November 23, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=6272a4
  editor.focus.mode.color.dark=6272a4
  debugger.valueTooltipAutoShowOnSelection=true
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  ide.completion.variant.limit=500
  suggest.all.run.configurations.from.context=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  i18n.locale=
  ide.images.show.chessboard=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.tasks (243.21565.122)
  com.fwdekker.randomness (3.3.3)
  Scratch (1.13)
  org.intellij.plugins.hcl (243.21565.180)
  com.nasller.CodeGlancePro (1.9.4)
  aws.toolkit.core (3.42-243)
  com.jetbrains.space (243.21565.122)
  lermitage.ij.all.pack (2024.12.2)
  com.ultrahob.zerolength.plugin (0.95)
  cat.dcat.jbplug.mactabbing (1.1.0)
  dev.willebrands.intellij.sloppyfocus (0.9.2)
  org.turbanov.run.configuration.as.action (3.0)
  PythonCore (243.21565.211)
  dev.turingcomplete.intellijdevelopertoolsplugins (6.0.1)
  org.toml.lang (243.21565.122)
  com.sburlyaev.terminal.plugin (0.8.0)
  com.crunch42.openapi (1.94)
  String Manipulation (9.15.0)
  Key Promoter X (2024.2.2)
  com.intellij.mermaid (0.0.24+IJ.243)
  AceJump (3.8.19)
  DuplicateLines (1.0.1)
  com.wakatime.intellij.plugin (15.0.3)
  com.schwarzit.spectral-intellij-plugin (3.0.1)
  GrepConsole (13.2.0-IJ2023.3)
  com.chylex.intellij.inspectionlens (1.4.1)
  com.dsoftware.ghtoolbar (2024.2.14)
  izhangzhihao.rainbow.brackets (2024.2.7-241)
  com.intellij.lang.jsgraphql (243.21565.122)
  intellij.prettierJS (243.21565.122)
  com.sourcegraph.jetbrains (7.3.2)
  com.mallowigi (97.0.0)
  com.chrisrm.idea.MaterialThemeUI (9.7.0)
  net.ashald.envfile (3.4.2)
  pro.bashsupport (4.5.0.243)
  ru.adelf.idea.dotenv (2024.3)
  aws.toolkit (3.42-243)

### Bug Description

The plugin keeps crashing constantly.

### Additional context

Stacktrace:
```text
java.lang.IllegalArgumentException: Invalid range specified: (10106, 10053); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:288)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:283)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:279)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:42)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:31)
	at com.intellij.openapi.util.TextRange.create(TextRange.java:199)
	at com.sourcegraph.utils.CodyEditorUtil.getTextRange(CodyEditorUtil.kt:65)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.displayAgentAutocomplete(CodyAutocompleteManager.kt:239)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult$lambda$10$lambda$9(CodyAutocompleteManager.kt:215)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:341)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:147)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction$lambda$5(AnyThreadWriteThreadingSupport.kt:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:389)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:896)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:145)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:154)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:121)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:341)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:329)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult$lambda$10(CodyAutocompleteManager.kt:214)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue...

**Comment by mkondratek** [comment]
Hello @lzrf0cuz  👋 thanks for the report. Sorry for the late reply on it.

Do you have any leads on it? Is there anything specific you do so this error appears? Is it writing in some specific window/dialog? Or maybe something specific about the file you are modifing?
