### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid range specified: (820, 759)

### ISSUE THREAD

**Issue by Nopik** [sourcegraph/jetbrains#2818]
### IDE Information

Latest idea, cody 7.5.1-nightly

### Bug Description

The bug report is too long to be parsed by github. The url:

https://github.com/sourcegraph/jetbrains/issues/new?template=bug_report.yml&labels=bug,repo/jetbrains&projects=sourcegraph/381&title=bug%3A+java.lang.IllegalArgumentException%3A+Invalid+range+specified%3A+%28830%2C+759%29%3B+&about=IntelliJ+IDEA+2024.3+%28Ultimate+Edition%29%0ABuild+%23IU-243.21565.193%2C+built+on+November+13%2C+2024%0ALicensed+to+Kamil+Burzynski%0ASubscription+is+active+until+October+6%2C+2025.%0ARuntime+version%3A+21.0.5%2B8-b631.16+aarch64+%28JCEF+122.1.9%29%0AVM%3A+OpenJDK+64-Bit+Server+VM+by+JetBrains+s.r.o.%0AToolkit%3A+sun.lwawt.macosx.LWCToolkit%0AmacOS+14.6.1%0AGC%3A+G1+Young+Generation%2C+G1+Concurrent+GC%2C+G1+Old+Generation%0AMemory%3A+16384M%0ACores%3A+10%0AMetal+Rendering+is+ON%0ARegistry%3A%0A++actionSystem.playback.typecommand.delay%3D50%0A++debugger.new.tool.window.layout%3Dtrue%0A++vcs.log.index.enable%3Dtrue%0A++ide.experimental.ui%3Dtrue%0A++i18n.locale%3D%0A++terminal.new.ui%3Dtrue%0A++typescript.service.node.arguments%3D--max-old-space-size%3D8192%0A++editor.minimap.enabled%3Dtrue%0ANon-Bundled+Plugins%3A%0A++String+Manipulation+%289.15.0%29%0A++com.wakatime.intellij.plugin+%2815.0.3%29%0A++PlantUML+integration+%287.11.2-IJ2023.2%29%0A++org.jetbrains.plugins.github+%28243.21565.204-ultimate%29%0A++com.sourcegraph.jetbrains+%287.5.1-nightly%29%0A++Dart+%28243.23177%29%0A++commit-prefix-plugin+%281.4.1%29%0A++ru.adelf.idea.dotenv+%282024.3%29%0A++com.eny.i18n+%282.6.2%29%0AKotlin%3A+243.21565.193-IJ%0A&logs=Stacktrace%3A%0A%60%60%60text%0Ajava.lang.IllegalArgumentException%3A+Invalid+range+specified%3A+%28830%2C+759%29%3B+%0A%09at+com.intellij.openapi.util.TextRange.assertProperRange%28TextRange.java%3A288%29%0A%09at+com.intellij.openapi.util.TextRange.assertProperRange%28TextRange.java%3A283%29%0A%09at+com.intellij.openapi.util.TextRange.assertProperRange%28TextRange.java%3A279%29%0A%09at+com.intellij.openapi.util.TextRange.%3Cinit%3E%28TextRange.java%3A42%29%0A%09at+com.intellij.openapi.util.TextRange.%3Cinit%3E%28TextRange.java%3A31%29%0A%09at+com.intellij.openapi.util.TextRange.create%28TextRange.java%3A199%29%0A%09at+com.sourcegraph.utils.CodyEditorUtil.getTextRange%28CodyEditorUtil.kt%3A65%29%0A%09at+com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.displayAgentAutocomplete%28CodyAutocompleteManager.kt%3A243%29%0A%09at+com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult%24lambda%2410%24lambda%249%28CodyAutocompleteManager.kt%3A219%29%0A%09at+com.intellij.openapi.command.WriteCommandAction.lambda%24runWriteCommandAction%244%28WriteCommandAction.java%3A341%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.lambda%24doRunWriteCommandAction%241%28WriteCommandAction.java%3A147%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%24lambda%245%28AnyThreadWriteThreadingSupport.kt%3A379%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%28AnyThreadWriteThreadingSupport.kt%3A389%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction%28AnyThreadWriteThreadingSupport.kt%3A379%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction%28ApplicationImpl.java%3A896%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.lambda%24doRunWriteCommandAction%242%28WriteCommandAction.java%3A145%29%0A%09at+com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand%28CoreCommandProcessor.java%3A226%29%0A%09at+com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand%28CoreCommandProcessor.java%3A188%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.doRunWriteCommandAction%28WriteCommandAction.java%3A154%29%0A%09at+com.intellij.openapi.command.WriteCommandAction%24BuilderImpl.run%28WriteCommandAction.java%3A121%29%0A%09at+com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction%28WriteCommandAction.java%3A341%29%0A%09at+com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction%28WriteCommandAction.java%3A329%29%0A%09at+com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult%24lambda%2410%28CodyAutocompleteManager.kt%3A218%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed%28TransactionGuardImpl.java%3A236%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl.access%24100%28TransactionGuardImpl.java%3A25%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl%241.run%28TransactionGuardImpl.java%3A198%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread%24lambda%242%28AnyThreadWriteThreadingSupport.kt%3A217%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction%28AnyThreadWriteThreadingSupport.kt%3A128%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread%28AnyThreadWriteThreadingSupport.kt%3A216%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread%28ApplicationImpl.java%3A842%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl%242.run%28ApplicationImpl.java%3A421%29%0A%09at+com.intellij.util.concurrency.ChildContext%24runInChildContext%241.invoke%28propagation.kt%3A101%29%0A%09at+com.intellij.util.concurrency.ChildContext%24runInChildContext%241.invoke%28propagation.kt%3A101%29%0A%09at+com.intellij.util.concurrency.ChildContext.runInChildContext%28propagation.kt%3A107%29%0A%09at+com.intellij.util.concurrency.ChildContext.runInChildContext%28propagation.kt%3A101%29%0A%09at+com.intellij.util.concurrency.ContextRunnable.run%28ContextRunnable.java%3A27%29%0A%09at+com.intellij.openapi.application.impl.FlushQueue.runNextEvent%28FlushQueue.java%3A117%29%0A%09at+com.intellij.openapi.application.impl.FlushQueue.flushNow%28FlushQueue.java%3A43%29%0A%09at+java.desktop%2Fjava.awt.event.InvocationEvent.dispatch%28InvocationEvent.java%3A318%29%0A%09at+java.desktop%2Fjava.awt.EventQueue.dispatchEventImpl%28EventQueue.java%3A781%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%244.run%28EventQueue.java%3A728%29%0A%09at+java.desktop%2Fjava.awt.EventQueue%244.run%28EventQueue.java%3A722%29%0A%09at+java.base%2Fjava.security.AccessController.doPrivileged%28AccessController.java%3A400%29%0A%09at+java.base%2Fjava.security.ProtectionDomain%24JavaSecurityAccessImpl.doIntersectionPrivilege%28ProtectionDomain.java%3A87%29%0A%09at+java.desktop%2Fjava.awt.EventQueue.dispatchEvent%28EventQueue.java%3A750%29%0A%09at+com.intellij.ide.IdeEventQueue.defaultDispatchEvent%28IdeEventQueue.kt%3A675%29%0A%09at+com.intellij.ide.IdeEventQueue._dispatchEvent%28IdeEventQueue.kt%3A573%29%0A%09at+com.intellij.ide.IdeEventQueue.dispatchEvent%24lambda%2418%24lambda%2417%24lambda%2416%24lambda%2415%28IdeEventQueue.kt%3A355%29%0A%09at+com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized%28CoreProgressManager.java%3A857%29%0A%09at+com.intellij.ide.IdeEventQueue.dispatchEvent%24lambda%2418%24lambda%2417%24lambda%2416%28IdeEventQueue.kt%3A354%29%0A%09at+com.intellij.ide.IdeEventQueueKt.performActivity%24lambda%242%24lambda%241%28IdeEventQueue.kt%3A1045%29%0A%09at+com.intellij.openapi.application.WriteIntentReadAction.lambda%24run%240%28WriteIntentReadAction.java%3A24%29%0A%09at+com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction%28AnyThreadWriteThreadingSupport.kt%3A128%29%0A%09at+com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction%28ApplicationImpl.java%3A916%29%0A%09at+com.intellij.openapi.application.WriteIntentReadAction.compute%28WriteIntentReadAction.java%3A55%29%0A%09at+com.intellij.openapi.application.WriteIntentReadAction.run%28WriteIntentReadAction.java%3A23%29%0A%09at+com.intellij.ide.IdeEventQueueKt.performActivity%24lambda%242%28IdeEventQueue.kt%3A1045%29%0A%09at+com.intellij.ide.IdeEventQueueKt.performActivity%24lambda%243%28IdeEventQueue.kt%3A1054%29%0A%09at+com.intellij.openapi.application.TransactionGuardImpl.performActivity%28TransactionGuardImpl.java%...

### Additional context

Message displayed by Idea:

java.lang.IllegalArgumentException: Invalid range specified: (820, 759); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:288)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:283)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:279)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:42)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:31)
	at com.intellij.openapi.util.TextRange.create(TextRange.java:199)
	at com.sourcegraph.utils.CodyEditorUtil.getTextRange(CodyEditorUtil.kt:65)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.displayAgentAutocomplete(CodyAutocompleteManager.kt:243)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult$lambda$10$lambda$9(CodyAutocompleteManager.kt:219)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$4(WriteCommandAction.java:341)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:147)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction$lambda$5(AnyThreadWriteThreadingSupport.kt:379)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:389)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteAction(AnyThreadWriteThreadingSupport.kt:379)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:896)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:145)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:154)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:121)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:341)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:329)
	at com.sourcegraph.cody.autocomplete.CodyAutocompleteManager.processAutocompleteResult$lambda$10(CodyAutocompleteManager.kt:218)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by PriNova** [comment]
Sorry for the late reply.
The team is aware of that issue and we are working on it.

Thank you.
