### ISSUE TITLE
bug: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by Flaxoos** [sourcegraph/jetbrains#2873]
### IDE Information

IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Licensed to Ido Flasch
Subscription is active until January 13, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1.1
Kotlin analyzer version: 2.1.20-dev-1411
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 30000M
Cores: 10
Metal Rendering is ON
Registry:
  run.processes.with.pty=false
  ide.experimental.ui=true
  idea.ignore.disabled.plugins=true
  i18n.locale=
  org.toml.json.schema=false
Non-Bundled Plugins:
  com.google.ide-perf (1.3.2)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  org.turbanov.run.configuration.as.action (3.0)
  com.github.lppedd.idea-conventional-commit (0.23.1)
  org.jetbrains.jumpToLine (0.1.17)
  org.jetbrains.idea.grammar (2022.3.2)
  com.codeium.intellij (1.30.6)
  String Manipulation (9.14.1)
  org.jetbrains.plugins.hocon (2024.2.0)
  com.shuzijun.markdown-editor (2.0.5)
  org.intellij.RegexpTester (2.2.0)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  com.intellij.exposed (243.21565.129)
  com.suusan2go.kotlin-fill-class (1.0.23)
  com.godwin.kdocer (1.6)
  kotest-plugin-intellij (1.3.86-243-EAP-SNAPSHOT)
  com.squareup.sqldelight (2.0.2)
  com.nbadal.ktlint (0.25.0)
  com.sourcegraph.jetbrains (7.5.6)
  com.jetbrains.hackathon.indices.viewer (1.29)
Kotlin: 243.21565.193-IJ

### Bug Description

this error appears

### Additional context

Stacktrace:
```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:128)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:95)
	at com.sourcegraph.cody.auth.CodyAccount$Companion.getActiveAccount(CodyAccount.kt:40)
	at com.sourcegraph.cody.auth.CodyAccount$Companion.hasActiveAccount(CodyAccount.kt:30)
	at com.sourcegraph.cody.listeners.CodySelectionInlayManager.handleSelectionChanged(CodySelectionInlayManager.kt:40)
	at com.sourcegraph.cody.listeners.CodySelectionListener.selectionChanged(CodySelectionListener.kt:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy134.selectionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.broadcastSelectionEvent(SelectionModelImpl.java:81)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.fireSelectionChanged(SelectionModelImpl.java:75)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$doSetSelection$6(CaretImpl.java:1176)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:413)
	at com.intellij.openapi.editor.impl.CaretImpl.doSetSelection(CaretImpl.java:1086)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1049)
	at com.intellij.openapi.editor.impl.CaretImpl.setSelection(CaretImpl.java:1044)
	at com.intellij.openapi.editor.SelectionModel.setSelection(SelectionModel.java:150)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.processMousePressed(EditorImpl.java:4648)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.lambda$runMousePressedCommand$0(EditorImpl.java:4376)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:226)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMousePressedCommand(EditorImpl.java:4381)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mousePressed(EditorImpl.java:4295)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6659)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at java.desktop/java.awt.Component.processEvent(Component.java:6427)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4574)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction....

**Comment by PriNova** [comment]
Sorry for the late reply and thank you for reporting this issue.

**Comment by pkukielka** [comment]
Fixed by https://github.com/sourcegraph/cody/pull/6558
