### ISSUE TITLE
bug: java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.

### ISSUE THREAD

**Issue by Flaxoos** [sourcegraph/jetbrains#2875]
### IDE Information

IntelliJ IDEA 2024.3 (Ultimate Edition)
Build #IU-243.21565.193, built on November 13, 2024
Licensed to Ido Flasch
Subscription is active until January 13, 2025.
Runtime version: 21.0.5+8-b631.16 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.1.1
Kotlin analyzer version: 2.1.20-dev-1411
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 30000M
Cores: 10
Metal Rendering is ON
Registry:
  run.processes.with.pty=false
  ide.experimental.ui=true
  idea.ignore.disabled.plugins=true
  i18n.locale=
  org.toml.json.schema=false
Non-Bundled Plugins:
  com.google.ide-perf (1.3.2)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  org.turbanov.run.configuration.as.action (3.0)
  com.github.lppedd.idea-conventional-commit (0.23.1)
  PythonCore (243.21565.211)
  org.jetbrains.jumpToLine (0.1.17)
  org.jetbrains.idea.grammar (2022.3.2)
  com.codeium.intellij (1.30.6)
  String Manipulation (9.14.1)
  org.jetbrains.plugins.hocon (2024.2.0)
  com.shuzijun.markdown-editor (2.0.5)
  org.intellij.RegexpTester (2.2.0)
  org.jetbrains.plugins.gitlab (243.21565.204)
  org.jetbrains.plugins.github (243.21565.204-ultimate)
  com.intellij.exposed (243.21565.129)
  com.suusan2go.kotlin-fill-class (1.0.23)
  com.godwin.kdocer (1.6)
  kotest-plugin-intellij (1.3.86-243-EAP-SNAPSHOT)
  com.squareup.sqldelight (2.0.2)
  com.nbadal.ktlint (0.25.0)
  com.sourcegraph.jetbrains (7.5.6)
  com.jetbrains.hackathon.indices.viewer (1.29)
Kotlin: 243.21565.193-IJ

### Bug Description

Got error in plugin

### Additional context

Stacktrace:
```text
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:128)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:95)
	at com.sourcegraph.cody.auth.CodyAccount$Companion.getActiveAccount(CodyAccount.kt:40)
	at com.sourcegraph.cody.auth.CodyAccount$Companion.hasActiveAccount(CodyAccount.kt:30)
	at com.sourcegraph.cody.listeners.CodySelectionInlayManager.handleSelectionChanged(CodySelectionInlayManager.kt:40)
	at com.sourcegraph.cody.listeners.CodySelectionListener.selectionChanged(CodySelectionListener.kt:31)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy133.selectionChanged(Unknown Source)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.broadcastSelectionEvent(SelectionModelImpl.java:81)
	at com.intellij.openapi.editor.impl.SelectionModelImpl.fireSelectionChanged(SelectionModelImpl.java:75)
	at com.intellij.openapi.editor.impl.CaretImpl.lambda$removeSelection$7(CaretImpl.java:1203)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:413)
	at com.intellij.openapi.editor.impl.CaretImpl.removeSelection(CaretImpl.java:1193)
	at com.intellij.openapi.editor.SelectionModel.removeSelection(SelectionModel.java:197)
	at com.intellij.openapi.editor.SelectionModel.removeSelection(SelectionModel.java:188)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateInEditor(OpenFileDescriptor.java:120)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigateIn(OpenFileDescriptor.java:98)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.navigateTo(TextEditorImpl.kt:200)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImplKt.navigateAndSelectEditor(FileEditorManagerImpl.kt:2477)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.kt:1421)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.kt:1386)
	at com.intellij.openapi.fileEditor.FileNavigatorImplKt.navigateInAnyFileEditor(FileNavigatorImpl.kt:120)
	at com.intellij.openapi.fileEditor.FileNavigatorImplKt.access$navigateInAnyFileEditor(FileNavigatorImpl.kt:1)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.kt:59)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.kt:54)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.kt:36)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:89)
	at com.intellij.build.FileNavigatable.navigate(FileNavigatable.java:41)
	at com.intellij.build.BuildTreeConsoleView.lambda$showErrorIfFirst$10(BuildTreeConsoleView.java:547)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue._...

**Comment by PriNova** [comment]
Duplicate of #2873
