### ISSUE TITLE
bug: java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, o...

### ISSUE THREAD

**Issue by kuuumo** [sourcegraph/jetbrains#2903]
### IDE Information

IntelliJ IDEA 2024.3.1.1 (Ultimate Edition)
Build #IU-243.22562.218, built on December 18, 2024
Licensed to Hayato Sugita
Subscription is active until July 9, 2025.
Runtime version: 21.0.5+8-b631.28 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.3
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.ml.llm (243.22562.251.6)
  name.kropp.intellij.makefile (243.21565.122)
  IdeaVIM (2.17.0)
  com.jetbrains.plugins.ini4idea (243.22562.236)
  org.jetbrains.plugins.go (243.22562.218)
  org.jetbrains.plugins.ruby (243.22562.218)
  com.intellij.grazie.pro (0.3.354)
  com.intellij.plugins.watcher (242.20224.155)
  org.jetbrains.plugins.stylus (243.21565.120)
  awesome.console (0.1337.12)
  lechuck.intellij-plugin.task (1.5.0)
  krasa.CpuUsageIndicator (1.18.0-IJ2023)
  Pythonid (243.22562.218)
  PythonCore (243.22562.145)
  GrepConsole (13.2.0-IJ2023.3)
  com.intellij.mermaid (0.0.24+IJ.243)
  com.github.yunabraska.githubworkflowplugin (2024.2.0)
  net.seesharpsoft.intellij.plugins.csv (4.0.1)
  com.dsoftware.ghtoolbar (2024.3.3)
  String Manipulation (9.15.0)
  com.github.shiraji.findpullrequest (2.0.4)
  mobi.hsz.idea.gitignore (4.5.4)
  com.sourcegraph.jetbrains (7.8.0-nightly)
  uk.co.ben-gibson.remote.repository.mapper (4.5.2)
  com.jetbrains.plugins.jade (243.21565.129)
  io.plugin.tsnode (2024.08.16-1)
  com.eny.i18n (2.6.2)
  com.jetbrains.twig (243.22562.236)
  izhangzhihao.rainbow.brackets (2024.2.8-241)
  com.github.copilot (1.5.30.8390-242-nightly)
  com.ppolivka.plugin.gitcleaner (1.1.4)
  zielu.gittoolbox (600.0.11+243)
  cn.yiiguxing.plugin.translate (3.6.8)
  ru.adelf.idea.dotenv (2024.3)
Kotlin: 243.22562.218-IJ

### Bug Description

bug: java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, o...

### Additional context

Stacktrace:
```text
java.lang.IllegalStateException: This method is forbidden on EDT because it does not pump the event queue. Switch to a BGT, or use com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking. 
	at com.intellij.openapi.progress.CoroutinesKt.assertBackgroundThreadOrWriteAction(coroutines.kt:473)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:139)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingMaybeCancellable(coroutines.kt:176)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.lockCacheCancellable$lambda$26(JSLanguageServiceQueueImpl.kt:542)
	at com.intellij.lang.javascript.service.JSLanguageServiceTracerUtilKt.withServiceTraceSpan(JSLanguageServiceTracerUtil.kt:42)
	at com.intellij.lang.javascript.service.JSLanguageServiceTracerUtilKt.withServiceTraceSpan$default(JSLanguageServiceTracerUtil.kt:39)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.lockCacheCancellable(JSLanguageServiceQueueImpl.kt:534)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.executeBlocking(JSLanguageServiceQueueImpl.kt:349)
	at com.intellij.lang.javascript.service.JSLanguageServiceQueueImpl.execute(JSLanguageServiceQueueImpl.kt:243)
	at com.intellij.lang.javascript.service.JSLanguageServiceBase.sendCommand(JSLanguageServiceBase.kt:28)
	at com.intellij.lang.javascript.service.JSLanguageServiceFileCommandCache.calculateWithCache(JSLanguageServiceFileCommandCache.kt:51)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFixSet.calcAndUpdateState(TypeScriptLanguageServiceFixSet.java:107)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFixSet.refresh(TypeScriptLanguageServiceFixSet.java:94)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFixSet.lambda$new$1(TypeScriptLanguageServiceFixSet.java:67)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFix.getText(TypeScriptLanguageServiceFix.java:112)
	at com.intellij.lang.typescript.compiler.languageService.codeFixes.TypeScriptLanguageServiceFix.getFamilyName(TypeScriptLanguageServiceFix.java:123)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doApplyInformationToEditor$lambda$4(CodyFixHighlightPass.kt:118)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doApplyInformationToEditor$lambda$5(CodyFixHighlightPass.kt:118)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.lambda$unregisterQuickFix$2(HighlightInfo.java:1012)
	at com.intellij.util.containers.ContainerUtil.findAll(ContainerUtil.java:1031)
	at com.intellij.util.containers.ContainerUtil.filter(ContainerUtil.java:1006)
	at com.intellij.codeInsight.daemon.impl.HighlightInfo.unregisterQuickFix(HighlightInfo.java:1012)
	at com.sourcegraph.cody.inspections.CodyFixHighlightPass.doApplyInformationToEditor(CodyFixHighlightPass.kt:118)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.applyInformationToEditor(TextEditorHighlightingPass.java:116)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService.lambda$applyInformationToEditorsLater$2(PassExecutorService.java:512)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread$lambda$2(AnyThreadWriteThreadingSupport.kt:217)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runIntendedWriteActionOnCurrentThread(AnyThreadWriteThreadingSupport.kt:216)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:842)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:421)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessControlle...

**Comment by PriNova** [comment]
Thank you for reporting this issue. It is a duplicate of [https://github.com/sourcegraph/jetbrains/issues/2869](https://github.com/sourcegraph/jetbrains/issues/2869)

**Comment by kuuumo** [comment]
Sorry about that.I'm going to have to close this one.

**Comment by PriNova** [comment]
No sorry. We track them automatically. Sorry for the inconvenience.
