### ISSUE TITLE
bug: java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"-280871737","projectHash":"c570587e","ranges":[{"exclusiveRef":"master","inclusiveRef":"production"}],"roots":[{"path":"C:/Users/eandr/Projects/Existlive/web-frontend"}]}

### ISSUE THREAD

**Issue by ceearrashee** [sourcegraph/jetbrains#342]
Plugin version: ```5.2.20102-nightly```
IDE version: ```GO-233.13135.104```
Exception: ```java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"-280871737","projectHash":"c570587e","ranges":[{"exclusiveRef":"master","inclusiveRef":"production"}],"roots":[{"path":"C:/Users/eandr/Projects/Existlive/web-frontend"}]}```
Stacktrace:
```text
java.nio.file.InvalidPathException: Illegal char <"> at index 1: {"sessionId":"-280871737","projectHash":"c570587e","ranges":[{"exclusiveRef":"master","inclusiveRef":"production"}],"roots":[{"path":"C:/Users/eandr/Projects/Existlive/web-frontend"}]}
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt:18)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath$default(TextDocument.kt:17)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.agent.protocol.TextDocument.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.CodyFileEditorListener.lambda$fileClosed$2(CodyFileEditorListener.java:48)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$applyAgentOnBackgroundThread$1.invoke$lambda$0(CodyAgentService.kt:83)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by taylorsperry** [comment]
Hey, @ceearrashee, Thank you for reporting! Could you please share what happened here and the steps to reproduce so we can make sure this gets prioritized? Thanks!

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/609
