### ISSUE TITLE
bug: Non-EDT thread exception in new enhanced context panel

### ISSUE THREAD

**Issue by steveyegge** [sourcegraph/jetbrains#344]
### Installation Information

Latest nightly as of 1/24.

### Describe the bug

com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Access is allowed from Event Dispatch Thread (EDT) only; see https://jb.gg/ij-platform-threading for details
Current thread: Thread[ApplicationImpl pooled thread 41,4,main] 2110361532 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 122581038
	at com.intellij.openapi.application.impl.ApplicationImpl.createThreadAccessException(ApplicationImpl.java:1083)
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1078)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1066)
	at com.intellij.ui.SpeedSearchBase.isPopupActive(SpeedSearchBase.java:210)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:55)
	at com.intellij.ui.speedSearch.SpeedSearchSupply.getSupply(SpeedSearchSupply.java:44)
	at com.intellij.ui.speedSearch.SpeedSearchUtil.applySpeedSearchHighlightingFiltered(SpeedSearchUtil.java:185)
	at com.intellij.ui.ColoredTreeCellRenderer.rendererComponentInner(ColoredTreeCellRenderer.java:129)
	at com.intellij.ui.ColoredTreeCellRenderer.getTreeCellRendererComponent(ColoredTreeCellRenderer.java:58)
	at com.intellij.ui.CheckboxTreeBase$CheckboxTreeCellRendererBase.getTreeCellRendererComponent(CheckboxTreeBase.java:164)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRenderer(DefaultTreeUI.java:189)
	at com.intellij.ui.tree.ui.DefaultTreeUI$2.getNodeDimensions(DefaultTreeUI.java:582)
	at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1451)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1272)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:967)
	at java.desktop/javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:181)
	at com.intellij.ui.tree.ui.DefaultTreeUI$3.setExpandedState(DefaultTreeUI.java:620)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:2003)
	at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:4295)
	at java.desktop/javax.swing.JTree.fireTreeExpanded(JTree.java:2855)
	at java.desktop/javax.swing.JTree.setExpandedState(JTree.java:3768)
	at java.desktop/javax.swing.JTree.expandPath(JTree.java:2298)
	at java.desktop/javax.swing.JTree.expandRow(JTree.java:2313)
	at com.sourcegraph.cody.context.ui.EnhancedContextPanel.<init>(EnhancedContextPanel.kt:63)

### Expected behavior

The bug happens when you open the IDE, and repro's for me every time I restart the IDE.

I was not able to repro this when building/running a local Cody.

**Comment by steveyegge** [comment]
https://github.com/sourcegraph/jetbrains/pull/345 with a proposed fix.

**Comment by mkondratek** [comment]
it looks to be related to https://github.com/sourcegraph/jetbrains/issues/354

**Comment by mkondratek** [comment]
To finalize the fix we should ensure that `project.getService(CodyToolWindowContent::class.java)` is called from the dispatched thread. Calling it for the first time (when Cody tool window has not been opened yet) invokes the constructor and all the related UI actions that need EDT. 

I suggest waiting with the fix until @pkukielka merges his https://github.com/sourcegraph/jetbrains/pull/349.

**Comment by taylorsperry** [comment]
@mkondratek I see that https://github.com/sourcegraph/jetbrains/pull/349 is closed. Does that mean this issue needs to be picked up? Seems like a P0 if it happens every time you restart the IDE, though I don't believe I'm able to repro: On 5.2.21709-nightly, I quit IntelliJ, toggled enhanced context on and off, and was able to ask Cody questions about my code when enhanced context was enabled.

**Comment by taylorsperry** [comment]
This still seems to be an issue. I'm closing this in favor of https://github.com/sourcegraph/jetbrains/issues/610 (which collects all of 'em).
