### ISSUE TITLE
bug: java.nio.file.InvalidPathException: Illegal char <"> at index 15: Microservices/{"typeTag":"com.intellij.microservices.ui.diagrams.model.MsDiagramWholeProjectSeed"}

### ISSUE THREAD

**Issue by magicprinc** [sourcegraph/jetbrains#355]
Plugin version: ```5.2.20247```
IDE version: ```IU-233.14015.106```
Exception: ```java.nio.file.InvalidPathException: Illegal char <"> at index 15: Microservices/{"typeTag":"com.intellij.microservices.ui.diagrams.model.MsDiagramWholeProjectSeed"}```
Stacktrace:
```text
java.nio.file.InvalidPathException: Illegal char <"> at index 15: Microservices/{"typeTag":"com.intellij.microservices.ui.diagrams.model.MsDiagramWholeProjectSeed"}
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt:18)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath$default(TextDocument.kt:17)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.agent.protocol.TextDocument.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.CodyFileEditorListener.lambda$fileClosed$2(CodyFileEditorListener.java:48)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$applyAgentOnBackgroundThread$1.invoke$lambda$0(CodyAgentService.kt:83)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by taylorsperry** [comment]
Hey, @magicprinc. Thanks so much for opening an issue! Can you please help me understand the error you're encountering so I can make sure we get this prioritized? Thank you!

**Comment by magicprinc** [comment]
@taylorsperry It happens from time to time 🤷‍♀️ I can't reproduce it.
How can I help you if it happens again?

I update IDEA and plugins frequently, so they are usually the most recent

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/609
