### ISSUE TITLE
bug: `CommandsTab` caches `project` on project close & open

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#356]
I managed to get this error:

```
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=Sourcegraph, containerState=DISPOSE_COMPLETED, componentStore=/Users/mkondratek/runIdeProjects/jetbrains) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:34)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:686)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:659)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:622)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:584)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getInstance(CodyAgentService.kt:106)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getAgent(CodyAgentService.kt:96)
	at com.sourcegraph.cody.agent.CodyAgentService.getAgent(CodyAgentService.kt)
	at com.sourcegraph.telemetry.GraphQlLogger.logEvent(GraphQlLogger.java:68)
	at com.sourcegraph.telemetry.GraphQlLogger.logCodyEvent(GraphQlLogger.java:35)
	at com.sourcegraph.cody.commands.ui.CommandsTabPanel.executeCommandWithContext$lambda$2(CommandsTabPanel.kt:47)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:295)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I started my investigation... 🕵️‍♂️
It looks like the component saves the previous `project` after I reopen the project.

## Steps to reproduce
1. open a project 
2. open Cody tool window (chat - it will initialize `CommandsTab` correctly)
3. run `Explain Code` from the context menu
4. it works
5. close Cody tool window
6. close the project
7. open the same project (or any other probably)
8. run `Explain Code` from the context menu
9. the error

## Expected behavior 
- the value of `project` is not cached on project closes & open events
- the context menu actions are enabled as soon as the agent is ready (regardless of Cody tool window being opened)

**Comment by mkondratek** [comment]
I estimate this one as **low effort**. 

However, we expect major changes to the related files (from https://github.com/sourcegraph/jetbrains/pull/155 and https://github.com/sourcegraph/jetbrains/pull/349). I suggest **we should wait for them** to be merged.
