### ISSUE TITLE
bug: java.lang.NoClassDefFoundError: com/intellij/dvcs/repo/VcsRepositoryManager

### ISSUE THREAD

**Issue by OfficialFox** [sourcegraph/jetbrains#366]
Plugin version: ```5.2.20247```
IDE version: ```JBC-232.10227.8```
Exception: ```java.lang.NoClassDefFoundError: com/intellij/dvcs/repo/VcsRepositoryManager```
Stacktrace:
```text
java.lang.NoClassDefFoundError: com/intellij/dvcs/repo/VcsRepositoryManager
	at com.sourcegraph.vcs.RepoUtil.getRemoteRepoUrl(RepoUtil.java:149)
	at com.sourcegraph.vcs.RepoUtil.getRemoteRepoUrlWithoutScheme(RepoUtil.java:134)
	at com.sourcegraph.vcs.RepoUtil.findRepositoryName(RepoUtil.java:96)
	at com.sourcegraph.cody.agent.CodyAgentCodebase.onFileOpened$lambda$1(CodyAgentCodebase.kt:24)
	at com.intellij.codeWithMe.ClientId$Companion.decorateRunnable$lambda$4(ClientId.kt:304)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassNotFoundException: com.intellij.dvcs.repo.VcsRepositoryManager PluginClassLoader(plugin=PluginDescriptor(name=Sourcegraph Cody + Code Search, id=com.sourcegraph.jetbrains, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\JetBrainsClient232.10227.8\plugins\Sourcegraph, version=5.2.20247, package=null, isBundled=false), packagePrefix=null, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:156)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more

```

**Comment by taylorsperry** [comment]
Hey, @OfficialFox. Thanks so much for opening an issue! Can you please help me understand the error you're encountering so I can make sure we get this prioritized? Thank you!
