### ISSUE TITLE
bug: IntelliJ plugin filled up disk with agent files

### ISSUE THREAD

**Issue by gabtorre** [sourcegraph/jetbrains#439]
### Installation Information

Cody plugin version 5.2.20247 

IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
Runtime version: 17.0.9+7-b1087.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3

### Describe the bug

The plugin seemed stuck in a loop, leading to excessive disk usage. Additionally, it created large temporary copies of the agent file during this process, with many of these logs:

```
2024-01-30 09:34:58,888 [86661021]   INFO - #CodyAgent - extracting Cody agent binary to /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
2024-01-30 09:34:58,920 [86661053]   INFO - #CodyAgent - starting Cody agent /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
```

To mitigate the issue, the user cleared all the files associated with the plugin, restarted the macOS, and then reenabled the plugin. After these actions, the plugin behaves correctly, with only two copies of the agent created.

It seems like the plugin may not clean up after itself properly, as indicated by the excessive number of temporary copies created during the loop.

### Expected behavior

The plugin cleans up temporary files appropriately to prevent excessive disk usage.

### Additional context (logs, images, etc)

Additional context: https://sourcegraph.slack.com/archives/C02842Z6YAK/p1706567669821759

```
2024-01-30 09:34:53,884 [86656017]   INFO - #CodyAgent - extracting Cody agent binary to /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent15487046631569367214
2024-01-30 09:34:53,918 [86656051]   INFO - #CodyAgent - starting Cody agent /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent15487046631569367214
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ getRgPath: Did not find bundled `rg`.
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:fileWatcherInit: watchers created
2024-01-30 09:34:55,094 [86657227]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ AuthProvider:init:lastEndpoint: https://sourcegraph.com/
2024-01-30 09:34:55,103 [86657236]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyIgnore:refresh:workspace: file:///Users/foo/bar/baz/.ijwb/
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatManager:constructor: init no local embeddings
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:constructor: init
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ vscode.commands.executeCommand: not found cody.chat.focus
2024-01-30 09:34:55,604 [86657737]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-01-30 09:34:57,037 [86659170]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase github.com/foo/bar
2024-01-30 09:34:57,037 [86659170]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-01-30 09:34:57,304 [86659437]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ Cody:publishConfig: configForWebview 
2024-01-30 09:34:57,304 [86659437]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase github.com/foo/bar
2024-01-30 09:34:57,305 [86659438]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ logEvent: CodyJetBrainsPlugin:Auth:failed JetBrains {"opts":{"agent":true}}
2024-01-30 09:34:57,305 [86659438]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.auth/failed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":2},{"key":"guardrails","value":0}]},"timestamp":"2024-01-29T20:34:57.300Z"}
2024-01-30 09:34:57,305 [86659438]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-01-30 09:34:57,327 [86659460]   INFO - #CodyAgent - Connected to Cody agent cody-agent
2024-01-30 09:34:57,565 [86659698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: evaluated export mode: 5.2.2-5.2.3
2024-01-30 09:34:58,886 [86661019]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:createWebviewPanel: 0
2024-01-30 09:34:58,887 [86661020]   WARN - #CodyAgent - Cody Agent shut down
2024-01-30 09:34:58,888 [86661021]   INFO - #CodyAgent - extracting Cody agent binary to /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
2024-01-30 09:34:58,920 [86661053]   INFO - #CodyAgent - starting Cody agent /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent8534747379058237572
... repeats
```

```
2024-01-30 08:17:01,833 [81983966]   WARN - #CodyAgent - Unable to start Cody agent
com.sourcegraph.cody.agent.CodyAgentException: failed to create agent binary
Caused by: java.nio.file.FileSystemException: /Users/foo/Library/Application Support/JetBrains/IntelliJIdea2023.3/plugins/Sourcegraph/agent/agent-macos-arm64 -> /var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T/cody-agent7707303340069661988: No space left on device
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:256)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:603)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:257)
	at java.base/java.nio.file.Files.copy(Files.java:1305)
	at CodyAgent$Companion.agentBinary(CodyAgent.kt:180)
	at CodyAgent$Companion.startAgentProcess(CodyAgent.kt:86)
	at CodyAgent$Companion.create(CodyAgent.kt:57)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$0(CodyAgentService.kt:37)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by mkondratek** [comment]
Hello @gabtorre 👋 I am sorry you suffer from this issue. Thanks for the detailed report 💟 

I understand that the plugin works correctly for you now (after the manual cleanup). 

We've seen a similar issue recently: https://github.com/sourcegraph/jetbrains/issues/315

Are you able to point the most common message in the logs? Is it: `WARN - #com.sourcegraph.cody.CodeFleEditorListener - server is null`? 

Hopefully, the newest version is not responsible for the wordy logging. We will revisit this issue and verify it.

**Comment by gabtorre** [comment]
Hey @mkondratek, In this case, rather than log files, there were thousands of `cody-agent7707303340069661988` or similar files from `/var/folders/z4/qq9brd3x7y9gxs52nc_3x6sm0000gn/T`.

**Comment by morgangauth** [comment]
I just received another report of this happening at another [customer](https://github.com/sourcegraph/accounts/issues/6036) . Slack thread can be found [here](https://sourcegraph.slack.com/archives/C02UM8A9M2R/p1706828104799179).

**Comment by olafurpg** [comment]
Thank you for reporting! This is a serious issues that we should prioritize fixing asap. This is not a recent regression, this behavior has been latent in the plugin since September. The root problem is that we never delete the temporary file that's created here

https://sourcegraph.com/github.com/sourcegraph/jetbrains@a5a1627c33cd4223ec28ffaeed393e87fd3de7e3/-/blob/src/main/kotlin/com/sourcegraph/cody/agent/CodyAgent.kt?L232

Adding logic to delete the file after the process finishes running should be an easy fix so I think it's safe to estimate that this will get resolved before the February 15th launch.

**Comment by olafurpg** [comment]
This PR https://github.com/sourcegraph/jetbrains/pull/566 should fix the root issue where the plugin is restarting a new (crashing) process in a loop. It's 10pm here right now so we will wait until Monday morning to make this fix available in a pre-release (aka. "nightly channel"). We will be cutting a new release (previously referred to as "stable channel") no later than Tuesday.
