### ISSUE TITLE
bug: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=fievel, containerState=DISPOSE_COMPLETED, componentStore=/Users/stanmay/Uber/fievel) (disposed))

### ISSUE THREAD

**Issue by tanmayuber** [sourcegraph/jetbrains#462]
Plugin version: ```5.2.20247```
IDE version: ```IU-232.8660.185```
Exception: ```com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=fievel, containerState=DISPOSE_COMPLETED, componentStore=/Users/stanmay/Uber/fievel) (disposed))```
Stacktrace:
```text
com.intellij.serviceContainer.AlreadyDisposedException: Cannot create light service com.sourcegraph.cody.agent.CodyAgentService because container is already disposed (container=Project(name=fievel, containerState=DISPOSE_COMPLETED, componentStore=/Users/stanmay/Uber/fievel) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkThatCreatingOfLightServiceIsAllowed(ComponentManagerImpl.kt:752)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:732)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getInstance(CodyAgentService.kt:106)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.getAgent(CodyAgentService.kt:96)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.isConnected(CodyAgentService.kt:101)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.didStatusChanged(CodyAutocompleteStatusService.kt:61)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.onCodyAutocompleteStatusReset$lambda$1(CodyAutocompleteStatusService.kt:41)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by pkukielka** [comment]
Thank you for reporting this issue. It is fixed in the [Cody release 5.3.3914](https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/edit/versions/stable/499571).
