### ISSUE TITLE
bug: java.nio.file.InvalidPathException: Illegal char <:> at index 6: Docker:4d3119dc9135aeb612ca04638865284cf1b0e9ca0eabf70398ffe45b45bb94e2:/workspace/BOOT-INF/classes/git.properties

### ISSUE THREAD

**Issue by magicprinc** [sourcegraph/jetbrains#466]
Plugin version: ```5.2.20247```
IDE version: ```IU-233.14015.106```
Exception: ```java.nio.file.InvalidPathException: Illegal char <:> at index 6: Docker:4d3119dc9135aeb612ca04638865284cf1b0e9ca0eabf70398ffe45b45bb94e2:/workspace/BOOT-INF/classes/git.properties```
Stacktrace:
```text
java.nio.file.InvalidPathException: Illegal char <:> at index 6: Docker:4d3119dc9135aeb612ca04638865284cf1b0e9ca0eabf70398ffe45b45bb94e2:/workspace/BOOT-INF/classes/git.properties
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:177)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt:18)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath$default(TextDocument.kt:17)
	at com.sourcegraph.cody.agent.protocol.TextDocument$Companion.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.agent.protocol.TextDocument.fromPath(TextDocument.kt)
	at com.sourcegraph.cody.CodyFocusChangeListener.lambda$focusGained$0(CodyFocusChangeListener.java:57)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion$applyAgentOnBackgroundThread$1.invoke$lambda$0(CodyAgentService.kt:83)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/609
