### ISSUE TITLE
Bug: UI was frozen during IDE startup

### ISSUE THREAD

**Issue by exigow** [sourcegraph/jetbrains#485]
One-time situation. After the restart, it was ok, but I had to kill the java.

```
2024-02-04 00:48:04,355 [ 138934]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities to files
2024-02-04 00:48:04,359 [ 138938]   WARN - #com.sourcegraph.cody.config.SettingsMigration - Unable to load user details for 'https://sourcegraph.com/' account
com.sourcegraph.cody.api.SourcegraphAuthenticationException: Request response: 401 Unauthorized
	at com.sourcegraph.cody.api.SourcegraphApiRequestExecutor.checkResponseCode(SourcegraphApiRequestExecutor.kt:102)
	at com.sourcegraph.cody.api.SourcegraphApiRequestExecutor.execute$lambda$4(SourcegraphApiRequestExecutor.kt:61)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:524)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:506)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:335)
	at com.sourcegraph.cody.api.SourcegraphApiRequestExecutor.execute(SourcegraphApiRequestExecutor.kt:50)
	at com.sourcegraph.cody.api.SourcegraphApiRequestExecutor.execute(SourcegraphApiRequestExecutor.kt:35)
	at com.sourcegraph.cody.api.SourcegraphApiRequests$CurrentUser.getDetails(SourcegraphApiRequests.kt:15)
	at com.sourcegraph.cody.config.SettingsMigration$loadUserDetails$1.invoke-IoAF18A(SettingsMigration.kt:180)
	at com.sourcegraph.cody.config.SettingsMigration$loadUserDetails$1.invoke(SettingsMigration.kt:176)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1$lambda$0(CompletableFutureUtil.kt:58)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.collaboration.async.CompletableFutureUtil.submitIOTask$lambda$1(CompletableFutureUtil.kt:58)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-02-04 00:48:04,368 [ 138947]   INFO - #c.i.o.p.i.j.JdkAuto - Looking for a local SDK for JDK with name SdkLookup{JDK, withVersionFilter}
2024-02-04 00:48:04,379 [ 138958]   INFO - #c.i.u.i.UnindexedFilesScanner - dfdbeb37: initial VFS refresh finished 227 ms
2024-02-04 00:48:04,380 [ 138959]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.util.indexing.DumbModeWhileScanningTrigger$DumbModeWhileScanning@51bfbc50
2024-02-04 00:48:04,381 [ 138960]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: UnindexedFilesScanner[spaceship-deck]
2024-02-04 00:48:04,382 [ 138961]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.util.indexing.DumbModeWhileScanningTrigger$DumbModeWhileScanning@51bfbc50
2024-02-04 00:48:04,382 [ 138961]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.util.indexing.UnindexedFilesScanner$2@ead13ac
2024-02-04 00:48:04,384 [ 138963]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.util.indexing.UnindexedFilesScanner$2@ead13ac
2024-02-04 00:48:04,384 [ 138963]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: UnindexedFilesScanner[spaceship-deck, 2 iterators]
2024-02-04 00:48:04,384 [ 138963]   INFO - #c.i.u.i.UnindexedFilesScanner - Started scanning for indexing of spaceship-deck. Reason: changes in: "Custom kind roots from entity (extensions, empty)", "Custom kind roots from entity (sass_functions.scss, sass_color.scss, sass_list.scss, ..., empty)"
2024-02-04 00:48:04,384 [ 138963]   INFO - #c.i.u.i.UnindexedFilesScanner - Performing delayed pushing properties tasks for spaceship-deck took 0ms; general responsiveness: ok; EDT responsiveness: ok
2024-02-04 00:48:04,385 [ 138964]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning of spaceship-deck uses 11 scanning threads
2024-02-04 00:48:04,405 [ 138984]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@263ee17f (reason: Push all on [com.intellij.openapi.roots.impl.JavaLanguageLevelPusher@57e8705])
2024-02-04 00:48:04,408 [ 138987]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@263ee17f (reason: Push all on [com.intellij.openapi.roots.impl.JavaLanguageLevelPusher@57e8705])
2024-02-04 00:48:04,408 [ 138987]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) UnindexedFilesIndexer[spaceship-deck, 1 iterators, reason: On project open]
2024-02-04 00:48:04,410 [ 138989]   INFO - #c.i.u.i.c.IndexUpdateRunner - Using 7 indexing  and 4 writing threads for indexing
2024-02-04 00:48:04,424 [ 139003]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning completed for spaceship-deck. Number of scanned files: 35; number of files for indexing: 0 took 40ms; general responsiveness: ok; EDT responsiveness: ok
2024-02-04 00:48:04,424 [ 139003]   INFO - #c.i.u.i.PerProjectIndexingQueue - Finished for spaceship-deck. No files to index with loading content.
2024-02-04 00:48:04,425 [ 139004]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: UnindexedFilesScanner[spaceship-deck, 2 iterators]
2024-02-04 00:48:04,572 [ 139151]   INFO - #c.i.u.i.ProjectChangedFilesScanner - Retrieving changed during indexing files of spaceship-deck : 3 to update, calculated in 0ms
2024-02-04 00:48:04,596 [ 139175]   INFO - #c.i.u.i.UnindexedFilesIndexer - Finished for spaceship-deck. Unindexed files update took 186ms; general responsiveness: ok; EDT responsiveness: ok
2024-02-04 00:48:04,597 [ 139176]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) UnindexedFilesIndexer[spaceship-deck, 1 iterators, reason: On project open]
2024-02-04 00:48:04,598 [ 139177]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.util.indexing.UnindexedFilesScanner$2@58000c82
2024-02-04 00:48:04,598 [ 139177]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.util.indexing.UnindexedFilesScanner$2@58000c82
2024-02-04 00:48:04,598 [ 139177]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: UnindexedFilesScanner[spaceship-deck, 1 iterators]
2024-02-04 00:48:04,598 [ 139177]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Running task: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@549f2da6 (reason: Push on VFS changes)
2024-02-04 00:48:04,599 [ 139178]   INFO - #c.i.u.i.UnindexedFilesScanner - Started scanning for indexing of spaceship-deck. Reason: changes in: "JDK 11 /usr/lib/jvm/java-11-openjdk"
2024-02-04 00:48:04,599 [ 139178]   INFO - #c.i.u.i.UnindexedFilesScanner - Performing delayed pushing properties tasks for spaceship-deck took 0ms; general responsiveness: ok; EDT responsiveness: ok
2024-02-04 00:48:04,599 [ 139178]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning of spaceship-deck uses 11 scanning threads
2024-02-04 00:48:04,599 [ 139178]   INFO - #c.i.o.p.MergingQueueGuiExecutor - Task finished: (dumb mode task) com.intellij.openapi.roots.impl.PushedFilePropertiesUpdaterImpl$MyDumbModeTask@549f2da6 (reason: Push on VFS changes)
2024-02-04 00:48:04,600 [ 139179]   INFO - #c.i.o.p.DumbServiceImpl - exit dumb mode [spaceship-deck]
2024-02-04 00:48:04,691 [ 139270]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:04,691 [ 139270]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ AuthProvider:init:lastEndpoint: https://sourcegraph.com/
2024-02-04 00:48:04,692 [ 139271]   INFO - #c.i.i.s.p.i.SharedIndexChunkConfigurationImpl - Chunk jdk-11.0.21-corretto-11.0.21-3183f394aec4-585ed96d is registered for project 'spaceship-deck: matching: (fb=81, stub=146), incompatible: (fb=0, stub=0), unknown: (fb=9, stub=9), 
2024-02-04 00:48:04,699 [ 139278]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyIgnore:refresh:workspace: file:///home/exigo/projects/spaceship-deck/
2024-02-04 00:48:04,859 [ 139438]   INFO - #c.i.i.s.download - There is no need to download shared indexes for JdkSharedIndexSuggestion(SharedIndexId(kind=jdk, url=https://index-cdn.jetbrains.com/v2/jdk, indexId=96c9a9b0a306b4247289174a41ba24484e1c795bc66ad087fce82b9dc984fa23#java version "11.0.20"), lazy). Similar compatible shared indexes are available locall...
2024-02-04 00:48:05,089 [ 139668]   INFO - #c.i.o.p.DumbServiceImpl - enter dumb mode [spaceship-deck]
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatManager:constructor: init no local embeddings
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:constructor: init
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:disposeWatchers: watchers disposed
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CommandsController:fileWatcherInit: watchers created
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - window.showErrorMessage: Continue setting up Cody
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,105 [ 139684]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,106 [ 139685]   INFO - #com.sourcegraph.cody.agent.CodyAgent - Connected to Cody agent cody-agent
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ Cody:publishConfig: configForWebview 
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ContextProvider:onConfigurationChange: using codebase 
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ logEvent: CodyJetBrainsPlugin:Auth:failed JetBrains {"opts":{"agent":true}}
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ telemetry-v2: recordEvent: cody.auth/failed: {"parameters":{"version":0,"metadata":[{"key":"contextSelection","value":2},{"key":"guardrails","value":0}]},"timestamp":"2024-02-03T23:48:05.101Z"}
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ CodyCompletionProvider:notSignedIn: You are not signed in.
2024-02-04 00:48:05,106 [ 139685]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ symf: using downloaded symf "/home/exigo/.local/share/Cody-nodejs/symf/symf-v0.0.5-x86_64-linux"
2024-02-04 00:48:05,114 [ 139693]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ symf: creating index file:///home/exigo/.local/share/Cody-nodejs/symf/indexroot/home/exigo/projects/spaceship-deck/
2024-02-04 00:48:05,119 [ 139698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:createWebviewPanel: 0
2024-02-04 00:48:05,119 [ 139698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView []
2024-02-04 00:48:05,119 [ 139698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider:registerWebviewPanel: registering webview panel
2024-02-04 00:48:05,119 [ 139698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView []
2024-02-04 00:48:05,119 [ 139698]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager: restorePanel
2024-02-04 00:48:05,120 [ 139699]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ ChatPanelsManager:createWebviewPanel: 0
2024-02-04 00:48:05,120 [ 139699]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView []
2024-02-04 00:48:05,120 [ 139699]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider:registerWebviewPanel: registering webview panel
2024-02-04 00:48:05,120 [ 139699]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView [{"displayName":"spaceship-deck","providers":[{"kind":"search","type":"local","state":"indexing"}]}]
2024-02-04 00:48:05,120 [ 139699]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView []
2024-02-04 00:48:05,120 [ 139699]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView [{"displayName":"spaceship-deck","providers":[{"kind":"search","type":"local","state":"indexing"}]}]
2024-02-04 00:48:05,322 [ 139901]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ GraphQLTelemetryExporter: evaluated export mode: 5.2.5+
2024-02-04 00:48:05,377 [ 139956]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: handleInitialized
2024-02-04 00:48:05,378 [ 139957]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,378 [ 139957]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: handleInitialized
2024-02-04 00:48:05,378 [ 139957]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ VSCodeSecretStorage:getAccessToken: failed 
2024-02-04 00:48:05,379 [ 139958]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: updateViewConfig 
2024-02-04 00:48:05,379 [ 139958]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: updateViewConfig 
2024-02-04 00:48:05,404 [ 139983]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView [{"displayName":"spaceship-deck","providers":[{"kind":"search","type":"local","state":"ready"}]}]
2024-02-04 00:48:05,404 [ 139983]   WARN - #com.sourcegraph.cody.agent.CodyAgentClient - Cody by Sourcegraph: █ SimpleChatPanelProvider: postContextStatusToWebView [{"displayName":"spaceship-deck","providers":[{"kind":"search","type":"local","state":"ready"}]}]
2024-02-04 00:50:45,740 [ 300319]   INFO - #AiAgreementUpdater - Requesting AI Terms of Service update...
2024-02-04 00:50:46,063 [ 300642]   INFO - #AiAgreementUpdater - No updated AI Terms of Service version is available
2024-02-04 00:50:47,779 [ 302358]   INFO - #c.i.m.l.c.license - AI Pro license is not available, AI Lite licenses is available
2024-02-04 00:50:47,779 [ 302358]   INFO - #c.i.m.l.c.g.GrazieJbaAuthService - Information about license was changed...
2024-02-04 00:50:47,779 [ 302358]   INFO - #c.i.m.l.c.g.GrazieJbaAuthService - Selected license was changed -> log out from AI Platform
2024-02-04 00:53:14,842 [ 449421]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 309774ms, details saved to /home/exigo/.cache/JetBrains/IntelliJIdea2023.3/log/threadDumps-freeze-20240204-004810-IU-233.11799.241-FileDispatcherImpl.read0-309sec
2024-02-04 00:53:34,889 [ 469468]   WARN - #c.i.d.PerformanceWatcherImpl - UI was frozen for 20050ms, details saved to /home/exigo/.cache/JetBrains/IntelliJIdea2023.3/log/threadDumps-freeze-20240204-005319-IU-233.11799.241-FileDispatcherImpl.read0-20sec
```

**Comment by taylorsperry** [comment]
Hey, @exigow, Can you help me understand this issue and how likely it is that a user would run into it?

**Comment by exigow** [comment]
More details:

It happened once while launching one of my projects. I took a screenshot for the record, but it seems unrelated to the "Checking for plugin updates" process according to stacktrace. 

I was not able to reproduce this again.

![Selection_065](https://github.com/sourcegraph/jetbrains/assets/5013708/e7c3e7ef-6e9e-453f-9e87-8bd9a221443a)

**Comment by taylorsperry** [comment]
Labeling as a `P2` since you couldn't repro, but lmk if you disagree.
