### ISSUE TITLE
bug: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false

### ISSUE THREAD

**Issue by akalia25** [sourcegraph/jetbrains#572]
Steps to reproduce: Updated Sourcegraph extension on PyCharm Pro and signed in with my S2 accounts and tried interacting with chat. I think this happens when there is a large repo to index and Cody has not finished indexing so it throws a panic? 🤷 

Plugin version: ```5.2.21709```
IDE version: ```PY-221.5787.24```
Exception: ```com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false```
Stacktrace:
```text
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: EventQueue.isDispatchThread()=false
Current thread: Thread[ApplicationImpl pooled thread 12,4,main] 1779070285
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 691930767
	at com.intellij.openapi.application.impl.ApplicationImpl.throwThreadAccessException(ApplicationImpl.java:1103)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1086)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:166)
	at com.intellij.ide.impl.DataManagerImpl.getDataContext(DataManagerImpl.java:197)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.<init>(DialogWrapperPeerImpl.java:85)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerFactoryImpl.createPeer(DialogWrapperPeerFactoryImpl.java:25)
	at com.jetbrains.rdserver.ui.dialogs.BackendDialogWrapperPeerFactory.createPeer(BackendDialogWrapperPeerFactory.kt:51)
	at com.intellij.openapi.ui.DialogWrapper.createPeer(DialogWrapper.java:857)
	at com.intellij.openapi.ui.DialogWrapper.<init>(DialogWrapper.java:232)
	at com.intellij.ui.messages.AlertDialog.<init>(AlertMessagesManager.kt:98)
	at com.intellij.ui.messages.AlertMessagesManager.showMessageDialog(AlertMessagesManager.kt:63)
	at com.intellij.ui.messages.MessagesServiceImpl.showMessageDialog(MessagesServiceImpl.java:49)
	at com.jetbrains.rdserver.ui.BackendMessagesService.showMessageDialog(BackendMessagesService.kt:29)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:604)
	at com.intellij.openapi.ui.Messages.showErrorDialog(Messages.java:619)
	at com.sourcegraph.cody.context.ui.ReindexButton$actionPerformed$1$1.run(ReindexButton.kt:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/610

**Comment by pkukielka** [comment]
That is indeed indexer failure, but reported error is misleading due to old bug in the reporting code.
It was since fixed by https://github.com/sourcegraph/jetbrains/pull/593

@akalia25 if you could upgrade to newer Cody version and try again that would be awesome.
Even if you will get the error again (possible) it should contain more useful info which will help us fixing it for good.
