### ISSUE TITLE
JetBrains: slow operation error

### ISSUE THREAD

**Issue by olafurpg** [sourcegraph/jetbrains#60]
I'm seeing this warning in my idea.log
```
2023-10-25 14:00:39,249 [ 123055] SEVERE - #c.i.u.SlowOperations - Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertSlowOperationsAreAllowed(SlowOperations.java:95)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:130)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:75)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:247)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSetWithCustomData(WorkspaceFileIndexImpl.kt:230)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:147)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getContentRootForFile(ProjectFileIndexImpl.java:141)
	at com.sourcegraph.common.ProjectFileUtils.getRelativePathToProjectRoot(ProjectFileUtils.java:14)
	at com.sourcegraph.cody.context.CurrentlyOpenFileListener.selectionChanged(CurrentlyOpenFileListener.java:28)
```

**Comment by olafurpg** [comment]
Another error
```
2023-10-25 14:12:23,024 [  50647] SEVERE - #c.i.u.SlowOperations - Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
java.lang.Throwable: Slow operations are prohibited on EDT. See SlowOperations.assertSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:109)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.get(PasswordSafeImpl.kt:93)
	at com.sourcegraph.cody.auth.AccountManagerBase.findCredentials(AccountManagerBase.kt:109)
	at com.sourcegraph.cody.config.CodyAccountDetailsProvider.scheduleLoad(CodyAccountDetailsProvider.kt:26)
	at com.sourcegraph.cody.config.CodyAccountDetailsProvider.scheduleLoad(CodyAccountDetailsProvider.kt:15)
	at com.sourcegraph.cody.auth.ui.LoadingAccountsDetailsProvider.getOrLoad(LoadingAccountsDetailsProvider.kt:34)
```

**Comment by mkondratek** [comment]
`getRelativePathToProjectRoot ` fixed by https://github.com/sourcegraph/jetbrains/issues/246.
`findCredentials` closing in favour of https://github.com/sourcegraph/jetbrains/issues/247.
