### ISSUE TITLE
bug: com.intellij.diagnostic.PluginException: 504 ms to call on EDT CodyStatusBarActionGroup#Update@popup (com.sourcegraph (...)

### ISSUE THREAD

**Issue by mkondratek** [sourcegraph/jetbrains#631]
Plugin version: ```5.2.23857-nightly```
IDE version: ```IU-233.13135.103```
Stacktrace:
```text
com.intellij.diagnostic.PluginException: 504 ms to call on EDT CodyStatusBarActionGroup#Update@popup (com.sourcegraph.cody.statusbar.CodyStatusBarActionGroup). Revise AnAction.getActionUpdateThread property [Plugin: com.sourcegraph.jetbrains]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt(ActionUpdater.kt:223)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.access$computeOnEdt(ActionUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$1.invokeSuspend(ActionUpdater.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: java.lang.Throwable: EDT-trace-at-317-ms (5/5)
		at java.base@17.0.9/jdk.internal.misc.Unsafe.park(Native Method)
		at java.base@17.0.9/java.util.concurrent.locks.LockSupport.park(LockSupport.java:211)
		at java.base@17.0.9/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1864)
		at java.base@17.0.9/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3465)
		at java.base@17.0.9/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3436)
		at java.base@17.0.9/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1898)
		at java.base@17.0.9/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
		at com.sourcegraph.cody.statusbar.CodyStatusBarActionGroup.deriveWarningAction(CodyStatusBarActionGroup.kt:45)
		at com.sourcegraph.cody.statusbar.CodyStatusBarActionGroup.update(CodyStatusBarActionGroup.kt:26)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:164)
		at com.intellij.openapi.actionSystem.ex.ActionUtil$$Lambda$1290/0x0000000800d26430.run(Unknown Source)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:187)
		at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.doUpdate(ActionUpdater.kt:696)
		at com.intellij.openapi.actionSystem.impl.ActionUpdaterKt.access$doUpdate(ActionUpdater.kt:1)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateActionReal$success$1.invoke(ActionUpdater.kt:110)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateActionReal$success$1.invoke(ActionUpdater.kt:109)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$callAction$4.invoke(ActionUpdater.kt:178)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$2.invoke(ActionUpdater.kt:204)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1$1.invoke(ActionUpdater.kt:468)
		at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:321)
		at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:198)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
		at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
		at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
		at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:197)
		at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1.invokeSuspend(ActionUpdater.kt:467)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at com.intellij.openapi.actionSystem.impl.UtilsKt$runBlockingForActionExpand$1.invoke(Utils.kt:1108)
		at com.intellij.openapi.actionSystem.impl.UtilsKt$runBlockingForActionExpand$1.invoke(Utils.kt:1105)
		at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:86)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupImpl(Utils.kt:1130)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.kt:296)
		at com.intellij.ui.popup.ActionStepBuilder.appendActionsFromGroup(ActionStepBuilder.java:103)
		at com.intellij.ui.popup.ActionStepBuilder.buildGroup(ActionStepBuilder.java:69)
		at com.intellij.ui.popup.ActionPopupStep.createActionItems(ActionPopupStep.java:126)
		at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.createStep(PopupFactoryImpl.java:279)
		at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:237)
		at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:219)
		at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.<init>(PopupFactoryImpl.java:186)
		at com.intellij.ui.popup.PopupFactoryImpl.createActionGroupPopup(PopupFactoryImpl.java:371)
		at com.jetbrains.rdserver.ui.popup.BackendBePopupFactory.createActionGroupPopup(BackendBePopupFactory.kt:111)
		at com.intellij.openapi.ui.popup.JBPopupFactory.createActionGroupPopup(JBPopupFactory.java:254)
		at com.jetbrains.rdserver.ui.popup.BackendBePopupFactory.createActionGroupPopup(BackendBePopupFactory.kt:165)
		at com.sourcegraph.cody.statusbar.CodyStatusBarWidget.createPopup(CodyStatusBarWidget.kt:33)
		at com.intellij.openapi.wm.impl.status.EditorBasedStatusBarPopup.showPopup(EditorBasedStatusBarPopup.kt:215)
		at com.intellij.openapi.wm.impl.status.EditorBasedStatusBarPopup.access$showPopup(EditorBasedStatusBarPopup (...)
```

I just opened a project. 

@pkukielka, this is something we've been talking about some time ago. It seems to be rare but we should rethink our solution.

**Comment by taylorsperry** [comment]
closing in favor of https://github.com/sourcegraph/jetbrains/issues/610
