### ISSUE TITLE
bug: com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see  (...)

### ISSUE THREAD

**Issue by nirzaf** [sourcegraph/jetbrains#663]
Plugin version: ```5.3.27```
IDE version: ```RD-233.14015.60```
Stacktrace:
```text
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[AWT-EventQueue-0,6,main] 1838182472 (EventQueue.isDispatchThread()=true)
SystemEventQueueThread: (same)
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:149)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:107)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1012)
	at com.intellij.openapi.editor.impl.CaretImpl.getOffset(CaretImpl.java:664)
	at com.intellij.openapi.editor.impl.CaretImpl.getSelectionStartPosition(CaretImpl.java:941)
	at com.intellij.openapi.editor.SelectionModel.getSelectionStartPosition(SelectionModel.java:45)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.getSelection(CodyEditorFactoryListener.kt:141)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.informAgentAboutEditorChange(CodyEditorFactoryListener.kt:166)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener$Util.informAgentAboutEditorChange$default(CodyEditorFactoryListener.kt:160)
	at com.sourcegraph.cody.autocomplete.CodyEditorFactoryListener.editorCreated(CodyEditorFactoryListener.kt:42)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.lambda$doCreateEditor$4(EditorFactoryImpl.java:229)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.forEachExtensionSafe(ExtensionProcessingHelper.kt:34)
	at com.intellij.openapi.extensions.ExtensionPointName.forEachExtensionSafe(ExtensionPointName.kt:50)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.doCreateEditor(EditorFactoryImpl.java:229)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:203)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:158)
	at com.intellij.ui.EditorTextField.createEditor(EditorTextField.java:678)
	at yinzhengfei.ai.coding.cK.createEditor(EditorFragment.java:104)
	at com.intellij.ui.EditorTextField.initEditorInner(EditorTextField.java:544)
	at com.intellij.ui.EditorTextField.initEditor(EditorTextField.java:529)
	at com.intellij.ui.EditorTextField.getEditor(EditorTextField.java:960)
	at com.intellij.ui.EditorTextField.getPreferredSize(EditorTextField.java:862)
	at yinzhengfei.ai.coding.cK.getPreferredSize(EditorFragment.java:135)
	at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:724)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.panels.Wrapper.getPreferredSize(Wrapper.java:115)
	at com.intellij.openapi.roots.ui.componentsList.layout.SizeProperty$1.getSize(SizeProperty.java:28)
	at com.intellij.openapi.roots.ui.componentsList.layout.ComponentOperation$SizeCalculator.applyTo(ComponentOperation.java:28)
	at com.intellij.openapi.roots.ui.componentsList.layout.VerticalStackLayout.withAllVisibleDo(VerticalStackLayout.java:30)
	at com.intellij.openapi.roots.ui.componentsList.layout.VerticalStackLayout.preferredLayoutSize(VerticalStackLayout.java:56)
	at java.desktop/java.awt.Container.lambda$preferredSize$4(Container.java:1826)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1824)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1723)
	at com.intellij.ui.components.panels.Wrapper.getPreferredSize(Wrapper.java:115)
	at yinzhengfei.ai.coding.cD.getPreferredSize(ChatNonOpaquePanel.java:207)
	at com.intellij.openapi.editor.impl.EditorImpl$PanelWithFloatingToolbar.doLayout(EditorImpl.java:5541)
	at java.desktop/java.awt.Container.validateTree(Container.java:1725)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.validateTree(Container.java:1734)
	at java.desktop/java.awt.Container.lambda$validate$3(Container.java:1659)
	at java.desktop/sun.awt.SunToolkit.performWithTreeLock(SunToolkit.java:2161)
	at java.desktop/java.awt.Container.validate(Container.java:1648)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:760)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:758)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:757)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1908)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEven (...)
```

**Comment by nirzaf** [comment]
duplicated
