### ISSUE TITLE
bug: java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by AlphaJanus** [sourcegraph/jetbrains#719]
Plugin version: ```5.3.27```
IDE version: ```PS-233.13135.108```
Stacktrace:
```text
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.getNow(CompletableFuture.java:2134)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.isConnected(CodyAgentService.kt:143)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.didStatusChanged(CodyAutocompleteStatusService.kt:64)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.onCodyAutocompleteStatusReset$lambda$1(CodyAutocompleteStatusService.kt:43)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:82)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	... 7 more
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:69)
	... 12 more

```

**Comment by pkukielka** [comment]
Hey @AlphaJanus , would it be possible for you to provide us a full [idea.log ](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) so we can investigate this issue more effectively?

**Comment by AlphaJanus** [comment]
> Hey @AlphaJanus , would it be possible for you to provide us a full [idea.log ](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files) so we can investigate this issue more effectively?

Sure, here it is.
[idea.log](https://github.com/sourcegraph/jetbrains/files/14330436/idea.log)

**Comment by pkukielka** [comment]
Thank you very much! Looks like it fails to download indexer for a local repo.
I will make sure we fix this one with proper priority (most likely I will pick it up next).

**Comment by AlphaJanus** [comment]
Thanks. If you need any assistance in testing - feel fee yo write here)

**Comment by AlphaJanus** [comment]
> Thank you very much! Looks like it fails to download indexer for a local repo. I will make sure we fix this one with proper priority (most likely I will pick it up next).

Thanks. If you need any assistance in testing - feel fee to write here)
By the way, according to your comment, i made Reindexing local project, and restarted Idea, and it started working. But i was working on the same project with Cody for some time. Anyway, it is not the first time when this issue happened, so i guess there must be some bad reason for that.

**Comment by taylorsperry** [comment]
Closing in favor of https://github.com/sourcegraph/jetbrains/issues/723
