### ISSUE TITLE
JetBrains: "java.util.concurrent.TimeoutException" while switching between different accounts.

### ISSUE THREAD

**Issue by jay-fibi** [sourcegraph/jetbrains#786]
### Installation Information

Plugin version: ```5.3.27```
IDE version: ```IC-233.14475.28```

### Describe the bug

**Steps to reproduce:**

1. Have Cody plugin installed in your JetBrains IntelliJ IDEA editor
2. User is already logged in to Cody with Free subscription
3. Go to Cody Settings and switch account to any other account you have added.
4. Wait for some time

**Observed behavior:**
TimeoutException error occurred while switching to another account with below stacktrace,

Stacktrace:
```text
java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:69)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

### Expected behavior

User should be able to switch account without any errors. 

### Additional context (logs, images, etc)

This is working fine for MacOS. This is occurred with Windows 10.

**Video link:**
https://drive.google.com/file/d/1njL6Z__05t1P9g2lfjNxlteDe3-Yv3c7/view?usp=drive_link

**Comment by pkukielka** [comment]
It's one of the ways in which this issue is manifesting:
https://github.com/sourcegraph/jetbrains/issues/723
Closing this one in favour of the tracking one.
