### ISSUE TITLE
bug: java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent

### ISSUE THREAD

**Issue by basheer-taplane** [sourcegraph/jetbrains#806]
Plugin version: ```5.3.27```
IDE version: ```PS-231.9225.18```
Stacktrace:
```text
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
	at java.base/java.util.concurrent.CompletableFuture.getNow(CompletableFuture.java:2134)
	at com.sourcegraph.cody.agent.CodyAgentService$Companion.isConnected(CodyAgentService.kt:143)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.didStatusChanged(CodyAutocompleteStatusService.kt:64)
	at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.onCodyAutocompleteStatusReset$lambda$1(CodyAutocompleteStatusService.kt:43)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:252)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.Exception: Failed to start Cody agent
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:82)
	... 10 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at f (C:\snapshot\dist\agent.js)
    at e3.t3 (C:\snapshot\dist\agent.js)
    at new e3 (C:\snapshot\dist\agent.js)
    at Function.parse (C:\snapshot\dist\agent.js)
    at _Uri.parse (C:\snapshot\dist\agent.js)
    at C:\snapshot\dist\agent.js
    at MessageDecoder.callback (C:\snapshot\dist\agent.js)
    at MessageDecoder._write (C:\snapshot\dist\agent.js)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:537:28)
    at Socket.emit (node:domain:482:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:69)
	... 10 more
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")

Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at f (C:\snapshot\dist\agent.js)
    at e3.t3 (C:\snapshot\dist\agent.js)
    at new e3 (C:\snapshot\dist\agent.js)
    at Function.parse (C:\snapshot\dist\agent.js)
    at _Uri.parse (C:\snapshot\dist\agent.js)
    at C:\snapshot\dist\agent.js
    at MessageDecoder.callback (C:\snapshot\dist\agent.js)
    at MessageDecoder._write (C:\snapshot\dist\agent.js)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:537:28)
    at Socket.emit (node:domain:482:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	... 1 more

```

**Comment by mkondratek** [comment]
hello @basheer-taplane 👋 I am sorry you encountered this problem 🙇 

can you share more details? are you using WSL? (possible rel: https://github.com/sourcegraph/jetbrains/issues/138)

**Comment by basheer-taplane** [comment]
Yes, I'm using WSL 2

**Comment by pkukielka** [comment]
Definitely looks like the same issue. 
Let me close this one just and use earlier one (#138) as a tracking issue.

**Comment by mkondratek** [comment]
Hi @basheer-taplane  👋 can you please update the plugin to [6.0.25](https://plugins.jetbrains.com/plugin/9682-cody-ai-coding-assistant-with-autocomplete--chat/versions/stable/584093?noRedirect=true)? 🙏 the issue with WSL should be resolved now 😌
