### ISSUE TITLE
bug: Text file busy

### ISSUE THREAD

**Issue by yuriyDne** [sourcegraph/jetbrains#819]
Plugin version: `5.3.27`
IDE version: `PS-233.14475.35`
Stacktrace:

```text
java.util.concurrent.CompletionException: java.lang.Exception: Failed to start Cody agent
 at java.base/java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:413)
 at java.base/java.util.concurrent.CompletableFuture.getNow(CompletableFuture.java:2134)
 at com.sourcegraph.cody.agent.CodyAgentService$Companion.isConnected(CodyAgentService.kt:143)
 at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.didStatusChanged(CodyAutocompleteStatusService.kt:64)
 at com.sourcegraph.cody.statusbar.CodyAutocompleteStatusService.onCodyAutocompleteStatusReset$lambda$1(CodyAutocompleteStatusService.kt:43)
 at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
 at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
 at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
 at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
 at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Failed to start Cody agent
 at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:82)
 ... 12 more
Caused by: java.io.IOException: Cannot run program "/tmp/cody-agent7361161579419492637": error=26, Text file busy
 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
 at com.sourcegraph.cody.agent.CodyAgent$Companion.startAgentProcess(CodyAgent.kt:163)
 at com.sourcegraph.cody.agent.CodyAgent$Companion.create(CodyAgent.kt:99)
 at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:69)
 ... 12 more
Caused by: java.io.IOException: error=26, Text file busy
 at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
 at java.base/java.lang.ProcessImpl.(ProcessImpl.java:314)
 at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
 at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
 ... 16 more
 
```

**Comment by mkondratek** [comment]
Hello @yuriyDne 👋 this is something new 😮 

Can you share more details? 🙏 

Steps to reproduce, installation info (in IDE: trigger the action "About", click on "Copy and close" and paste the output here), etc can help us 🙂 

Is this issue blocking you from using the plugin? Can you re-try in the latest version (for today it's [5.3.1544](https://plugins.jetbrains.com/plugin/9682-sourcegraph-cody--code-search/versions/stable/492105))?
