### ISSUE TITLE
bug:   Failed to start Cody agent

### ISSUE THREAD

**Issue by pinakig22** [sourcegraph/jetbrains#871]
Plugin version: ```5.3.27```
IDE version: ```IC-232.9921.47```
Stacktrace:
```text
  Failed to start Cody agent
  
  java.util.concurrent.TimeoutException
at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
at com.sourcegraph.cody.agent.CodyAgentService.startAgent$lambda$3(CodyAgentService.kt:69)
at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:272)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by mkondratek** [comment]
hello @pinakig22 👋 I am sorry you encountered this issue. as a quick workaround you can try a better internet connection. 

we have a few improvements that should make this issue appear less frequently, we hope to release them soon (within a week). I kindly ask you for some patience 🙏 

I am closing this issue in favour of https://github.com/sourcegraph/jetbrains/issues/723
